/******************************************************************************
 **  Copyright (c) 2006-2025, Calaos. All Rights Reserved.
 **
 **  This file is part of Calaos.
 **
 **  Calaos is free software; you can redistribute it and/or modify
 **  it under the terms of the GNU General Public License as published by
 **  the Free Software Foundation; either version 3 of the License, or
 **  (at your option) any later version.
 **
 **  Calaos is distributed in the hope that it will be useful,
 **  but WITHOUT ANY WARRANTY; without even the implied warranty of
 **  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 **  GNU General Public License for more details.
 **
 **  You should have received a copy of the GNU General Public License
 **  along with Foobar; if not, write to the Free Software
 **  Foundation, Inc., 51 Franklin St, Fifth Floor, Boston, MA  02110-1301  USA
 **
 ******************************************************************************/
#ifndef S_JSONAPI_CHARACTERIZATION_H
#define S_JSONAPI_CHARACTERIZATION_H

/*******************************************************************************
 * E4.0a - Characterization harness for the JSON API (port 5454).
 *
 * READ THIS BEFORE WRITING A SINGLE ASSERTION. Sub-tickets E4.0b..E4.0f are
 * expected to use this file and nothing else as their entry point; you should
 * not need to read JsonApiCharacterization.cpp to use it.
 *
 * ---------------------------------------------------------------------------
 * WHAT THIS IS FOR
 * ---------------------------------------------------------------------------
 * Freezing the OBSERVABLE behaviour of the JSON API before the jansson ->
 * nlohmann migration (E4.1). It records what the code does TODAY, bugs
 * included. It fixes nothing, it improves nothing. If a test here looks like
 * it pins a bug, it does, on purpose (see "KNOWN DIVERGENCES" below).
 *
 * ---------------------------------------------------------------------------
 * THE ORACLE - NON NEGOTIABLE
 * ---------------------------------------------------------------------------
 * Comparison is SEMANTIC: both sides are parsed with nlohmann::json::parse()
 * and compared with operator==. Consequences, all of them wanted:
 *
 *   - INSENSITIVE to key order, by construction (a nlohmann object is a
 *     std::map). jansson preserves insertion order, nlohmann sorts keys, and
 *     the user has ALREADY accepted that change of order. The tree even emits
 *     the WS envelope in two different key orders today depending on which
 *     sendJson() overload is used (JsonApiHandlerWS.cpp:63-73 gives
 *     msg,msg_id,data; :75-85 gives data,msg,msg_id) - clients already live
 *     with both. ⚠️ E4.1s DELETED the jansson overload: one envelope order is
 *     left, the sorted one, plus the no-data envelope of sendJsonNoData(),
 *     which OMITS the key rather than writing a null.
 *   - SENSITIVE to array order. The order of rooms, IOs and rules IS
 *     semantic (it drives evaluation order, invariant of the E4.2 series).
 *     NEVER sort an array before comparing.
 *   - STRICT on types: "3" != 3. A migration that "improves" a stringified
 *     number into a real JSON number must break the test. That is the point.
 *
 * COMPARING SERIALIZED JSON STRINGS IS FORBIDDEN AND WILL BE REJECTED IN
 * REVIEW. Concretely, never write any of:
 *      EXPECT_EQ(payload, "{\"a\":\"b\"}");
 *      EXPECT_EQ(j.dump(), golden);
 *      EXPECT_EQ(j.dump(-1, ' ', true, Json::error_handler_t::replace), "...");
 *      any assertion on key order or on the length of a JSON string.
 * Use EXPECT_JSON_EQ / ASSERT_JSON_EQ / EXPECT_JSON_GOLDEN below. They accept
 * a raw std::string of JSON text and parse it for you - passing the captured
 * payload straight in is both correct and the shortest thing to write, so
 * there is no reason to hand-roll a string compare.
 *
 * On failure the assertion prints the JSON-pointer path of the FIRST diverging
 * node (e.g. /home/2/items/5/state) with expected and actual. A raw EXPECT_EQ
 * on a 200-key object is unusable and would make the migration miserable.
 *
 * ---------------------------------------------------------------------------
 * GOLDEN FILES
 * ---------------------------------------------------------------------------
 * Stored one per case in tests/core/golden/<name>.json, UTF-8, dump(2).
 * They are GENERATED BY THE CODE, never hand written:
 *
 *      CALAOS_GOLDEN_UPDATE=1 ./core/JsonApiCharacterization_test
 *
 * rewrites every golden the run touches, then you re-read the diff and commit
 * it. A golden that was hand-edited to look "clean" is worthless: it would
 * describe the desirable, not the existing.
 *
 * Goldens are located through, in order: $CALAOS_GOLDEN_DIR, the compile-time
 * -DCALAOS_GOLDEN_DIR passed by tests/Makefile.am, $srcdir/core/golden, then a
 * couple of relative fallbacks. You do not need to care unless you run the
 * binary by hand from an unusual directory.
 *
 * ---------------------------------------------------------------------------
 * THE THREE POINTS E4.0a HAD TO SETTLE, AND HOW THEY WERE SETTLED
 * ---------------------------------------------------------------------------
 * (a) HttpClient::getClientIp() - stub in the test unit, or link the real
 *     HttpClient.o?  MEASURED: `nm -Cu JsonApiHandlerWS.o` shows exactly one
 *     HttpClient symbol needed (getClientIp), so a stub WOULD be enough for a
 *     WS-only binary. But `nm -Cu JsonApiHandlerHttp.o` needs three
 *     (getClientIp, buildHttpResponse, buildHttpResponseFromFile), and
 *     buildHttpResponse() is exactly the production logic E4.0e must
 *     characterize (headers, Content-Length, conn_close). Stubbing it would
 *     characterize the stub. DECISION: LINK the real HttpClient.o and its
 *     closure (the block is already written, tested and green for
 *     core/RemoteUIDeviceInfo_test). No stub anywhere in this harness.
 *
 * (b) JsonApiHandlerHttp needs a non-null HttpClient (sendLoginFailed() and
 *     sendJson() dereference it without a guard). MEASURED: constructing
 *     HttpClient on an UNCONNECTED uvw::TcpHandle works - buildHttpResponse()
 *     is pure string formatting over member state, getClientIp() is null and
 *     exception safe and answers "unknown", and ~HttpClient() does not touch
 *     the socket. So the HTTP transport is characterizable end to end.
 *     CONSTRAINT, carried into the design: buildHttpResponse() MUTATES the
 *     connection state (resHeaders accumulates, conn_close flips,
 *     HttpClient.cpp:552-566), therefore ONE FRESH HttpClient PER REQUEST is
 *     MANDATORY. HttpTestRequest below enforces it: one object, one request,
 *     reuse is refused.
 *
 * (c) Event delivery needs the uvw loop pumped. EventManager::appendEvent()
 *     queues into an Idler (EventManager.cpp:46-54) and CalaosCoreFixture.h
 *     documents that the queue simply grows in tests. MEASURED: a single
 *     uvw::Loop::getDefault()->run<NOWAIT>() is enough to fire the idler and
 *     get the WS "event" envelope out; pumpEventLoop() below runs a few
 *     iterations so the close callbacks of the one-shot idle handle also run.
 *     Asserting right after EventManager::create() without pumping always
 *     sees zero messages. E4.0d owns the event cases; the pump is here.
 *
 * ---------------------------------------------------------------------------
 * TRAPS THIS HARNESS SETS FOR YOU - READ BEFORE DEBUGGING A WEIRD FAILURE
 * ---------------------------------------------------------------------------
 * 1. DESTROYING AN HttpTestRequest FLUSHES THE EVENT QUEUE. Its destructor
 *    calls pumpEventLoop(2) to run the uv close callbacks of the TcpHandle it
 *    allocated. That also fires the EventManager idler. So an HTTP request
 *    going out of scope silently delivers every queued event to every live WS
 *    session. This one is aimed straight at E4.0d: if a case mixes an HTTP
 *    request with an event expectation, scope the request explicitly, or
 *    snapshot ws.count() before and after instead of assuming nothing moved.
 *
 * 2. AN HttpTestRequest KEPT ALIVE ACROSS A LONG PUMP WILL FIRE A TIMER.
 *    HttpClient's constructor (HttpClient.cpp:145-153) installs a LIVE read
 *    timeout Timer whose callback calls CloseConnection() - on a handle that
 *    was never connected. Harmless today because every case here destroys the
 *    request long before the timeout, and pumpEventLoop() only runs a handful
 *    of NOWAIT iterations. A sub-ticket that holds a request across a longer
 *    or repeated pump will trip it. Keep HttpTestRequest objects short lived.
 *
 * 3. PROVING A MUTATION RED REQUIRES DELETING TWO FILES, NOT ONE. Every test
 *    binary in this tree overrides <name>_DEPENDENCIES, which removes the
 *    objects of src/bin/calaos_server from its prerequisites. Rebuilding one
 *    .o therefore does NOT relink the test binary: make answers "is up to
 *    date" and the OLD binary runs again, green. Measured live on this very
 *    binary during E4.0a. So:
 *        rm -f src/bin/calaos_server/<Mutated>.o tests/core/<Your>_test
 *        make -C src/bin/calaos_server <Mutated>.o
 *        make -C tests core/<Your>_test        # must print CXXLD, check it
 *    A mutation proof without both deletions and the CXXLD line in the log is
 *    not a proof, and review rejects it. The same trap will produce a false
 *    green during E4.1 itself, which is the catastrophe this series exists to
 *    prevent.
 *
 * ---------------------------------------------------------------------------
 * KNOWN DIVERGENCES - FREEZE THEM, DO NOT FIX THEM
 * ---------------------------------------------------------------------------
 *   - audio_db expects "get_albums" over HTTP and "get_album" over WS.
 *   - autoscenario with an unknown "type" USED TO answer nothing at all, on
 *     both transports, HTTP not even closing the socket. E4.6e (D8) gave both
 *     dispatchers an else; the divergence is gone and the cases that pinned it
 *     are flipped. Silence is still observable behaviour elsewhere in this
 *     harness: assert the message count is zero.
 *   - buildQuery() tests jParam.Exists("id") but reads jParam["input_id"]
 *     (JsonApi.cpp:641-661).
 *   - the "unkown audio_action" error string is misspelled in production.
 * A sub-ticket that finds another one writes it in FINDINGS.md and pins it as
 * it is. Touching src/ during characterization destroys the reference.
 *
 * ---------------------------------------------------------------------------
 * OUT OF SCOPE
 * ---------------------------------------------------------------------------
 * get_camera_pic and get_cover spawn calaos_picture through
 * uvw::ProcessHandle: excluded from characterization (their JSON error paths
 * are not).
 *
 * ---------------------------------------------------------------------------
 * TYPICAL USE
 * ---------------------------------------------------------------------------
 *      class MyTest: public CalaosTest::JsonApiCharacterizationTest {};
 *
 *      TEST_F(MyTest, GetHome)
 *      {
 *          loadReferenceHouse();
 *
 *          WsTestSession ws;                    // already authenticated
 *          ws.send(Json{{ "msg", "get_home" }, { "msg_id", "1" }});
 *
 *          ASSERT_EQ(1u, ws.count());
 *          EXPECT_JSON_GOLDEN("ws_get_home", ws.lastMessage());
 *      }
 *
 *      TEST_F(MyTest, GetHomeHttp)
 *      {
 *          loadReferenceHouse();
 *
 *          HttpTestRequest req;                 // fresh client, one shot
 *          req.send(authenticated(Json{{ "action", "get_home" }}));
 *
 *          EXPECT_EQ("HTTP/1.0 200 OK", req.statusLine());
 *          EXPECT_JSON_GOLDEN("http_get_home", req.body());
 *      }
 *
 * Everything is a singleton in the server, so these tests must not be run in
 * parallel inside a single process (same caveat as CalaosCoreFixture).
 ******************************************************************************/

#include "CalaosCoreFixture.h"

#include "JsonApiHandlerWS.h"
#include "JsonApiHandlerHttp.h"
#include "HttpClient.h"
#include "Params.h"

#include <memory>
#include <string>
#include <vector>

namespace CalaosTest
{

/*******************************************************************************
 * The oracle
 ******************************************************************************/

//Parse helper. Throws nothing: on a parse error the returned json is discarded
//by the assertion, which reports the error itself.
bool parseJsonText(const std::string &text, Json &out, std::string &error);

//Returns "" when the two documents are semantically equal, otherwise a human
//readable description of the FIRST diverging node, prefixed by its JSON
//pointer path (e.g. "/home/2/items/5/state: expected ... actual ...").
std::string firstJsonDifference(const Json &expected, const Json &actual);

//Normalisation overloads, so the assertions below accept either a raw JSON
//text (the common case: a captured payload or a golden file) or an already
//built Json. Note that these are deliberately NOT implicit conversions: a
//std::string implicitly converted to Json would silently become a JSON
//*string* and turn the assertion into the string comparison this harness
//forbids.
inline const Json &asJsonDocument(const Json &j) { return j; }
Json asJsonDocument(const std::string &text);
inline Json asJsonDocument(const char *text) { return asJsonDocument(std::string(text)); }

template<typename Expected, typename Actual>
::testing::AssertionResult jsonSemanticEqual(const char *expectedExpr,
                                            const char *actualExpr,
                                            const Expected &expected,
                                            const Actual &actual)
{
    const Json jexpected = asJsonDocument(expected);
    const Json jactual = asJsonDocument(actual);

    //asJsonDocument() answers a discarded value on a parse error
    if (jexpected.is_discarded())
        return ::testing::AssertionFailure()
                << expectedExpr << " is not parsable JSON";
    if (jactual.is_discarded())
        return ::testing::AssertionFailure()
                << actualExpr << " is not parsable JSON";

    const std::string diff = firstJsonDifference(jexpected, jactual);
    if (diff.empty())
        return ::testing::AssertionSuccess();

    return ::testing::AssertionFailure()
            << "JSON documents differ (semantic comparison, key order ignored,\n"
            << "array order significant, types strict).\n"
            << "  expected: " << expectedExpr << "\n"
            << "  actual  : " << actualExpr << "\n"
            << "  " << diff << "\n"
            << "--- expected ---\n" << jexpected.dump(2) << "\n"
            << "--- actual ---\n" << jactual.dump(2);
}

//Compares against tests/core/golden/<name>.json. With CALAOS_GOLDEN_UPDATE=1
//in the environment the golden is (re)written from the actual value instead of
//being compared, so goldens are always generated by the code.
::testing::AssertionResult jsonMatchesGolden(const char *nameExpr,
                                             const char *actualExpr,
                                             const std::string &goldenName,
                                             const std::string &actualJsonText);
::testing::AssertionResult jsonMatchesGolden(const char *nameExpr,
                                             const char *actualExpr,
                                             const std::string &goldenName,
                                             const Json &actual);

//Absolute-ish path of a golden file, exposed for diagnostics only.
std::string goldenFilePath(const std::string &goldenName);

//True when CALAOS_GOLDEN_UPDATE is set. A case that deliberately feeds a WRONG
//payload to EXPECT_JSON_GOLDEN (the negative tests of the assertions) must
//GTEST_SKIP() on this: in update mode the macro WRITES instead of comparing, so
//it would happily overwrite a real golden with the wrong payload.
bool goldenUpdateModeEnabled();

/*******************************************************************************
 * Total accessors - USE THESE, NEVER operator[] ON A CAPTURED PAYLOAD
 *
 * RULE OF THE SERIES, promoted from E4.0d after being measured there.
 * nlohmann's CONST operator[] does not answer null on a missing key: it fires
 * an assert() and ABORTS THE WHOLE BINARY. A renamed key therefore kills the
 * run at the first case that reads it, and every later case is simply never
 * executed - so the report says "5 failures" when the truth is 33, and says
 * nothing at all about WHICH keys moved.
 *
 * That is exactly the shape of the E4.1 migration: keys move, and the value of
 * this whole series is a readable list of which ones. Measured on E4.0d's own
 * counter mutation: reading through operator[] aborted at the 5th case;
 * reading through these two reported 33 and 21 clean failures with the paths.
 *
 *      member(env, "data")             -> the member, or a null Json
 *      member(member(env,"data"), "x") -> nests safely, null all the way down
 *      str(ev, "type_str")             -> the string, or "" if absent/not a string
 *
 * Neither ever throws, asserts or aborts. `str()` on a non-string member
 * answers "" rather than the JSON text of it, on purpose: a case that needs to
 * know the type must ask member(...).is_string() and say so.
 ******************************************************************************/
inline Json member(const Json &j, const char *key)
{
    if (!j.is_object())
        return Json();
    const auto it = j.find(key);
    return it == j.end()? Json(): *it;
}

inline std::string str(const Json &j, const char *key)
{
    const Json m = member(j, key);
    return m.is_string()? m.get<std::string>(): std::string();
}

/*******************************************************************************
 * Websocket session
 *
 * Drives JsonApiHandlerWS::processApi() in process, with no socket and no
 * running loop, and captures everything the handler pushes out through the
 * sendData signal. Constructed authenticated by default: login itself is a
 * case of its own (E4.0e), every other case would otherwise have to replay it.
 *
 * A session is also an event sink: JsonApiHandlerWS connects to
 * EventManager::newEvent in its constructor, so events raised while a session
 * is alive land in messages() - AFTER pumpEventLoop() (see point (c) above).
 ******************************************************************************/
class WsTestSession
{
public:
    explicit WsTestSession(bool authenticated = true, bool serviceScope = false);
    ~WsTestSession();

    WsTestSession(const WsTestSession &) = delete;
    WsTestSession &operator=(const WsTestSession &) = delete;

    //Feed one client message to the handler.
    void send(const std::string &jsonText);
    void send(const Json &request);

    //Everything sendData emitted, in order, as raw text.
    const std::vector<std::string> &messages() const { return sentMessages; }
    size_t count() const { return sentMessages.size(); }
    //Last message as raw text ("" when nothing was sent). Feed it to
    //EXPECT_JSON_EQ / EXPECT_JSON_GOLDEN, never to EXPECT_EQ.
    std::string lastMessage() const;
    //Last message parsed: the whole envelope {msg, msg_id, data}.
    Json lastEnvelope() const;
    //data member of the last envelope (null when absent).
    Json lastData() const;

    //closeConnection emissions, as (code, reason).
    const std::vector<std::pair<int, std::string>> &closes() const { return closeEvents; }

    void clear();

    void setAuthenticated(bool auth);
    void setServiceScope(bool scope);

private:
    class Handler;
    std::unique_ptr<Handler> handler;
    std::vector<std::string> sentMessages;
    std::vector<std::pair<int, std::string>> closeEvents;
};

/*******************************************************************************
 * HTTP request
 *
 * Drives JsonApiHandlerHttp::processApi() over a real HttpClient built on an
 * unconnected uvw::TcpHandle, and captures the raw HTTP response emitted
 * through sendData.
 *
 * ONE OBJECT PER REQUEST, ENFORCED. buildHttpResponse() accumulates into
 * resHeaders and flips conn_close on the client, so replaying a second request
 * on the same client would characterize the leftovers of the first one.
 * send() aborts the test if called twice.
 ******************************************************************************/
class HttpTestRequest
{
public:
    HttpTestRequest();
    ~HttpTestRequest();

    HttpTestRequest(const HttpTestRequest &) = delete;
    HttpTestRequest &operator=(const HttpTestRequest &) = delete;

    //body is the raw request body. Pass a non-JSON body to exercise the GET
    //parameter fallback and the 400 path (JsonApiHandlerHttp.cpp:81-90).
    void send(const std::string &body, const Params &paramsGET = Params());
    void send(const Json &body, const Params &paramsGET = Params());

    //Raw response(s) as emitted. Normally exactly one.
    const std::vector<std::string> &rawResponses() const { return responses; }
    size_t count() const { return responses.size(); }

    //Parsed view of the (single) response.
    std::string statusLine() const;                     //"HTTP/1.0 200 OK"
    std::string header(const std::string &key) const;   //case insensitive, "" if absent
    bool hasHeader(const std::string &key) const;
    std::string body() const;                           //raw body text
    Json bodyJson() const;                              //parsed body

    const std::vector<std::pair<int, std::string>> &closes() const { return closeEvents; }

private:
    class Client;
    std::shared_ptr<Client> client;
    std::unique_ptr<JsonApiHandlerHttp> handler;
    std::vector<std::string> responses;
    std::vector<std::pair<int, std::string>> closeEvents;
    bool alreadySent = false;
};

/*******************************************************************************
 * Loop pumping
 *
 * Runs the default uvw loop in NOWAIT mode a few times. Needed after
 * EventManager::create() for the queued events to reach the WS sessions; a
 * no-op otherwise. Kept out of the sessions on purpose: a test that pins the
 * ABSENCE of a message (the !loggedin gating, the camera silences) must
 * be able to pump and still observe nothing.
 ******************************************************************************/
void pumpEventLoop(int iterations = 4);

/*******************************************************************************
 * Fixture
 *
 * CoreFixture (isolated config dir, clean singletons) plus:
 *   - API credentials set to apiUser()/apiPassword(),
 *   - LoginThrottle reset between cases (a failed-login case would otherwise
 *     block the next ones, they all share the client ip "unknown"),
 *   - a deterministic reference house.
 ******************************************************************************/
class JsonApiCharacterizationTest: public CoreFixture
{
protected:
    void SetUp() override;

    /* THIS TEARDOWN LEAVES THE EVENT QUEUE EMPTY. FIXED IN E4.0g, AND THE
     * ORDER OF ITS TWO STATEMENTS IS THE FIX - DO NOT SWAP THEM BACK.
     *
     * It calls CoreFixture::TearDown() FIRST and pumps the loop AFTER. The
     * parent call is what destroys the rooms, and ~Room() raises one
     * EventIODeleted per IO it still owns (Room.cpp:77, eight of them for the
     * reference house). Those events are produced BY the parent teardown, so a
     * pump placed before it drains everything except exactly them: they used
     * to survive into the NEXT case and be delivered to its first session -
     * even to a session created after the fact, since newEvent is emitted at
     * FLUSH time, not at QUEUE time.
     *
     * Consequence, now gone: a case pinning the ABSENCE of a message passed
     * alone and failed in a full run, under some orderings only - and, on some
     * seeds, crashed outright rather than failing cleanly (uv assertion in
     * uv__finish_close, or std::bad_alloc, MEASURED in the E4.0g review).
     *
     * FIVE workarounds had accumulated against it, in four different shapes,
     * and E4.0g removed all five in the same diff (plus a sixth drain in
     * loadReferenceHouse(), see there) - which is how the fix was proven.
     *
     * Do NOT read that as "every sub-ticket needed one". MEASURED per
     * workaround, by restoring the old pump order and shuffling seeds, only
     * THREE were load-bearing:
     *   - JsonApiEvents_test, last statement of SetUp()      - red 3/3 seeds
     *   - JsonApiSession_test, mid-SetUp()                   - red 2/3 seeds
     *   - JsonApiWsTransport_test, end of SetUp()            - red 14/15 seeds
     * and TWO never absorbed anything at all, 0 red in 18 seeds each with the
     * defect present:
     *   - JsonApiAudioPayload_test, end of SetUp()
     *   - JsonApiHome_test, head of one case body, not in SetUp() at all
     *
     * Those last two were copied from a neighbour, and from an explanation
     * that was itself false (see the EventIOAdded correction below). Copying a
     * pump you have not measured is how this file ended up documenting the
     * wrong cause for six sub-tickets.
     *
     * YOU THEREFORE INHERIT AN EMPTY QUEUE. Do not add a defensive pump to
     * your SetUp(): if you ever need one, you have found a SECOND source of
     * events surviving TearDown() - name it and write it in FINDINGS.md
     * instead of papering over it. The control that catches a regression here
     * is --gtest_shuffle on a few seeds, never the default order.
     */
    void TearDown() override;

    //Credentials the API is configured with. Use authenticated() to stamp them
    //on an HTTP request body; the WS session is authenticated directly.
    static const char *apiUser();
    static const char *apiPassword();

    //Adds cn_user/cn_pass to an HTTP request body.
    static Json authenticated(Json body);

    /***************************************************************************
     * The reference house. Three rooms, eight IOs, deliberately including:
     *   - the three variable types (bool, int, string) so var_type and the
     *     stringification of state are exercised,
     *   - a non zero "hits" on the first room,
     *   - an IO whose name carries accented UTF-8. It leaves as \uXXXX escapes
     *     on BOTH sides - jansson wrote an UPPERCASE hexadecimal under
     *     JSON_ENSURE_ASCII, the tree writes a lowercase one since E4.1b and
     *     E4.1s (ensure_ascii = true, invariant 3 of the epic) - and both
     *     parse to the same string, which is precisely what the semantic
     *     oracle has to prove.
     *     ⚠️ THIS PARAGRAPH USED TO SAY "nlohmann writes raw UTF-8". That is
     *     FORM 2, the bare dump(), and it is exactly the form the epic refused
     *     to ship; see the tripwires of tests/ParamsJson_test.cpp and
     *     core/JsonApiDispatchWireBytes_test.cpp,
     *   - that SAME IO (HOUSE_ACCENTED) is also the only one setting every
     *     OPTIONAL param of buildJsonIO() - hits, chauffage_id, unit,
     *     auto_scenario, step, io_style, value_warning - so all sixteen
     *     candidate keys appear at least once in the goldens. ADDED IN E4.0b
     *     AFTER A REVIEW COUNTER-MUTATION: renaming four of those keys in
     *     JsonApi.cpp used to leave the ENTIRE suite green, because they were
     *     missing from every payload for want of an IO setting them, not
     *     because the code skipped them. Every OTHER IO of the house stays
     *     sparse ON PURPOSE - the contrast inside one golden is what pins the
     *     "absent param -> absent key, never null" contract
     *     (JsonApi.cpp:285-286). Do not spread these params around: you would
     *     destroy the contrast and the absence side would stop being covered.
     *     The seventeenth key, status_info, cannot come from configuration at
     *     all (IOBase::setStatusInfo() is called by drivers); it is covered by
     *     a runtime case in JsonApiHome_test.cpp,
     *   - TWO REAL CAMERAS and ONE REAL AUDIO PLAYER, so buildJsonCameras() and
     *     buildJsonAudio() are characterized on non-empty arrays. The two
     *     cameras cover both branches of the ptz capability, and the player
     *     carries an "amp" param so the OPTIONAL "avr" key is emitted.
     *     Concrete classes chosen by measurement (see the note on the
     *     dynamic_cast filter below).
     * Rooms and IOs are emitted in declaration order, and that order is
     * asserted (arrays are ordered).
     *
     * ON THE dynamic_cast FILTER OF buildJsonCameras()/buildJsonAudio(), and a
     * CORRECTION TO E4.0.md:90-93: the plan asks the goldens to also contain
     * "an IO that does NOT pass the dynamic_cast". MEASURED: that IO cannot be
     * built from any configuration. ListeRoom::addIOHash() (ListeRoom.cpp:80-85)
     * populates cameraCache/audioCache purely on get_param("gui_type") ==
     * "camera" / "audio_player", and the ONLY code that ever sets those two
     * values is IPCam's constructor (IPCam.cpp) and AudioPlayer's constructor
     * (AudioPlayer.cpp) - both of which then call addIOHash() themselves. Every
     * other IO class overwrites gui_type with its own value (e.g.
     * IO/IntValue.cpp:83-85 forces var_bool/var_int/var_string), so an XML
     * attribute cannot smuggle a foreign IO into either cache. The dynamic_cast
     * is therefore UNREACHABLE DEFENSIVE CODE, not a filter with two outcomes.
     * Do not spend a sub-ticket trying to cover its false branch: it has no
     * false branch reachable from configuration.
     *
     * It also carries one simple rule (HOUSE_RULE_NAME) so the rule side is
     * not empty. It does NOT pump the loop: see the note on the removed drain
     * below.
     *
     * CORRECTED IN E4.0d, THIS PARAGRAPH USED TO BE WRONG. It claimed the load
     * raises one EventIOAdded per IO ("five queued events"). MEASURED: the
     * load raises NOTHING, and the house holds EIGHT IOs, not five.
     * EventIOAdded has a single call site, ListeRoom::createIO()
     * (ListeRoom.cpp:466), which is the runtime path of the JSON API; config
     * loading goes through Room::LoadFromXml() (Room.cpp:152-175), which
     * builds and attaches the IOs without raising anything.
     *
     * THE DRAIN THIS FUNCTION USED TO END WITH IS GONE, REMOVED BY E4.0g. What
     * it really absorbed was the PREVIOUS case's backlog: the EventIODeleted
     * that ~Room() raises while CoreFixture::TearDown() destroys the rooms.
     * That backlog no longer exists - the fixture now pumps AFTER the parent
     * teardown (see TearDown() below), so a case starts on an empty queue and
     * the drain was dead code. MEASURED as removable, twice and independently:
     * fifteen --gtest_shuffle seeds green on every binary of this harness
     * without it, and no caller raises an event before asking for the house.
     * It was removed rather than kept as a guard, because TearDown() tells
     * sub-tickets not to keep a defensive pump nothing exercises and the
     * harness does not get to exempt itself from its own rule.
     *
     * Ids are prefixed e40_ and used nowhere else: Config's IO state cache is
     * process wide and never cleared (see CalaosCoreFixture.h), so sharing ids
     * with another test file would leak state across binaries' cases.
     **************************************************************************/
    void loadReferenceHouse();

    static const char *const HOUSE_ROOM1_NAME;
    static const char *const HOUSE_ROOM2_NAME;
    static const char *const HOUSE_BOOL_IN;
    static const char *const HOUSE_BOOL_OUT;
    static const char *const HOUSE_INT;
    static const char *const HOUSE_STRING;
    static const char *const HOUSE_ACCENTED;
    static const char *const HOUSE_ROOM3_NAME;
    static const char *const HOUSE_CAMERA_PTZ;
    static const char *const HOUSE_CAMERA_PLAIN;
    static const char *const HOUSE_PLAYER;
    static const char *const HOUSE_RULE_NAME;
};

} //namespace CalaosTest

/*******************************************************************************
 * Assertions. These are the ONLY sanctioned way to compare JSON in the E4.0
 * series.
 ******************************************************************************/
#define EXPECT_JSON_EQ(expected, actual) \
    EXPECT_PRED_FORMAT2(::CalaosTest::jsonSemanticEqual, expected, actual)
#define ASSERT_JSON_EQ(expected, actual) \
    ASSERT_PRED_FORMAT2(::CalaosTest::jsonSemanticEqual, expected, actual)

#define EXPECT_JSON_GOLDEN(name, actual) \
    EXPECT_PRED_FORMAT2(::CalaosTest::jsonMatchesGolden, std::string(name), actual)
#define ASSERT_JSON_GOLDEN(name, actual) \
    ASSERT_PRED_FORMAT2(::CalaosTest::jsonMatchesGolden, std::string(name), actual)

#endif
