/******************************************************************************
 **  Copyright (c) 2006-2025, Calaos. All Rights Reserved.
 **
 **  This file is part of Calaos.
 **
 **  Calaos is free software; you can redistribute it and/or modify
 **  it under the terms of the GNU General Public License as published by
 **  the Free Software Foundation; either version 3 of the License, or
 **  (at your option) any later version.
 **
 **  Calaos is distributed in the hope that it will be useful,
 **  but WITHOUT ANY WARRANTY; without even the implied warranty of
 **  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 **  GNU General Public License for more details.
 **
 **  You should have received a copy of the GNU General Public License
 **  along with Foobar; if not, write to the Free Software
 **  Foundation, Inc., 51 Franklin St, Fifth Floor, Boston, MA  02110-1301  USA
 **
 ******************************************************************************/
/*******************************************************************************
 * E4.0b - the model and the state: the nine commands every client of the JSON
 * API calls, on BOTH transports.
 *
 *      get_home  get_io  get_state  get_states  query
 *      get_param  set_param  del_param  set_state
 *
 * This file freezes what the code does TODAY. It fixes nothing and improves
 * nothing: several cases below pin behaviour that is unambiguously wrong (see
 * "FROZEN BUGS" further down). Correcting a behaviour while characterizing it
 * destroys the reference the E4.1 migration will be judged against.
 *
 * Everything goes through the E4.0a harness (tests/core/JsonApiCharacterization.h,
 * read it before touching anything here): semantic oracle, one golden per case,
 * goldens GENERATED by CALAOS_GOLDEN_UPDATE=1 and never hand written.
 *
 * ---------------------------------------------------------------------------
 * WHAT THE TWO TRANSPORTS DO NOT AGREE ON - characterized here, not fixed
 * ---------------------------------------------------------------------------
 *  - get_io / get_state read their "items" array from DIFFERENT PLACES:
 *    WS reads jsonRoot["data"]["items"] (JsonApiHandlerWS.cpp:255, :314), HTTP
 *    reads the ROOT object's "items" (JsonApiHandlerHttp.cpp:285, :349). The
 *    exact same document sent to both transports does not address the same IOs.
 *  - HTTP additionally accepts "items" as a COMMA SEPARATED STRING through the
 *    GET parameter fallback (JsonApiHandlerHttp.cpp:300-303, :364-367). WS has
 *    no equivalent.
 *  - set_state over WS answers NOTHING when the request carries no msg_id
 *    (JsonApiHandlerWS.cpp:334) while HTTP always answers. A fire-and-forget
 *    set_state is silent by design over WS; over HTTP it is not.
 *  - set_param / del_param are refused for a service-scoped session over WS
 *    (scope denied); the HTTP transport has no scope notion at all.
 *
 * ---------------------------------------------------------------------------
 * FROZEN BUGS - pinned on purpose, DO NOT FIX HERE
 * ---------------------------------------------------------------------------
 *  - buildQuery() (JsonApi.cpp:641-661) gates on jParam.Exists("id") but looks
 *    the IO up with jParam["input_id"]. A well formed {"id": <valid io>} query
 *    therefore answers {"error":"wrong id"}, and a query carrying only
 *    "input_id" answers {} without ever looking anything up. Both pinned.
 *  - get_param on a KNOWN io and an UNKNOWN param is not an error: it answers
 *    {"<param>":""}, an empty string (JsonApi.cpp:672, get_param() on a missing
 *    key returns ""). "wrong io/param" is reserved for an unknown IO.
 *  - get_param with no "param" member at all answers {"":""} - a JSON object
 *    with an EMPTY KEY. Same root cause.
 *  - get_states/query are effectively dead for every IO of the tree except
 *    IOAVReceiver: get_all_values_*() and query_param() are only overridden
 *    there (IOBase.h:103-111), so every other IO answers {}. Measured, and
 *    reported as a finding, not fixed.
 ******************************************************************************/

#include "JsonApiCharacterization.h"

#include "EventManager.h"

using namespace Calaos;
using namespace CalaosTest;

class JsonApiHomeTest: public JsonApiCharacterizationTest
{
protected:
    //The four IOs of the first room plus the accented one of the second: every
    //IO of the reference house that is neither a camera nor a player, i.e.
    //everything get_state can answer synchronously.
    static Json plainItems()
    {
        return Json::array({ HOUSE_BOOL_IN, HOUSE_BOOL_OUT, HOUSE_INT,
                             HOUSE_STRING, HOUSE_ACCENTED });
    }

    //Same list plus the two cameras. Deliberately excludes the player: a player
    //makes buildJsonState() asynchronous, which is characterized on its own
    //below.
    static Json plainAndCameraItems()
    {
        Json j = plainItems();
        j.push_back(HOUSE_CAMERA_PTZ);
        j.push_back(HOUSE_CAMERA_PLAIN);
        return j;
    }

    //Walks a whole document and fails on the first JSON null it finds. The
    //"absent key, never null" contract of buildJsonIO() (JsonApi.cpp:286
    //`continue`) is the single most fragile thing of the migration: a
    //`j[key] = nullptr` written by reflex would create the key instead of
    //skipping it, and every golden here would still pass on the keys it does
    //list.
    static ::testing::AssertionResult hasNoNullAnywhere(const Json &j,
                                                        const std::string &path = "")
    {
        if (j.is_null())
            return ::testing::AssertionFailure() << "null at " << (path.empty()? "/": path);

        if (j.is_object())
        {
            for (auto it = j.begin(); it != j.end(); ++it)
            {
                auto res = hasNoNullAnywhere(it.value(), path + "/" + it.key());
                if (!res) return res;
            }
        }
        else if (j.is_array())
        {
            for (size_t i = 0; i < j.size(); i++)
            {
                auto res = hasNoNullAnywhere(j[i], path + "/" + std::to_string(i));
                if (!res) return res;
            }
        }

        return ::testing::AssertionSuccess();
    }

    //Every leaf of the document must be a JSON string. The whole API is
    //stringified today (JsonApi.cpp holds 32 json_string and zero json_integer
    /// json_real / json_true); buildJsonEventLog() is the single exception and
    //it belongs to E4.0e, not here.
    static ::testing::AssertionResult everyLeafIsAString(const Json &j,
                                                          const std::string &path = "")
    {
        if (j.is_object())
        {
            for (auto it = j.begin(); it != j.end(); ++it)
            {
                auto res = everyLeafIsAString(it.value(), path + "/" + it.key());
                if (!res) return res;
            }
            return ::testing::AssertionSuccess();
        }

        if (j.is_array())
        {
            for (size_t i = 0; i < j.size(); i++)
            {
                auto res = everyLeafIsAString(j[i], path + "/" + std::to_string(i));
                if (!res) return res;
            }
            return ::testing::AssertionSuccess();
        }

        if (j.is_string())
            return ::testing::AssertionSuccess();

        return ::testing::AssertionFailure()
                << "non string leaf at " << path << ": " << j.dump();
    }
};

/*******************************************************************************
 * get_home
 *
 * The biggest payload of the API and the one every client fetches first:
 * rooms in declaration order, each with its IOs in declaration order, plus the
 * two flat arrays cameras/audio built by dynamic_cast over ListeRoom's caches.
 ******************************************************************************/

/* NO get_home GOLDEN IN THIS FILE, ON PURPOSE. E4.0a already versions
 * ws_get_home.json and http_get_home.json, generated from the same reference
 * house by the same builders: a golden here would be BYTE IDENTICAL to its,
 * adding zero coverage and doubling the number of files E4.1 has to regenerate.
 * The cases below characterize get_home on the axes E4.0a does NOT cover -
 * cross transport equality, the no-null/all-strings contract, the shape of a
 * room object, the empty house, and the full key set of an IO.
 */

TEST_F(JsonApiHomeTest, GetHomeIsIdenticalOnBothTransports)
{
    //The HTTP body is the same object the WS envelope carries under "data".
    //Pinning the equality is what allows every other case here to characterize
    //a payload once instead of twice.
    loadReferenceHouse();

    WsTestSession ws;
    ws.send(Json{{ "msg", "get_home" }, { "msg_id", "1" }});
    ASSERT_EQ(1u, ws.count());
    const Json wsData = ws.lastData();

    HttpTestRequest req;
    req.send(authenticated(Json{{ "action", "get_home" }}));
    ASSERT_EQ(1u, req.count());

    EXPECT_JSON_EQ(wsData, req.bodyJson());
}

TEST_F(JsonApiHomeTest, GetHomeEmitsNoNullAndOnlyStrings)
{
    //Two contracts of the whole series in one case: an absent param is NOT
    //emitted (never as null), and every scalar on the wire is a string.
    loadReferenceHouse();

    WsTestSession ws;
    ws.send(Json{{ "msg", "get_home" }, { "msg_id", "1" }});

    ASSERT_EQ(1u, ws.count());
    const Json data = ws.lastData();

    EXPECT_TRUE(hasNoNullAnywhere(data));
    EXPECT_TRUE(everyLeafIsAString(data));
}

TEST_F(JsonApiHomeTest, GetHomeRoomShapeAndHits)
{
    //A room object is exactly {type, name, hits, items}. hits is stringified,
    //and the reference house sets it to 3 on the first room precisely so the
    //non-zero case is covered.
    loadReferenceHouse();

    WsTestSession ws;
    ws.send(Json{{ "msg", "get_home" }, { "msg_id", "1" }});

    ASSERT_EQ(1u, ws.count());
    const Json home = ws.lastData()["home"];
    ASSERT_TRUE(home.is_array());
    ASSERT_EQ(3u, home.size());

    for (const Json &room: home)
    {
        ASSERT_TRUE(room.is_object());
        EXPECT_EQ(4u, room.size()) << room.dump();
        EXPECT_TRUE(room.contains("type"));
        EXPECT_TRUE(room.contains("name"));
        EXPECT_TRUE(room.contains("hits"));
        EXPECT_TRUE(room["items"].is_array());
    }

    EXPECT_EQ("salon", home[0].value("type", std::string()));
    EXPECT_EQ("3", home[0].value("hits", std::string()));
    EXPECT_EQ("0", home[1].value("hits", std::string()));
}

TEST_F(JsonApiHomeTest, GetHomeOnAnEmptyHouseAnswersThreeEmptyArrays)
{
    //No rooms at all: the three members are still present, as empty arrays.
    //An absent member would break every client that indexes them blindly.
    //Loading an empty document raises nothing, and since E4.0g the previous
    //case leaves nothing either (the fixture pumps after
    //CoreFixture::TearDown()), so no drain is needed before counting messages.
    loadConfig(ioXmlDocument(std::string()), rulesXmlDocument(std::string()));

    WsTestSession ws;
    ws.send(Json{{ "msg", "get_home" }, { "msg_id", "1" }});

    ASSERT_EQ(1u, ws.count());
    EXPECT_JSON_EQ(std::string(R"({"msg":"get_home","msg_id":"1",)"
                               R"("data":{"home":[],"cameras":[],"audio":[]}})"),
                   ws.lastMessage());
}

/*******************************************************************************
 * get_io
 *
 * Same per-IO object as get_home, but keyed by id in a flat map instead of
 * nested in rooms.
 ******************************************************************************/

TEST_F(JsonApiHomeTest, WsGetIoOnEveryNonPlayerIo)
{
    loadReferenceHouse();

    WsTestSession ws;
    ws.send(Json{{ "msg", "get_io" },
                 { "msg_id", "e40b-2" },
                 { "data", {{ "items", plainAndCameraItems() }} }});

    ASSERT_EQ(1u, ws.count());
    EXPECT_JSON_GOLDEN("e40b_ws_get_io", ws.lastMessage());
}

TEST_F(JsonApiHomeTest, HttpGetIoReadsItemsFromTheRootObject)
{
    //DIVERGENCE, frozen: HTTP looks for "items" in the ROOT object
    //(JsonApiHandlerHttp.cpp:349) where WS looks for it under "data".
    loadReferenceHouse();

    HttpTestRequest req;
    req.send(authenticated(Json{{ "action", "get_io" },
                                { "items", plainAndCameraItems() }}));

    ASSERT_EQ(1u, req.count());
    EXPECT_JSON_GOLDEN("e40b_http_get_io", req.body());
}

TEST_F(JsonApiHomeTest, GetIoPayloadIsIdenticalOnBothTransports)
{
    loadReferenceHouse();

    WsTestSession ws;
    ws.send(Json{{ "msg", "get_io" },
                 { "msg_id", "1" },
                 { "data", {{ "items", plainAndCameraItems() }} }});
    ASSERT_EQ(1u, ws.count());
    const Json wsData = ws.lastData();

    HttpTestRequest req;
    req.send(authenticated(Json{{ "action", "get_io" },
                                { "items", plainAndCameraItems() }}));
    ASSERT_EQ(1u, req.count());

    EXPECT_JSON_EQ(wsData, req.bodyJson());
}

TEST_F(JsonApiHomeTest, HttpGetIoIgnoresItemsPlacedUnderData)
{
    //The mirror of the divergence above: the WS shaped request, sent to HTTP,
    //addresses nothing at all and answers an empty object rather than an error.
    loadReferenceHouse();

    HttpTestRequest req;
    req.send(authenticated(Json{{ "action", "get_io" },
                                { "data", {{ "items", plainItems() }} }}));

    ASSERT_EQ(1u, req.count());
    EXPECT_JSON_EQ(std::string("{}"), req.body());
}

TEST_F(JsonApiHomeTest, WsGetIoIgnoresItemsPlacedAtTheRoot)
{
    loadReferenceHouse();

    WsTestSession ws;
    ws.send(Json{{ "msg", "get_io" },
                 { "msg_id", "1" },
                 { "items", plainItems() }});

    ASSERT_EQ(1u, ws.count());
    //no "data" member at all: json_object_get(jroot, "data") is null, so
    //processGetIO() answers the envelope alone (JsonApiHandlerWS.cpp:307-311)
    EXPECT_JSON_EQ(std::string(R"({"msg":"get_io","msg_id":"1"})"),
                   ws.lastMessage());
}

TEST_F(JsonApiHomeTest, WsGetIoWithAnEmptyDataObjectAnswersAnEmptyMap)
{
    //"data" present but without "items": the envelope carries data:{}, which is
    //NOT the same document as the case above (no data member at all).
    loadReferenceHouse();

    WsTestSession ws;
    ws.send(Json{{ "msg", "get_io" }, { "msg_id", "1" }, { "data", Json::object() }});

    ASSERT_EQ(1u, ws.count());
    EXPECT_JSON_EQ(std::string(R"({"msg":"get_io","msg_id":"1","data":{}})"),
                   ws.lastMessage());
}

TEST_F(JsonApiHomeTest, GetIoSilentlyDropsUnknownIdsAndNonStringEntries)
{
    //buildJsonGetIO() skips an id it cannot resolve (JsonApi.cpp:747) and
    //processGetIO() skips an array entry that is not a string
    //(JsonApiHandlerWS.cpp:322). No error, no null placeholder: the key is
    //simply absent from the answer.
    loadReferenceHouse();

    WsTestSession ws;
    ws.send(Json{{ "msg", "get_io" },
                 { "msg_id", "1" },
                 { "data", {{ "items", Json::array({ HOUSE_BOOL_IN,
                                                     "e40b_no_such_io",
                                                     42,
                                                     Json::object(),
                                                     HOUSE_INT }) }} }});

    ASSERT_EQ(1u, ws.count());
    const Json data = ws.lastData();
    ASSERT_TRUE(data.is_object());
    EXPECT_EQ(2u, data.size()) << data.dump();
    EXPECT_TRUE(data.contains(HOUSE_BOOL_IN));
    EXPECT_TRUE(data.contains(HOUSE_INT));
    EXPECT_FALSE(data.contains("e40b_no_such_io"));
}

TEST_F(JsonApiHomeTest, GetIoRepeatsTheSameIdOnlyOnce)
{
    //The answer is a json OBJECT keyed by id, so a duplicated id collapses.
    loadReferenceHouse();

    WsTestSession ws;
    ws.send(Json{{ "msg", "get_io" },
                 { "msg_id", "1" },
                 { "data", {{ "items", Json::array({ HOUSE_BOOL_IN,
                                                     HOUSE_BOOL_IN }) }} }});

    ASSERT_EQ(1u, ws.count());
    EXPECT_EQ(1u, ws.lastData().size());
}

TEST_F(JsonApiHomeTest, HttpGetIoAcceptsACommaSeparatedItemsGetParameter)
{
    //HTTP ONLY (JsonApiHandlerHttp.cpp:364-367). Reachable only when the body
    //is not JSON, which is exactly how a browser hits the API with a query
    //string.
    loadReferenceHouse();

    Params getParams;
    getParams.Add("cn_user", apiUser());
    getParams.Add("cn_pass", apiPassword());
    getParams.Add("action", "get_io");
    getParams.Add("items", std::string(HOUSE_BOOL_IN) + "," + HOUSE_INT);

    HttpTestRequest req;
    req.send(std::string("not json"), getParams);

    ASSERT_EQ(1u, req.count());
    EXPECT_EQ("HTTP/1.0 200 OK", req.statusLine());
    const Json body = req.bodyJson();
    ASSERT_TRUE(body.is_object());
    EXPECT_EQ(2u, body.size());
    EXPECT_TRUE(body.contains(HOUSE_BOOL_IN));
    EXPECT_TRUE(body.contains(HOUSE_INT));
}

TEST_F(JsonApiHomeTest, GetIoDescribesTheThreeVariableTypes)
{
    //var_type is derived from the C++ type of the IO, not from a param:
    //TINT -> "float", TBOOL -> "bool", TSTRING -> "string"
    //(JsonApi.cpp:277-282). The state of a TINT goes through
    //Utils::to_string(double), which is ostream default formatting.
    loadReferenceHouse();

    WsTestSession ws;
    ws.send(Json{{ "msg", "get_io" },
                 { "msg_id", "1" },
                 { "data", {{ "items", plainItems() }} }});

    ASSERT_EQ(1u, ws.count());
    const Json data = ws.lastData();

    EXPECT_EQ("bool", data[HOUSE_BOOL_IN].value("var_type", std::string()));
    EXPECT_EQ("false", data[HOUSE_BOOL_IN].value("state", std::string()));
    EXPECT_EQ("float", data[HOUSE_INT].value("var_type", std::string()));
    EXPECT_EQ("string", data[HOUSE_STRING].value("var_type", std::string()));
}

/*******************************************************************************
 * The sixteen candidate keys of buildJsonIO(), and the seventeenth.
 *
 * ADDED AFTER A REVIEW COUNTER-MUTATION. The first version of this file claimed
 * its goldens "exhibited the absence contract" on eight keys. Six of them -
 * hits, chauffage_id, auto_scenario, step, io_style, value_warning - were in
 * fact absent because NO IO OF THE REFERENCE HOUSE SET THEM. Renaming four of
 * them in JsonApi.cpp:259-262 left all 52 cases green: the net saw nothing.
 * They are real production params (ListeRoom.cpp:276 reads chauffage_id,
 * IO/OutputAnalog.cpp:39 documents step, IO/InputSwitch.cpp:48 io_style,
 * IO/InputAnalog.cpp:66 value_warning).
 *
 * HOUSE_ACCENTED now sets every optional one, so the sixteen keys are pinned
 * BOTH by the goldens and by the explicit list below - a rename in production
 * cannot pass any more. The three cases are complementary on purpose: the
 * presence side, the absence side, and status_info which no configuration can
 * produce.
 ******************************************************************************/

TEST_F(JsonApiHomeTest, GetIoEmitsTheSixteenKeysForAFullyConfiguredIo)
{
    loadReferenceHouse();

    WsTestSession ws;
    ws.send(Json{{ "msg", "get_io" },
                 { "msg_id", "1" },
                 { "data", {{ "items", Json::array({ HOUSE_ACCENTED }) }} }});

    ASSERT_EQ(1u, ws.count());
    const Json jio = ws.lastData()[HOUSE_ACCENTED];
    ASSERT_TRUE(jio.is_object());

    //the exact list of JsonApi.cpp:258-262, in that order, spelled out so a
    //rename in production fails HERE with the key name in the message
    const std::vector<std::string> keys =
    { "id", "name", "type", "hits", "var_type", "visible",
      "chauffage_id", "rw", "unit", "gui_type", "state",
      "auto_scenario", "step", "io_type", "io_style",
      "value_warning" };

    for (const std::string &k: keys)
        EXPECT_TRUE(jio.contains(k)) << "buildJsonIO() no longer emits " << k;

    //status_info is the only other key it can add, and this IO has none
    EXPECT_EQ(keys.size(), jio.size()) << jio.dump();

    //the seven configured through XML, with their values, all as strings
    EXPECT_EQ("12", jio.value("hits", std::string()));
    EXPECT_EQ("e40_heater", jio.value("chauffage_id", std::string()));
    EXPECT_EQ("\xc2\xb0""C", jio.value("unit", std::string()));
    EXPECT_EQ("e40_scenario", jio.value("auto_scenario", std::string()));
    EXPECT_EQ("0.5", jio.value("step", std::string()));
    EXPECT_EQ("temperature", jio.value("io_style", std::string()));
    EXPECT_EQ("false", jio.value("value_warning", std::string()));
}

TEST_F(JsonApiHomeTest, GetIoOmitsTheOptionalKeysOfASparseIo)
{
    //The other half of the contract, and the reason the rest of the house is
    //deliberately left sparse: a param the IO does not carry is NOT EMITTED AT
    //ALL (JsonApi.cpp:285-286 `continue`). Never null, never an empty string.
    //A migration writing j[k] = nullptr by reflex creates the key and fails
    //here.
    loadReferenceHouse();

    WsTestSession ws;
    ws.send(Json{{ "msg", "get_io" },
                 { "msg_id", "1" },
                 { "data", {{ "items", Json::array({ HOUSE_BOOL_IN,
                                                     HOUSE_CAMERA_PLAIN }) }} }});

    ASSERT_EQ(1u, ws.count());
    const Json data = ws.lastData();

    const Json plain = data[HOUSE_BOOL_IN];
    for (const char *k: { "hits", "chauffage_id", "unit", "auto_scenario",
                          "step", "io_style", "value_warning", "status_info" })
        EXPECT_FALSE(plain.contains(k)) << k << " unexpectedly emitted: " << plain.dump();
    EXPECT_TRUE(hasNoNullAnywhere(plain));

    //IPCam does not even set rw, which IntValue does (IntValue.cpp:81) - so
    //the two IOs of this very answer do not carry the same key set
    EXPECT_TRUE(plain.contains("rw"));
    EXPECT_FALSE(data[HOUSE_CAMERA_PLAIN].contains("rw"))
            << data[HOUSE_CAMERA_PLAIN].dump();
}

TEST_F(JsonApiHomeTest, GetIoEmitsStatusInfoAsANestedObjectWhenTheIoHasSome)
{
    //status_info is the seventeenth key and the only NESTED object of a
    //buildJsonIO() payload (JsonApi.cpp:294-296, :1997-2014). It cannot come
    //from configuration: setStatusInfo() is called by drivers at runtime, so
    //the reference house can never carry it and only a case like this one
    //covers it. hasStatusInfo() gates the whole key, and getStatusInfo() gates
    //each member individually - the same absence contract, one level down.
    loadReferenceHouse();

    IOBase *target = io(HOUSE_BOOL_IN);
    ASSERT_TRUE(target != nullptr);
    target->setStatusInfo(IOBase::StatusType::BatteryLevel, 55.0);
    target->setStatusInfo(IOBase::StatusType::WifiSSID, std::string("e40b_ssid"));

    WsTestSession ws;
    ws.send(Json{{ "msg", "get_io" },
                 { "msg_id", "1" },
                 { "data", {{ "items", Json::array({ HOUSE_BOOL_IN,
                                                     HOUSE_STRING }) }} }});

    ASSERT_EQ(1u, ws.count());
    const Json data = ws.lastData();

    ASSERT_TRUE(data[HOUSE_BOOL_IN].contains("status_info"));
    const Json status = data[HOUSE_BOOL_IN]["status_info"];
    ASSERT_TRUE(status.is_object());
    EXPECT_EQ("55", status.value("battery_level", std::string()));
    EXPECT_EQ("e40b_ssid", status.value("wifi_ssid", std::string()));
    //the members that were never set are absent, not null and not ""
    EXPECT_EQ(2u, status.size()) << status.dump();

    //and an IO without any status info still has no such key
    EXPECT_FALSE(data[HOUSE_STRING].contains("status_info"));
}

/*******************************************************************************
 * get_state
 *
 * A flat id -> value map. Same stringification rules as the "state" key of
 * buildJsonIO(), but nothing else: no name, no type, no params.
 ******************************************************************************/

TEST_F(JsonApiHomeTest, WsGetState)
{
    loadReferenceHouse();

    WsTestSession ws;
    ws.send(Json{{ "msg", "get_state" },
                 { "msg_id", "e40b-3" },
                 { "data", {{ "items", plainAndCameraItems() }} }});

    ASSERT_EQ(1u, ws.count());
    EXPECT_JSON_GOLDEN("e40b_ws_get_state", ws.lastMessage());
}

TEST_F(JsonApiHomeTest, HttpGetState)
{
    loadReferenceHouse();

    HttpTestRequest req;
    req.send(authenticated(Json{{ "action", "get_state" },
                                { "items", plainAndCameraItems() }}));

    ASSERT_EQ(1u, req.count());
    EXPECT_JSON_GOLDEN("e40b_http_get_state", req.body());
}

TEST_F(JsonApiHomeTest, GetStateDropsUnknownIdsWithoutAnError)
{
    loadReferenceHouse();

    WsTestSession ws;
    ws.send(Json{{ "msg", "get_state" },
                 { "msg_id", "1" },
                 { "data", {{ "items", Json::array({ "e40b_no_such_io",
                                                     HOUSE_STRING }) }} }});

    ASSERT_EQ(1u, ws.count());
    const Json data = ws.lastData();
    EXPECT_EQ(1u, data.size()) << data.dump();
    EXPECT_TRUE(data.contains(HOUSE_STRING));
}

TEST_F(JsonApiHomeTest, WsGetStateWithoutADataMemberAnswersTheEnvelopeAlone)
{
    loadReferenceHouse();

    WsTestSession ws;
    ws.send(Json{{ "msg", "get_state" }, { "msg_id", "1" }});

    ASSERT_EQ(1u, ws.count());
    EXPECT_JSON_EQ(std::string(R"({"msg":"get_state","msg_id":"1"})"),
                   ws.lastMessage());
}

TEST_F(JsonApiHomeTest, HttpGetStateAcceptsACommaSeparatedItemsGetParameter)
{
    loadReferenceHouse();

    Params getParams;
    getParams.Add("cn_user", apiUser());
    getParams.Add("cn_pass", apiPassword());
    getParams.Add("action", "get_state");
    getParams.Add("items", std::string(HOUSE_BOOL_IN) + "," + HOUSE_STRING);

    HttpTestRequest req;
    req.send(std::string("not json"), getParams);

    ASSERT_EQ(1u, req.count());
    const Json body = req.bodyJson();
    EXPECT_EQ(2u, body.size()) << body.dump();
    EXPECT_TRUE(body.contains(HOUSE_BOOL_IN));
}

TEST_F(JsonApiHomeTest, GetStateOfAnIntGoesThroughOstreamDoubleFormatting)
{
    //Utils::to_string(double) is an ostringstream with the default precision of
    //6 SIGNIFICANT digits (StringUtils.h:112-118). So a fractional value keeps
    //its decimals, and a large one is emitted in SCIENTIFIC notation - as a
    //string, on the wire, today. Anything that "improves" this during the
    //migration must break here.
    loadReferenceHouse();

    ASSERT_TRUE(io(HOUSE_INT) != nullptr);
    ASSERT_TRUE(io(HOUSE_INT)->set_value(42.5));

    WsTestSession ws;
    ws.send(Json{{ "msg", "get_state" },
                 { "msg_id", "1" },
                 { "data", {{ "items", Json::array({ HOUSE_INT }) }} }});

    ASSERT_EQ(1u, ws.count());
    EXPECT_EQ("42.5", ws.lastData().value(HOUSE_INT, std::string()));

    ws.clear();
    ASSERT_TRUE(io(HOUSE_INT)->set_value(1234567.89));
    ws.send(Json{{ "msg", "get_state" },
                 { "msg_id", "2" },
                 { "data", {{ "items", Json::array({ HOUSE_INT }) }} }});

    ASSERT_EQ(1u, ws.count());
    EXPECT_EQ("1.23457e+06", ws.lastData().value(HOUSE_INT, std::string()));
}

TEST_F(JsonApiHomeTest, GetStateOfAnAudioPlayerIsAsynchronous)
{
    //buildJsonState() branches on gui_type == "audio_player" and chains six
    //player queries (JsonApi.cpp:438-590). RoonPlayer answers each of them
    //through Timer::singleShot(0), so NOTHING is sent until the loop runs.
    //Pinned because a migration that made this path synchronous, or that lost
    //the chain, would be invisible to every other case in this file.
    loadReferenceHouse();

    WsTestSession ws;
    ws.send(Json{{ "msg", "get_state" },
                 { "msg_id", "1" },
                 { "data", {{ "items", Json::array({ HOUSE_BOOL_IN,
                                                     HOUSE_PLAYER }) }} }});

    EXPECT_EQ(0u, ws.count()) << "expected silence, got: " << ws.lastMessage();

    //six chained one-shot timers, one loop iteration each at least
    pumpEventLoop(24);

    ASSERT_EQ(1u, ws.count());
    const Json data = ws.lastData();
    EXPECT_EQ("false", data.value(HOUSE_BOOL_IN, std::string()));
    ASSERT_TRUE(data.contains(HOUSE_PLAYER));
    const Json player = data[HOUSE_PLAYER];
    EXPECT_TRUE(player.contains("playlist_current_track"));
    EXPECT_TRUE(player.contains("volume"));
    EXPECT_TRUE(player.contains("playlist_size"));
    EXPECT_TRUE(player.contains("time_elapsed"));
    EXPECT_TRUE(player.contains("status"));
    EXPECT_TRUE(player["current_track"].is_object());
}

/*******************************************************************************
 * get_states
 *
 * MEASURED AND REPORTED AS A FINDING: get_all_values_bool/double/string() are
 * only overridden by IOAVReceiver (IOBase.h:103-111 return an empty map).
 * get_states therefore answers {} for every IO of a normal house. The command
 * is characterized as it behaves, empty answers included.
 ******************************************************************************/

TEST_F(JsonApiHomeTest, GetStatesOfAKnownIoAnswersAnEmptyObject)
{
    loadReferenceHouse();

    WsTestSession ws;
    ws.send(Json{{ "msg", "get_states" },
                 { "msg_id", "1" },
                 { "data", {{ "id", HOUSE_INT }} }});

    ASSERT_EQ(1u, ws.count());
    EXPECT_JSON_EQ(std::string(R"({"msg":"get_states","msg_id":"1","data":{}})"),
                   ws.lastMessage());
}

TEST_F(JsonApiHomeTest, GetStatesOfAnUnknownIoIsAnError)
{
    loadReferenceHouse();

    WsTestSession ws;
    ws.send(Json{{ "msg", "get_states" },
                 { "msg_id", "1" },
                 { "data", {{ "id", "e40b_no_such_io" }} }});

    ASSERT_EQ(1u, ws.count());
    EXPECT_JSON_EQ(std::string(R"({"msg":"get_states","msg_id":"1",)"
                               R"("data":{"error":"wrong id"}})"),
                   ws.lastMessage());
}

TEST_F(JsonApiHomeTest, GetStatesWithoutAnIdAnswersAnEmptyObject)
{
    //No "id" member: the whole lookup is skipped and an empty Params is
    //serialized. Not an error.
    loadReferenceHouse();

    WsTestSession ws;
    ws.send(Json{{ "msg", "get_states" }, { "msg_id", "1" }, { "data", Json::object() }});

    ASSERT_EQ(1u, ws.count());
    EXPECT_JSON_EQ(std::string(R"({"msg":"get_states","msg_id":"1","data":{}})"),
                   ws.lastMessage());
}

TEST_F(JsonApiHomeTest, HttpGetStatesBehavesLikeWs)
{
    loadReferenceHouse();

    HttpTestRequest known;
    known.send(authenticated(Json{{ "action", "get_states" }, { "id", HOUSE_INT }}));
    ASSERT_EQ(1u, known.count());
    EXPECT_JSON_EQ(std::string("{}"), known.body());

    HttpTestRequest unknown;
    unknown.send(authenticated(Json{{ "action", "get_states" },
                                    { "id", "e40b_no_such_io" }}));
    ASSERT_EQ(1u, unknown.count());
    EXPECT_JSON_EQ(std::string(R"({"error":"wrong id"})"), unknown.body());
}

/*******************************************************************************
 * query
 *
 * FROZEN BUG. buildQuery() (JsonApi.cpp:641-661) gates on Exists("id") and
 * resolves jParam["input_id"]. The three cases below are the complete truth
 * table of that mismatch.
 ******************************************************************************/

TEST_F(JsonApiHomeTest, QueryWithAValidIdAndNoInputIdAnswersWrongId)
{
    //THE bug: the only well formed request a client would write answers an
    //error, because the id it is gated on is not the id it looks up.
    loadReferenceHouse();

    WsTestSession ws;
    ws.send(Json{{ "msg", "query" },
                 { "msg_id", "1" },
                 { "data", {{ "id", HOUSE_INT }, { "param", "name" }} }});

    ASSERT_EQ(1u, ws.count());
    EXPECT_JSON_EQ(std::string(R"({"msg":"query","msg_id":"1",)"
                               R"("data":{"error":"wrong id"}})"),
                   ws.lastMessage());
}

TEST_F(JsonApiHomeTest, QueryNeedsBothIdAndInputIdToResolveAnything)
{
    //With BOTH keys the lookup succeeds. The answer is still {}: query_param()
    //is only overridden by IOAVReceiver (IOBase.h:111).
    loadReferenceHouse();

    WsTestSession ws;
    ws.send(Json{{ "msg", "query" },
                 { "msg_id", "1" },
                 { "data", {{ "id", "anything at all" },
                            { "input_id", HOUSE_INT },
                            { "param", "name" }} }});

    ASSERT_EQ(1u, ws.count());
    EXPECT_JSON_EQ(std::string(R"({"msg":"query","msg_id":"1","data":{}})"),
                   ws.lastMessage());
}

TEST_F(JsonApiHomeTest, QueryWithOnlyInputIdNeverLooksAnythingUp)
{
    //The gate is never opened, so even a valid input_id answers {} instead of
    //querying the IO.
    loadReferenceHouse();

    WsTestSession ws;
    ws.send(Json{{ "msg", "query" },
                 { "msg_id", "1" },
                 { "data", {{ "input_id", HOUSE_INT }, { "param", "name" }} }});

    ASSERT_EQ(1u, ws.count());
    EXPECT_JSON_EQ(std::string(R"({"msg":"query","msg_id":"1","data":{}})"),
                   ws.lastMessage());
}

TEST_F(JsonApiHomeTest, HttpQueryCarriesTheSameBug)
{
    loadReferenceHouse();

    HttpTestRequest req;
    req.send(authenticated(Json{{ "action", "query" },
                                { "id", HOUSE_INT },
                                { "param", "name" }}));

    ASSERT_EQ(1u, req.count());
    EXPECT_JSON_EQ(std::string(R"({"error":"wrong id"})"), req.body());
}

/*******************************************************************************
 * get_param / set_param / del_param
 ******************************************************************************/

TEST_F(JsonApiHomeTest, GetParamAnswersTheValueKeyedByTheParamName)
{
    loadReferenceHouse();

    WsTestSession ws;
    ws.send(Json{{ "msg", "get_param" },
                 { "msg_id", "1" },
                 { "data", {{ "id", HOUSE_INT }, { "param", "name" }} }});

    ASSERT_EQ(1u, ws.count());
    EXPECT_JSON_EQ(std::string(R"({"msg":"get_param","msg_id":"1",)"
                               R"("data":{"name":"Int value"}})"),
                   ws.lastMessage());
}

TEST_F(JsonApiHomeTest, GetParamOnAnUnknownIoIsAnError)
{
    loadReferenceHouse();

    WsTestSession ws;
    ws.send(Json{{ "msg", "get_param" },
                 { "msg_id", "1" },
                 { "data", {{ "id", "e40b_no_such_io" }, { "param", "name" }} }});

    ASSERT_EQ(1u, ws.count());
    EXPECT_JSON_EQ(std::string(R"({"msg":"get_param","msg_id":"1",)"
                               R"("data":{"error":"wrong io/param"}})"),
                   ws.lastMessage());
}

TEST_F(JsonApiHomeTest, GetParamOnAnUnknownParamOfAKnownIoIsAnEmptyString)
{
    //FROZEN: "wrong io/param" only ever means "wrong io". An unknown param
    //answers the empty string keyed by the name that was asked for.
    loadReferenceHouse();

    WsTestSession ws;
    ws.send(Json{{ "msg", "get_param" },
                 { "msg_id", "1" },
                 { "data", {{ "id", HOUSE_INT },
                            { "param", "no_such_param" }} }});

    ASSERT_EQ(1u, ws.count());
    EXPECT_JSON_EQ(std::string(R"({"msg":"get_param","msg_id":"1",)"
                               R"("data":{"no_such_param":""}})"),
                   ws.lastMessage());
}

TEST_F(JsonApiHomeTest, GetParamWithoutAParamMemberAnswersAnEmptyKey)
{
    //FROZEN: a JSON object with an EMPTY STRING as key. Perfectly legal JSON,
    //and a good reason to keep this test: an implementation that refused the
    //empty key would change an observable answer.
    loadReferenceHouse();

    WsTestSession ws;
    ws.send(Json{{ "msg", "get_param" },
                 { "msg_id", "1" },
                 { "data", {{ "id", HOUSE_INT }} }});

    ASSERT_EQ(1u, ws.count());
    EXPECT_JSON_EQ(std::string(R"({"msg":"get_param","msg_id":"1","data":{"":""}})"),
                   ws.lastMessage());
}

TEST_F(JsonApiHomeTest, SetParamThenGetParamRoundTrip)
{
    loadReferenceHouse();

    WsTestSession ws;
    ws.send(Json{{ "msg", "set_param" },
                 { "msg_id", "1" },
                 { "data", {{ "id", HOUSE_INT },
                            { "param", "e40b_custom" },
                            { "value", "42" }} }});

    ASSERT_EQ(1u, ws.count());
    EXPECT_JSON_EQ(std::string(R"({"msg":"set_param","msg_id":"1",)"
                               R"("data":{"success":"true"}})"),
                   ws.lastMessage());

    ws.clear();
    ws.send(Json{{ "msg", "get_param" },
                 { "msg_id", "2" },
                 { "data", {{ "id", HOUSE_INT }, { "param", "e40b_custom" }} }});

    ASSERT_EQ(1u, ws.count());
    EXPECT_EQ("42", ws.lastData().value("e40b_custom", std::string()));
}

TEST_F(JsonApiHomeTest, SetParamOfAKeyOutsideTheSixteenStaysOutOfGetIo)
{
    //buildJsonIO() only emits its 16 known keys, so a custom param must NOT
    //show up there. The IO's param list and the payload's key list are two
    //different things, and that is the contract. set_param SUCCEEDS - the
    //param really is stored, get_param reads it back (see the round trip case
    //above) - it simply never reaches the get_io payload.
    loadReferenceHouse();

    WsTestSession ws;
    ws.send(Json{{ "msg", "set_param" },
                 { "msg_id", "1" },
                 { "data", {{ "id", HOUSE_INT },
                            { "param", "e40b_custom" },
                            { "value", "42" }} }});
    ASSERT_EQ(1u, ws.count());

    ws.clear();
    ws.send(Json{{ "msg", "get_io" },
                 { "msg_id", "2" },
                 { "data", {{ "items", Json::array({ HOUSE_INT }) }} }});

    ASSERT_EQ(1u, ws.count());
    EXPECT_FALSE(ws.lastData()[HOUSE_INT].contains("e40b_custom"));
}

TEST_F(JsonApiHomeTest, SetParamOnAKeyOfBuildJsonIoChangesThePayload)
{
    //The other half of the previous case: a param that IS one of the 16 keys
    //is reflected immediately.
    loadReferenceHouse();

    WsTestSession ws;
    ws.send(Json{{ "msg", "set_param" },
                 { "msg_id", "1" },
                 { "data", {{ "id", HOUSE_INT },
                            { "param", "unit" },
                            { "value", "\xc2\xb0""C" }} }});
    ASSERT_EQ(1u, ws.count());

    ws.clear();
    ws.send(Json{{ "msg", "get_io" },
                 { "msg_id", "2" },
                 { "data", {{ "items", Json::array({ HOUSE_INT }) }} }});

    ASSERT_EQ(1u, ws.count());
    EXPECT_EQ("\xc2\xb0""C", ws.lastData()[HOUSE_INT].value("unit", std::string()));
}

TEST_F(JsonApiHomeTest, SetParamRefusesAnUnknownIoAnEmptyParamAndAnEmptyValue)
{
    loadReferenceHouse();

    const std::string error = R"({"error":"wrong io/param"})";

    WsTestSession ws;
    ws.send(Json{{ "msg", "set_param" },
                 { "msg_id", "1" },
                 { "data", {{ "id", "e40b_no_such_io" },
                            { "param", "p" }, { "value", "v" }} }});
    ASSERT_EQ(1u, ws.count());
    EXPECT_JSON_EQ(error, ws.lastData());

    ws.clear();
    ws.send(Json{{ "msg", "set_param" },
                 { "msg_id", "2" },
                 { "data", {{ "id", HOUSE_INT }, { "value", "v" }} }});
    ASSERT_EQ(1u, ws.count());
    EXPECT_JSON_EQ(error, ws.lastData());

    ws.clear();
    //an EMPTY value is refused too - so a param cannot be blanked with
    //set_param, only deleted with del_param
    ws.send(Json{{ "msg", "set_param" },
                 { "msg_id", "3" },
                 { "data", {{ "id", HOUSE_INT }, { "param", "unit" },
                            { "value", "" }} }});
    ASSERT_EQ(1u, ws.count());
    EXPECT_JSON_EQ(error, ws.lastData());
}

TEST_F(JsonApiHomeTest, SetParamRaisesAnIoChangedEvent)
{
    //JsonApi.cpp:696-698. Characterized here because the event carries the
    //param name AS A KEY, not as a value - a shape no other event uses.
    loadReferenceHouse();

    WsTestSession ws;
    ws.send(Json{{ "msg", "set_param" },
                 { "msg_id", "1" },
                 { "data", {{ "id", HOUSE_INT },
                            { "param", "e40b_evt" },
                            { "value", "on" }} }});
    ASSERT_EQ(1u, ws.count());

    ws.clear();
    pumpEventLoop();

    ASSERT_EQ(1u, ws.count()) << "expected the queued EventIOChanged";
    const Json env = ws.lastEnvelope();
    EXPECT_EQ("event", env.value("msg", std::string()));
    EXPECT_EQ("io_changed", env["data"].value("type_str", std::string()));
    EXPECT_EQ(HOUSE_INT, env["data"]["data"].value("id", std::string()));
    EXPECT_EQ("on", env["data"]["data"].value("e40b_evt", std::string()));
}

TEST_F(JsonApiHomeTest, DelParamRemovesTheKeyFromGetIoInsteadOfNullingIt)
{
    //THE case for the "absent key, never null" contract: "unit" is one of the
    //16 keys of buildJsonIO(), it is emitted while the param exists and it
    //DISAPPEARS once deleted. A migration writing j["unit"] = nullptr would
    //keep the key with a null value and break exactly here.
    loadReferenceHouse();

    WsTestSession ws;
    ws.send(Json{{ "msg", "set_param" },
                 { "msg_id", "1" },
                 { "data", {{ "id", HOUSE_INT }, { "param", "unit" },
                            { "value", "kWh" }} }});
    ASSERT_EQ(1u, ws.count());

    ws.clear();
    ws.send(Json{{ "msg", "get_io" },
                 { "msg_id", "2" },
                 { "data", {{ "items", Json::array({ HOUSE_INT }) }} }});
    ASSERT_EQ(1u, ws.count());
    ASSERT_EQ("kWh", ws.lastData()[HOUSE_INT].value("unit", std::string()));

    ws.clear();
    ws.send(Json{{ "msg", "del_param" },
                 { "msg_id", "3" },
                 { "data", {{ "id", HOUSE_INT }, { "param", "unit" }} }});
    ASSERT_EQ(1u, ws.count());
    EXPECT_JSON_EQ(std::string(R"({"success":"true"})"), ws.lastData());

    ws.clear();
    ws.send(Json{{ "msg", "get_io" },
                 { "msg_id", "4" },
                 { "data", {{ "items", Json::array({ HOUSE_INT }) }} }});
    ASSERT_EQ(1u, ws.count());
    const Json jio = ws.lastData()[HOUSE_INT];
    EXPECT_FALSE(jio.contains("unit")) << jio.dump();
    EXPECT_TRUE(hasNoNullAnywhere(jio));
}

TEST_F(JsonApiHomeTest, DelParamRefusesAnUnknownIoAndAnEmptyParam)
{
    loadReferenceHouse();

    const std::string error = R"({"error":"wrong io/param"})";

    WsTestSession ws;
    ws.send(Json{{ "msg", "del_param" },
                 { "msg_id", "1" },
                 { "data", {{ "id", "e40b_no_such_io" }, { "param", "unit" }} }});
    ASSERT_EQ(1u, ws.count());
    EXPECT_JSON_EQ(error, ws.lastData());

    ws.clear();
    ws.send(Json{{ "msg", "del_param" },
                 { "msg_id", "2" },
                 { "data", {{ "id", HOUSE_INT }} }});
    ASSERT_EQ(1u, ws.count());
    EXPECT_JSON_EQ(error, ws.lastData());
}

TEST_F(JsonApiHomeTest, DelParamOfAnAbsentParamStillSucceeds)
{
    //Params::Delete() on a missing key is a no-op and success stays true. Not
    //an idempotency guarantee anyone designed - just what the code does.
    loadReferenceHouse();

    WsTestSession ws;
    ws.send(Json{{ "msg", "del_param" },
                 { "msg_id", "1" },
                 { "data", {{ "id", HOUSE_INT }, { "param", "never_set" }} }});

    ASSERT_EQ(1u, ws.count());
    EXPECT_JSON_EQ(std::string(R"({"success":"true"})"), ws.lastData());
}

TEST_F(JsonApiHomeTest, HttpParamCommandsBehaveLikeWs)
{
    loadReferenceHouse();

    HttpTestRequest set;
    set.send(authenticated(Json{{ "action", "set_param" },
                                { "id", HOUSE_STRING },
                                { "param", "unit" },
                                { "value", "lux" }}));
    ASSERT_EQ(1u, set.count());
    EXPECT_JSON_EQ(std::string(R"({"success":"true"})"), set.body());

    HttpTestRequest get;
    get.send(authenticated(Json{{ "action", "get_param" },
                                { "id", HOUSE_STRING },
                                { "param", "unit" }}));
    ASSERT_EQ(1u, get.count());
    EXPECT_JSON_EQ(std::string(R"({"unit":"lux"})"), get.body());

    HttpTestRequest del;
    del.send(authenticated(Json{{ "action", "del_param" },
                                { "id", HOUSE_STRING },
                                { "param", "unit" }}));
    ASSERT_EQ(1u, del.count());
    EXPECT_JSON_EQ(std::string(R"({"success":"true"})"), del.body());

    HttpTestRequest gone;
    gone.send(authenticated(Json{{ "action", "get_param" },
                                 { "id", HOUSE_STRING },
                                 { "param", "unit" }}));
    ASSERT_EQ(1u, gone.count());
    EXPECT_JSON_EQ(std::string(R"({"unit":""})"), gone.body());
}

TEST_F(JsonApiHomeTest, SetParamAndDelParamAreDeniedToAServiceScopedSession)
{
    //WS ONLY (JsonApiHandlerWS.cpp:175-184). The HTTP transport has no scope,
    //which is itself part of the frozen behaviour.
    loadReferenceHouse();

    WsTestSession ws(true /*authenticated*/, true /*serviceScope*/);
    ws.send(Json{{ "msg", "set_param" },
                 { "msg_id", "1" },
                 { "data", {{ "id", HOUSE_INT }, { "param", "unit" },
                            { "value", "kWh" }} }});

    ASSERT_EQ(1u, ws.count());
    EXPECT_JSON_EQ(std::string(R"({"msg":"set_param","msg_id":"1",)"
                               R"("data":{"error":"scope denied"}})"),
                   ws.lastMessage());

    ws.clear();
    ws.send(Json{{ "msg", "del_param" },
                 { "msg_id", "2" },
                 { "data", {{ "id", HOUSE_INT }, { "param", "unit" }} }});

    ASSERT_EQ(1u, ws.count());
    EXPECT_JSON_EQ(std::string(R"({"msg":"del_param","msg_id":"2",)"
                               R"("data":{"error":"scope denied"}})"),
                   ws.lastMessage());

    //and the denial really is a denial: the param was not written
    ws.clear();
    ws.setServiceScope(false);
    ws.send(Json{{ "msg", "get_param" },
                 { "msg_id", "3" },
                 { "data", {{ "id", HOUSE_INT }, { "param", "unit" }} }});
    ASSERT_EQ(1u, ws.count());
    EXPECT_EQ("", ws.lastData().value("unit", std::string()));
}

TEST_F(JsonApiHomeTest, GetParamAndGetStatesAreNotScopeDenied)
{
    //Only the four mutating/heavy commands are gated. Pinned so a migration
    //cannot widen or narrow the list unnoticed.
    loadReferenceHouse();

    WsTestSession ws(true, true /*serviceScope*/);
    ws.send(Json{{ "msg", "get_param" },
                 { "msg_id", "1" },
                 { "data", {{ "id", HOUSE_INT }, { "param", "name" }} }});

    ASSERT_EQ(1u, ws.count());
    EXPECT_JSON_EQ(std::string(R"({"name":"Int value"})"), ws.lastData());
}

/*******************************************************************************
 * set_state
 ******************************************************************************/

TEST_F(JsonApiHomeTest, SetStateOnTheThreeVariableTypes)
{
    loadReferenceHouse();

    WsTestSession ws;

    ws.send(Json{{ "msg", "set_state" },
                 { "msg_id", "1" },
                 { "data", {{ "id", HOUSE_BOOL_OUT }, { "value", "true" }} }});
    ASSERT_EQ(1u, ws.count());
    EXPECT_JSON_EQ(std::string(R"({"msg":"set_state","msg_id":"1",)"
                               R"("data":{"success":"true"}})"),
                   ws.lastMessage());

    ws.clear();
    ws.send(Json{{ "msg", "set_state" },
                 { "msg_id", "2" },
                 { "data", {{ "id", HOUSE_INT }, { "value", "7" }} }});
    ASSERT_EQ(1u, ws.count());
    EXPECT_JSON_EQ(std::string(R"({"success":"true"})"), ws.lastData());

    ws.clear();
    ws.send(Json{{ "msg", "set_state" },
                 { "msg_id", "3" },
                 { "data", {{ "id", HOUSE_STRING }, { "value", "hello" }} }});
    ASSERT_EQ(1u, ws.count());
    EXPECT_JSON_EQ(std::string(R"({"success":"true"})"), ws.lastData());

    //and the three values really landed
    ws.clear();
    ws.send(Json{{ "msg", "get_state" },
                 { "msg_id", "4" },
                 { "data", {{ "items", Json::array({ HOUSE_BOOL_OUT, HOUSE_INT,
                                                     HOUSE_STRING }) }} }});
    ASSERT_EQ(1u, ws.count());
    const Json data = ws.lastData();
    EXPECT_EQ("true", data.value(HOUSE_BOOL_OUT, std::string()));
    EXPECT_EQ("7", data.value(HOUSE_INT, std::string()));
    EXPECT_EQ("hello", data.value(HOUSE_STRING, std::string()));
}

TEST_F(JsonApiHomeTest, SetStateOnAnUnknownIoAnswersSuccessFalse)
{
    //Not an "error" object: set_state has its own vocabulary,
    //{"success":"false"}, and it is the only command here that reports failure
    //that way.
    loadReferenceHouse();

    WsTestSession ws;
    ws.send(Json{{ "msg", "set_state" },
                 { "msg_id", "1" },
                 { "data", {{ "id", "e40b_no_such_io" }, { "value", "true" }} }});

    ASSERT_EQ(1u, ws.count());
    EXPECT_JSON_EQ(std::string(R"({"msg":"set_state","msg_id":"1",)"
                               R"("data":{"success":"false"}})"),
                   ws.lastMessage());
}

TEST_F(JsonApiHomeTest, WsSetStateWithoutAMsgIdAnswersNothingAtAll)
{
    //DIVERGENCE, frozen: processSetState() only answers when client_id is not
    //empty (JsonApiHandlerWS.cpp:334). The state IS changed, the client just
    //never hears about it. HTTP always answers - see the case right after.
    loadReferenceHouse();

    WsTestSession ws;
    ws.send(Json{{ "msg", "set_state" },
                 { "data", {{ "id", HOUSE_BOOL_OUT }, { "value", "true" }} }});

    EXPECT_EQ(0u, ws.count()) << "expected silence, got: " << ws.lastMessage();

    //silent, but not a no-op
    ws.send(Json{{ "msg", "get_state" },
                 { "msg_id", "1" },
                 { "data", {{ "items", Json::array({ HOUSE_BOOL_OUT }) }} }});
    ASSERT_EQ(1u, ws.count());
    EXPECT_EQ("true", ws.lastData().value(HOUSE_BOOL_OUT, std::string()));
}

TEST_F(JsonApiHomeTest, HttpSetStateAlwaysAnswers)
{
    loadReferenceHouse();

    HttpTestRequest ok;
    ok.send(authenticated(Json{{ "action", "set_state" },
                               { "id", HOUSE_BOOL_OUT },
                               { "value", "true" }}));
    ASSERT_EQ(1u, ok.count());
    EXPECT_JSON_EQ(std::string(R"({"success":"true"})"), ok.body());

    HttpTestRequest ko;
    ko.send(authenticated(Json{{ "action", "set_state" },
                               { "id", "e40b_no_such_io" },
                               { "value", "true" }}));
    ASSERT_EQ(1u, ko.count());
    EXPECT_JSON_EQ(std::string(R"({"success":"false"})"), ko.body());
}

TEST_F(JsonApiHomeTest, SetStateOnABoolAcceptsToggleLikeValues)
{
    //decodeSetState() special-cases the literals "true"/"false" for a TBOOL and
    //hands anything else to the string overload of set_value()
    //(JsonApi.cpp:770-775), which is how "toggle"/"impulse" reach an output.
    loadReferenceHouse();

    WsTestSession ws;
    ws.send(Json{{ "msg", "set_state" },
                 { "msg_id", "1" },
                 { "data", {{ "id", HOUSE_BOOL_OUT }, { "value", "toggle" }} }});

    ASSERT_EQ(1u, ws.count());
    EXPECT_JSON_EQ(std::string(R"({"success":"true"})"), ws.lastData());

    ws.clear();
    ws.send(Json{{ "msg", "get_state" },
                 { "msg_id", "2" },
                 { "data", {{ "items", Json::array({ HOUSE_BOOL_OUT }) }} }});
    ASSERT_EQ(1u, ws.count());
    EXPECT_EQ("true", ws.lastData().value(HOUSE_BOOL_OUT, std::string()));
}

TEST_F(JsonApiHomeTest, SetStateRaisesAnIoChangedEvent)
{
    loadReferenceHouse();

    WsTestSession ws;
    ws.send(Json{{ "msg", "set_state" },
                 { "msg_id", "1" },
                 { "data", {{ "id", HOUSE_BOOL_OUT }, { "value", "true" }} }});
    ASSERT_EQ(1u, ws.count());

    ws.clear();
    pumpEventLoop();

    ASSERT_LE(1u, ws.count());
    const Json env = ws.lastEnvelope();
    EXPECT_EQ("event", env.value("msg", std::string()));
    EXPECT_EQ("io_changed", env["data"].value("type_str", std::string()));
}
