/******************************************************************************
 **  Copyright (c) 2006-2025, Calaos. All Rights Reserved.
 **
 **  This file is part of Calaos.
 **
 **  Calaos is free software; you can redistribute it and/or modify
 **  it under the terms of the GNU General Public License as published by
 **  the Free Software Foundation; either version 3 of the License, or
 **  (at your option) any later version.
 **
 **  Calaos is distributed in the hope that it will be useful,
 **  but WITHOUT ANY WARRANTY; without even the implied warranty of
 **  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 **  GNU General Public License for more details.
 **
 **  You should have received a copy of the GNU General Public License
 **  along with Foobar; if not, write to the Free Software
 **  Foundation, Inc., 51 Franklin St, Fifth Floor, Boston, MA  02110-1301  USA
 **
 ******************************************************************************/

/* T1.4 — hardening of the json api.
 *
 * Covers the parts that can be exercised without a running libuv loop and
 * without a real http client: the security helpers of JsonApi and the login
 * throttle state machine. The throttle takes the current time as a parameter
 * precisely so it can be driven here without any timer.
 */

#include "CalaosCoreFixture.h"

#include "JsonApi.h"
#include "FileUtils.h"
#include "LogSetup.h"

#include <fstream>
#include <sys/stat.h>

using namespace CalaosTest;

/******************************************************************************
 * Constant time comparison (F2)
 ******************************************************************************/

TEST(JsonApiSecureCompare, AcceptsIdenticalSecrets)
{
    EXPECT_TRUE(JsonApi::secureCompare("s3cr3t", "s3cr3t"));
    EXPECT_TRUE(JsonApi::secureCompare("", ""));

    //A real token: 64 hex chars, as generated by RAND_bytes
    const std::string token(64, 'a');
    EXPECT_TRUE(JsonApi::secureCompare(token, token));
}

TEST(JsonApiSecureCompare, RejectsDifferentSecrets)
{
    EXPECT_FALSE(JsonApi::secureCompare("s3cr3t", "S3cr3t"));
    EXPECT_FALSE(JsonApi::secureCompare("s3cr3t", "s3cr3T"));
    EXPECT_FALSE(JsonApi::secureCompare("s3cr3t", ""));
    EXPECT_FALSE(JsonApi::secureCompare("", "s3cr3t"));
}

TEST(JsonApiSecureCompare, RejectsPrefixOfTheSecret)
{
    //The old std::equal based check returned on the first differing byte and
    //compared sizes first, both leaking information through timing
    EXPECT_FALSE(JsonApi::secureCompare("s3cr3t", "s3cr"));
    EXPECT_FALSE(JsonApi::secureCompare("s3cr", "s3cr3t"));
}

TEST(JsonApiSecureCompare, HandlesEmbeddedNulBytes)
{
    std::string a("ab\0cd", 5);
    std::string b("ab\0ce", 5);

    EXPECT_TRUE(JsonApi::secureCompare(a, a));
    EXPECT_FALSE(JsonApi::secureCompare(a, b));
}

/******************************************************************************
 * Integer parameters given to calaos_picture (F7)
 ******************************************************************************/

TEST(JsonApiIntParam, AcceptsPlainIntegers)
{
    EXPECT_TRUE(JsonApi::isValidIntParam("100", 1, 10000));
    EXPECT_TRUE(JsonApi::isValidIntParam("1", 1, 10000));
    EXPECT_TRUE(JsonApi::isValidIntParam("10000", 1, 10000));
    EXPECT_TRUE(JsonApi::isValidIntParam("0", -360, 360));
    EXPECT_TRUE(JsonApi::isValidIntParam("-90", -360, 360));
}

TEST(JsonApiIntParam, RejectsArgumentInjection)
{
    //The command line used to be split on spaces: anything after a space was
    //an extra argv entry for calaos_picture
    EXPECT_FALSE(JsonApi::isValidIntParam("100 --flag", 1, 10000));
    EXPECT_FALSE(JsonApi::isValidIntParam("100 -r 90", 1, 10000));
    EXPECT_FALSE(JsonApi::isValidIntParam("100 /etc/passwd", 1, 10000));
    EXPECT_FALSE(JsonApi::isValidIntParam("--version", 1, 10000));
    EXPECT_FALSE(JsonApi::isValidIntParam("90 x", -360, 360));
}

TEST(JsonApiIntParam, RejectsNonIntegers)
{
    EXPECT_FALSE(JsonApi::isValidIntParam("", 1, 10000));
    EXPECT_FALSE(JsonApi::isValidIntParam("abc", 1, 10000));
    EXPECT_FALSE(JsonApi::isValidIntParam("1.5", 1, 10000));
    EXPECT_FALSE(JsonApi::isValidIntParam("0x10", 1, 10000));
    EXPECT_FALSE(JsonApi::isValidIntParam(" 100", 1, 10000));
    EXPECT_FALSE(JsonApi::isValidIntParam("100\n", 1, 10000));
    EXPECT_FALSE(JsonApi::isValidIntParam("+100", 1, 10000));
    EXPECT_FALSE(JsonApi::isValidIntParam("-", 1, 10000));
}

TEST(JsonApiIntParam, RejectsOutOfRangeValues)
{
    EXPECT_FALSE(JsonApi::isValidIntParam("0", 1, 10000));
    EXPECT_FALSE(JsonApi::isValidIntParam("10001", 1, 10000));
    EXPECT_FALSE(JsonApi::isValidIntParam("-1", 1, 10000));
    EXPECT_FALSE(JsonApi::isValidIntParam("361", -360, 360));
    //Does not overflow on huge values either
    EXPECT_FALSE(JsonApi::isValidIntParam("99999999999999999999", 1, 10000));
}

/******************************************************************************
 * Redaction of the credentials in the logs (F4)
 ******************************************************************************/

/* WHAT REPLACED THE REDACTION LIST, AND WHY THE ORACLE HAD TO MOVE WITH IT.
 *
 * The old cases asked "is this secret masked" of a list of eleven names. That
 * question has no good answer: config/put uploads local_config.xml under a key
 * that is a FILE NAME, and no list of credential names had a reason to carry
 * it. The oracle is the other way round now - a value is published only when
 * its key is one this server routes on, so a key nobody here has heard of is
 * withheld BECAUSE it is unknown, and a case can say so by inventing one.
 *
 * These cases exercise the reducer directly, which is exactly what they cannot
 * prove on their own: the guard on the real path is in
 * tests/core/HttpRequestLogSecret_test.cpp, over a socket.
 */

TEST(JsonApiRequestDescription, PublishesTheRoutingWordsAndNothingElse)
{
    Json j;
    j["cn_user"] = "admin";
    j["cn_pass"] = "sup3rs3cr3t";
    j["action"] = "get_home";

    const std::string dump = JsonApi::describeRequestForLog(j);

    EXPECT_EQ(dump.find("sup3rs3cr3t"), std::string::npos) << dump;
    EXPECT_EQ(dump.find("admin"), std::string::npos)
            << "a value nothing routes on is published: " << dump;

    //Both halves: the pair must be NAMED, not dropped, or an integrator can no
    //longer see what its client sent.
    EXPECT_NE(dump.find("cn_pass[11B]"), std::string::npos) << dump;
    EXPECT_NE(dump.find("cn_user[5B]"), std::string::npos) << dump;
    EXPECT_NE(dump.find("action=get_home"), std::string::npos) << dump;
}

TEST(JsonApiRequestDescription, AKeyNobodyHereHasHeardOfIsWithheldBecauseItIsUnknown)
{
    //THE CASE THE ELEVEN NAMES COULD NOT HAVE. Three carriers that no
    //redaction list of this tree ever named, and one of them is the shape the
    //API itself uploads: a file name.
    Json files;
    files["local_config.xml"] = "<?xml version=\"1.0\"?><calaos><mcp_token>LEAK_MCP_TOKEN_LEAK</mcp_token></calaos>";

    Json j;
    j["action"] = "config";
    j["type"] = "put";
    j["config_files"] = files;
    j["x_calaos_future_auth"] = "LEAK_FUTURE_LEAK";

    const std::string dump = JsonApi::describeRequestForLog(j);

    EXPECT_EQ(dump.find("LEAK_MCP_TOKEN_LEAK"), std::string::npos)
            << "the file this server writes its own tokens into is in the log: " << dump;
    EXPECT_EQ(dump.find("LEAK_FUTURE_LEAK"), std::string::npos)
            << "a key no list of this tree names is published in clear: " << dump;

    //The counterweight, in the same case: which command, which sub-command,
    //and which files it carried are all still readable.
    EXPECT_NE(dump.find("action=config"), std::string::npos) << dump;
    EXPECT_NE(dump.find("type=put"), std::string::npos) << dump;
    EXPECT_NE(dump.find("local_config.xml"), std::string::npos) << dump;
}

TEST(JsonApiRequestDescription, TheSecretOfSetParamTravelsUnderTheKeyValue)
{
    //set_param is why a list of key NAMES cannot work even in principle: the
    //word "password" is the VALUE of `param` here, and the camera credential
    //sits under `value`. Neither key can be added to any list without losing
    //every legitimate set_param.
    Json j;
    j["action"] = "set_param";
    j["id"] = "io_cam_1";
    j["param"] = "password";
    j["value"] = "LEAK_CAMERA_PASSWORD_LEAK";

    const std::string dump = JsonApi::describeRequestForLog(j);

    EXPECT_EQ(dump.find("LEAK_CAMERA_PASSWORD_LEAK"), std::string::npos) << dump;
    EXPECT_EQ(dump.find("io_cam_1"), std::string::npos) << dump;
    EXPECT_NE(dump.find("action=set_param"), std::string::npos) << dump;
    EXPECT_NE(dump.find("value[25B]"), std::string::npos) << dump;
}

TEST(JsonApiRequestDescription, TheSetIsCaseSensitiveSoAFoldCannotWidenIt)
{
    //Folding the key would only ever ADD to what is published, and this set is
    //allowed to narrow and nothing else.
    Json j;
    j["Action"] = "get_home";
    j["MSG"] = "login";

    const std::string dump = JsonApi::describeRequestForLog(j);

    EXPECT_EQ(dump.find("get_home"), std::string::npos) << dump;
    EXPECT_EQ(dump.find("login"), std::string::npos) << dump;
    EXPECT_NE(dump.find("Action[8B]"), std::string::npos) << dump;
}

TEST(JsonApiRequestDescription, ARoutingWordTooLongToBeGrammarIsWithheldToo)
{
    //`action` is published, so it would otherwise be a channel of its own: a
    //client that puts four kilobytes there would have them written out.
    Json j;
    j["action"] = std::string(64, 'z');

    const std::string dump = JsonApi::describeRequestForLog(j);

    EXPECT_EQ(dump.find(std::string(64, 'z')), std::string::npos) << dump;
    EXPECT_NE(dump.find("action[64B]"), std::string::npos) << dump;
}

TEST(JsonApiRequestDescription, HandlesNullAndArrays)
{
    //nullptr still answers the empty string: a null Json is what either caller
    //holds whenever a non throwing parse discards a bad message.
    EXPECT_EQ(JsonApi::describeRequestForLog(nullptr), std::string());
    EXPECT_EQ(JsonApi::describeRequestForLog(Json::parse("not json", nullptr, false)),
              std::string());

    Json item;
    item["password"] = "insidearray";
    Json j;
    j["items"] = Json::array({ item });

    const std::string dump = JsonApi::describeRequestForLog(j);

    EXPECT_EQ(dump.find("insidearray"), std::string::npos) << dump;
    EXPECT_NE(dump.find("items[1"), std::string::npos) << dump;
}

TEST(JsonApiRequestDescription, ANewlineInAKeyCannotForgeALogLine)
{
    //A key goes on a log LINE, and nothing downstream recovers from a second
    //one appearing inside it.
    Json j;
    j["evil\ninjected"] = "x";

    const std::string dump = JsonApi::describeRequestForLog(j);

    EXPECT_EQ(dump.find('\n'), std::string::npos) << dump;
    EXPECT_NE(dump.find("evil.injected"), std::string::npos) << dump;
}

TEST(JsonApiRequestDescription, TheOutputIsBoundedWhateverTheDocument)
{
    //The line is built on every request, before the credentials are checked,
    //on a body allowed to nest 2048 levels: the old dump cost 16.8 MB there.
    Json deep = "leaf";
    for (int i = 0; i < 400; i++)
    {
        Json wrap;
        wrap["k" + std::to_string(i)] = deep;
        deep = wrap;
    }

    Json wide;
    for (int i = 0; i < 400; i++)
        wide["w" + std::to_string(i)] = "value";
    wide["nested"] = deep;

    const std::string dump = JsonApi::describeRequestForLog(wide);

    EXPECT_LT(dump.size(), (size_t)2048)
            << "the line grows with the document again: " << dump.size() << " bytes";
    EXPECT_NE(dump.find("..."), std::string::npos)
            << "nothing says the description was cut: " << dump;
}

TEST(JsonApiRequestDescription, TwoBodiesDifferingOnlyInWhatIsWithheldRenderDifferently)
{
    //A reduction that renders every config upload identically leaves a reader
    //unable to say which one arrived. Same shape, same byte counts, same keys.
    Json a, b;
    a["action"] = "config";
    a["type"] = "put";
    a["config_files"] = Json{{ "io.xml", "<?xml?><a>aaaa</a>" }};
    b = a;
    b["config_files"] = Json{{ "io.xml", "<?xml?><a>bbbb</a>" }};

    const std::string da = JsonApi::describeRequestForLog(a);
    const std::string db = JsonApi::describeRequestForLog(b);

    ASSERT_EQ(da.size(), db.size()) << da << "\n" << db;
    EXPECT_NE(da, db)
            << "two different uploads render the same line:\n" << da << "\n" << db;
}

/******************************************************************************
 * What the log level does with the request line (T3.65)
 ******************************************************************************/

/* THE PREMISE OF T3.65, AND THE ONLY PLACE IT IS FALSIFIABLE.
 *
 * LogStream appends whatever is streamed into it and looks at the level only
 * in its DESTRUCTOR: `cDebugDom(d) << expensive()` pays for expensive() at
 * every level, and prints it at one. describeRequestForLog() is that argument
 * on the request path, and this case pins that at the level a stock install
 * runs (debug_level defaults to 4, INFO), nothing of it is ever printed.
 *
 * std::cout is captured by its streambuf, not by the file descriptor: Logger
 * writes through the stream object and a redirected fd would also swallow what
 * the test framework prints.
 */
namespace
{

class CoutCapture
{
public:
    CoutCapture(): previous(std::cout.rdbuf(captured.rdbuf())) {}
    ~CoutCapture() { std::cout.rdbuf(previous); }

    CoutCapture(const CoutCapture &) = delete;
    CoutCapture &operator=(const CoutCapture &) = delete;

    std::string str() const { return captured.str(); }

private:
    std::ostringstream captured;
    std::streambuf *previous;
};

} //namespace

TEST(JsonApiRequestLog, TheNetworkDomainPrintsNothingAtDebugLevel)
{
    std::string debugOutput, infoOutput;

    {
        CoutCapture capture;
        cDebugDom("network") << "T365_DEBUG_MARKER";
        debugOutput = capture.str();
    }

    //The control: the very same domain, one level up, DOES print. Without it
    //this case would also pass on a capture that swallows everything.
    {
        CoutCapture capture;
        cInfoDom("network") << "T365_INFO_MARKER";
        infoOutput = capture.str();
    }

    EXPECT_EQ(debugOutput.find("T365_DEBUG_MARKER"), std::string::npos)
            << "the default log level is no longer INFO: " << debugOutput;
    EXPECT_NE(infoOutput.find("T365_INFO_MARKER"), std::string::npos)
            << infoOutput;
}

namespace
{

//One log line on the "network" domain, at a level chosen at run time.
void logNetworkAt(int level, const std::string &marker)
{
    switch (level)
    {
    case Logger::LOG_LEVEL_CRITICAL: cCriticalDom("network") << marker; break;
    case Logger::LOG_LEVEL_ERROR: cErrorDom("network") << marker; break;
    case Logger::LOG_LEVEL_WARNING: cWarningDom("network") << marker; break;
    case Logger::LOG_LEVEL_INFO: cInfoDom("network") << marker; break;
    case Logger::LOG_LEVEL_DEBUG: cDebugDom("network") << marker; break;
    default: FAIL() << "no macro for level " << level;
    }
}

} //namespace

/* THE GUARD OF T3.65 IS ONLY WORTH ANYTHING IF IT ANSWERS WHAT THE DESTRUCTOR
 * WOULD HAVE ANSWERED. It is asked one level too early, from the call site, so
 * this case asks BOTH and compares them, at every level the logger knows.
 *
 * The two counters at the end are what keeps it honest: a predicate stuck on
 * true and a predicate stuck on false both agree with the log at SOME level,
 * and only a case that sees printed and silent levels in the same run can tell
 * them apart.
 */
TEST(JsonApiRequestLog, TheDebugGuardAnswersWhatTheLogPrints)
{
    Logger *logger = Utils::calaosLogger("network");
    ASSERT_TRUE(logger != nullptr);

    int printedLevels = 0, silentLevels = 0;

    for (int level = Logger::LOG_LEVEL_CRITICAL; level <= Logger::LOG_LEVEL_DEBUG; level++)
    {
        const std::string marker = "T365_LEVEL_" + std::to_string(level);
        std::string output;

        {
            CoutCapture capture;
            logNetworkAt(level, marker);
            output = capture.str();
        }

        const bool printed = output.find(marker) != std::string::npos;
        EXPECT_EQ(logger->isLevelEnabled(level), printed)
                << "level " << level << ": the guard and the log disagree";

        printed? printedLevels++: silentLevels++;
    }

    EXPECT_GT(printedLevels, 0) << "no level printed: the comparison is vacuous";
    EXPECT_GT(silentLevels, 0) << "every level printed: the comparison is vacuous";
}

/******************************************************************************
 * Login throttle (F3)
 ******************************************************************************/

class JsonApiThrottleTest: public ::testing::Test
{
protected:
    void SetUp() override { LoginThrottle::clear(); }
    void TearDown() override { LoginThrottle::clear(); }
};

TEST_F(JsonApiThrottleTest, UnknownAddressIsNeverBlocked)
{
    EXPECT_FALSE(LoginThrottle::isBlocked("10.0.0.1", 1000.0));
    EXPECT_EQ(LoginThrottle::trackedCount(), 0);
}

TEST_F(JsonApiThrottleTest, FirstFailureOpensAOneSecondWindow)
{
    LoginThrottle::registerFailure("10.0.0.1", 1000.0);

    EXPECT_TRUE(LoginThrottle::isBlocked("10.0.0.1", 1000.0));
    EXPECT_TRUE(LoginThrottle::isBlocked("10.0.0.1", 1000.5));
    EXPECT_FALSE(LoginThrottle::isBlocked("10.0.0.1", 1001.0));
}

TEST_F(JsonApiThrottleTest, WindowGrowsExponentiallyAndIsCapped)
{
    double now = 1000.0;

    //1s, then 2s, then 4s, 8s...
    LoginThrottle::registerFailure("10.0.0.1", now);
    EXPECT_FALSE(LoginThrottle::isBlocked("10.0.0.1", now + 1.0));

    now += 1.0;
    LoginThrottle::registerFailure("10.0.0.1", now);
    EXPECT_TRUE(LoginThrottle::isBlocked("10.0.0.1", now + 1.5));
    EXPECT_FALSE(LoginThrottle::isBlocked("10.0.0.1", now + 2.0));

    now += 2.0;
    LoginThrottle::registerFailure("10.0.0.1", now);
    EXPECT_TRUE(LoginThrottle::isBlocked("10.0.0.1", now + 3.5));
    EXPECT_FALSE(LoginThrottle::isBlocked("10.0.0.1", now + 4.0));

    //Many more failures never lock the address out for more than MaxDelay
    for (int i = 0;i < 40;i++)
        LoginThrottle::registerFailure("10.0.0.1", now);

    EXPECT_TRUE(LoginThrottle::isBlocked("10.0.0.1", now + LoginThrottle::MaxDelay - 0.1));
    EXPECT_FALSE(LoginThrottle::isBlocked("10.0.0.1", now + LoginThrottle::MaxDelay));
}

TEST_F(JsonApiThrottleTest, ThrottleIsPerSourceAddress)
{
    LoginThrottle::registerFailure("10.0.0.1", 1000.0);

    EXPECT_TRUE(LoginThrottle::isBlocked("10.0.0.1", 1000.0));
    EXPECT_FALSE(LoginThrottle::isBlocked("10.0.0.2", 1000.0));
}

TEST_F(JsonApiThrottleTest, SuccessClearsTheBackoff)
{
    LoginThrottle::registerFailure("10.0.0.1", 1000.0);
    LoginThrottle::registerFailure("10.0.0.1", 1001.0);
    EXPECT_TRUE(LoginThrottle::isBlocked("10.0.0.1", 1001.5));

    LoginThrottle::registerSuccess("10.0.0.1");

    EXPECT_FALSE(LoginThrottle::isBlocked("10.0.0.1", 1001.5));
    EXPECT_EQ(LoginThrottle::trackedCount(), 0);

    //And the backoff starts again from the shortest window
    LoginThrottle::registerFailure("10.0.0.1", 1002.0);
    EXPECT_FALSE(LoginThrottle::isBlocked("10.0.0.1", 1003.0));
}

TEST_F(JsonApiThrottleTest, QuietEntriesExpire)
{
    LoginThrottle::registerFailure("10.0.0.1", 1000.0);
    EXPECT_EQ(LoginThrottle::trackedCount(), 1);

    //Nothing from that address for a long time: it is forgotten
    double later = 1000.0 + LoginThrottle::EntryTimeout + 1.0;
    EXPECT_FALSE(LoginThrottle::isBlocked("10.0.0.1", later));
    EXPECT_EQ(LoginThrottle::trackedCount(), 0);

    //A new failure from another address purges the stale ones as well
    LoginThrottle::registerFailure("10.0.0.5", 2000.0);
    LoginThrottle::registerFailure("10.0.0.6", 2000.0 + LoginThrottle::EntryTimeout + 1.0);
    EXPECT_EQ(LoginThrottle::trackedCount(), 1);
}

TEST_F(JsonApiThrottleTest, TableSizeIsBounded)
{
    //Spoofed source addresses must not be usable to eat memory
    for (int i = 0;i < LoginThrottle::MaxEntries + 500;i++)
    {
        std::string ip = "10.1." + std::to_string(i / 256) + "." + std::to_string(i % 256);
        LoginThrottle::registerFailure(ip, 1000.0 + i * 0.001);
    }

    EXPECT_LE(LoginThrottle::trackedCount(), LoginThrottle::MaxEntries);

    //The most recent addresses are the ones still tracked
    std::string last = "10.1." + std::to_string((LoginThrottle::MaxEntries + 499) / 256) + "." +
                       std::to_string((LoginThrottle::MaxEntries + 499) % 256);
    EXPECT_TRUE(LoginThrottle::isBlocked(last, 1000.0 + (LoginThrottle::MaxEntries + 499) * 0.001));
}

/******************************************************************************
 * Credentials and event pictures, both need the config/cache tree
 ******************************************************************************/

class JsonApiConfigTest: public CoreFixture
{
protected:
    void SetUp() override
    {
        CoreFixture::SetUp();
        LoginThrottle::clear();
    }

    std::string pushPicturesDir() const { return cacheDir() + "/push_pictures"; }

    void writePicture(const std::string &name)
    {
        ::mkdir(pushPicturesDir().c_str(), 0755);
        std::ofstream f((pushPicturesDir() + "/" + name).c_str());
        f << "jpegdata";
    }
};

TEST_F(JsonApiConfigTest, CheckCredentialsUsesTheConfiguredUser)
{
    //local_config.xml is seeded with a cn_user/cn_pass pair, which takes
    //precedence over calaos_user/calaos_password
    Utils::del_config_option("cn_user");
    Utils::del_config_option("cn_pass");

    Utils::set_config_option("calaos_user", "admin");
    Utils::set_config_option("calaos_password", "s3cr3t");

    EXPECT_TRUE(JsonApi::checkCredentials("admin", "s3cr3t"));
    EXPECT_FALSE(JsonApi::checkCredentials("admin", "s3cr3T"));
    EXPECT_FALSE(JsonApi::checkCredentials("admi", "s3cr3t"));
    EXPECT_FALSE(JsonApi::checkCredentials("admin", "s3cr3"));
    EXPECT_FALSE(JsonApi::checkCredentials("", ""));
}

TEST_F(JsonApiConfigTest, CheckCredentialsPrefersTheCalaosNetworkAccount)
{
    Utils::set_config_option("calaos_user", "admin");
    Utils::set_config_option("calaos_password", "s3cr3t");
    Utils::set_config_option("cn_user", "cnuser");
    Utils::set_config_option("cn_pass", "cnpass");

    EXPECT_TRUE(JsonApi::checkCredentials("cnuser", "cnpass"));
    EXPECT_FALSE(JsonApi::checkCredentials("admin", "s3cr3t"));

    Utils::del_config_option("cn_user");
    Utils::del_config_option("cn_pass");
}

TEST_F(JsonApiConfigTest, EventPictureResolvesAnExistingUid)
{
    writePicture("abcd1234.jpg");

    std::string out;
    ASSERT_TRUE(JsonApi::resolveEventPicture("abcd1234", out));
    EXPECT_NE(out.find("/push_pictures/abcd1234.jpg"), std::string::npos) << out;
    EXPECT_TRUE(FileUtils::exists(out));
}

TEST_F(JsonApiConfigTest, EventPictureRejectsPathTraversal)
{
    writePicture("abcd1234.jpg");

    //A file the api must never serve, one level above the cache directory
    std::ofstream secret((cacheDir() + "/secret.jpg").c_str());
    secret << "secret";
    secret.close();

    std::string out;

    EXPECT_FALSE(JsonApi::resolveEventPicture("../secret", out));
    EXPECT_TRUE(out.empty());

    EXPECT_FALSE(JsonApi::resolveEventPicture("../../../../../../etc/passwd", out));
    EXPECT_FALSE(JsonApi::resolveEventPicture("sub/../../secret", out));
    EXPECT_FALSE(JsonApi::resolveEventPicture("/etc/passwd", out));
    EXPECT_FALSE(JsonApi::resolveEventPicture(std::string("abcd1234\0/../secret", 19), out));
    EXPECT_FALSE(JsonApi::resolveEventPicture("", out));
    //Unknown uid, no information about the filesystem is given back
    EXPECT_FALSE(JsonApi::resolveEventPicture("doesnotexist", out));
}
