/******************************************************************************
 **  Copyright (c) 2006-2025, Calaos. All Rights Reserved.
 **
 **  This file is part of Calaos.
 **
 **  Calaos is free software; you can redistribute it and/or modify
 **  it under the terms of the GNU General Public License as published by
 **  the Free Software Foundation; either version 3 of the License, or
 **  (at your option) any later version.
 **
 **  Calaos is distributed in the hope that it will be useful,
 **  but WITHOUT ANY WARRANTY; without even the implied warranty of
 **  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 **  GNU General Public License for more details.
 **
 **  You should have received a copy of the GNU General Public License
 **  along with Foobar; if not, write to the Free Software
 **  Foundation, Inc., 51 Franklin St, Fifth Floor, Boston, MA  02110-1301  USA
 **
 ******************************************************************************/
/*******************************************************************************
 * E4.0a - the foundation of the JSON API characterization net, proven end to
 * end.
 *
 * This file is NOT the characterization campaign. E4.0b..E4.0f are. What it
 * has to demonstrate is that every mechanism of the harness works against the
 * real production code, so the five sub-tickets can start on it without
 * re-litigating anything:
 *
 *   - the semantic oracle behaves as specified (key order blind, array order
 *     significant, strict on types),
 *   - a golden file round trips: generated by the code, compared semantically,
 *   - a plain WS command answers a full payload (get_home),
 *   - a WS command with a second level of dispatch reaches its sub-handler
 *     (audio / audio_action),
 *   - the error and silence paths are observable (unknown action, unknown
 *     autoscenario type, command before login),
 *   - E4.6e: the autoscenario dispatch itself - routing, service scope and
 *     unknown sub-commands - in a section of its own at the end of the file,
 *   - the HTTP transport is drivable with a real HttpClient built on an
 *     unconnected socket, headers included,
 *   - events are delivered once, and only once, the uvw loop is pumped.
 *
 * Everything here records the behaviour that exists today. One case still pins
 * what is, unambiguously, a production bug (the "unkown audio_action" typo),
 * frozen on purpose: fixing a behaviour while characterizing it destroys the
 * reference. The autoscenario silence was the second one; E4.6e flipped it.
 ******************************************************************************/

#include "JsonApiCharacterization.h"

#include "EventManager.h"
#include "ListeRoom.h"

//EXPECT_NONFATAL_FAILURE. The assertions this harness ships must be proven to
//FAIL when they should, not only to pass when they should.
#include "gtest/gtest-spi.h"

using namespace Calaos;
using namespace CalaosTest;

class JsonApiCharacterizationTestSuite: public JsonApiCharacterizationTest
{
};

/*******************************************************************************
 * The oracle itself. Executable specification of the comparison contract: if
 * one of these ever fails, every golden in the series became meaningless.
 ******************************************************************************/

TEST_F(JsonApiCharacterizationTestSuite, OracleIsBlindToKeyOrder)
{
    //jansson emits insertion order, nlohmann emits sorted keys, and the user
    //has already accepted the change. The tree even emits the WS envelope in
    //two different orders today depending on the sendJson() overload.
    EXPECT_JSON_EQ(std::string(R"({"msg":"get_home","msg_id":"1","data":{"a":"b"}})"),
                   std::string(R"({"data":{"a":"b"},"msg_id":"1","msg":"get_home"})"));
}

TEST_F(JsonApiCharacterizationTestSuite, OracleIsStrictOnTypes)
{
    //"3" is not 3. The whole API is stringified today; a migration that
    //"improves" a stringified number into a JSON number must break the net.
    const Json stringy = Json::parse(R"({"type":"3"})");
    const Json numeric = Json::parse(R"({"type":3})");

    EXPECT_NE(stringy, numeric);
    EXPECT_FALSE(firstJsonDifference(stringy, numeric).empty());
    EXPECT_NE(std::string::npos, firstJsonDifference(stringy, numeric).find("/type"));
}

TEST_F(JsonApiCharacterizationTestSuite, OracleKeepsArrayOrderSignificant)
{
    //Room, IO and rule order drives evaluation order (invariant of the E4.2
    //series). Never sort an array before comparing.
    const Json a = Json::parse(R"({"home":[{"name":"A"},{"name":"B"}]})");
    const Json b = Json::parse(R"({"home":[{"name":"B"},{"name":"A"}]})");

    EXPECT_FALSE(firstJsonDifference(a, b).empty());
    EXPECT_NE(std::string::npos, firstJsonDifference(a, b).find("/home/0/name"));
}

TEST_F(JsonApiCharacterizationTestSuite, OracleReportsThePathOfTheFirstDivergence)
{
    //A raw EXPECT_EQ on a 200 key object is unusable during a migration. The
    //assertion has to say WHERE.
    const Json expected = Json::parse(
        R"({"home":[{"items":[{"id":"a","state":"true"},{"id":"b","state":"false"}]}]})");
    const Json actual = Json::parse(
        R"({"home":[{"items":[{"id":"a","state":"true"},{"id":"b","state":"true"}]}]})");

    const std::string diff = firstJsonDifference(expected, actual);
    EXPECT_NE(std::string::npos, diff.find("/home/0/items/1/state")) << diff;
}

TEST_F(JsonApiCharacterizationTestSuite, OracleReportsAMissingAndAnExtraKey)
{
    const Json expected = Json::parse(R"({"a":"1","b":"2"})");
    const Json missing = Json::parse(R"({"a":"1"})");
    const Json extra = Json::parse(R"({"a":"1","b":"2","c":"3"})");

    EXPECT_NE(std::string::npos, firstJsonDifference(expected, missing).find("/b"));
    EXPECT_NE(std::string::npos, firstJsonDifference(expected, extra).find("/c"));
}

/*******************************************************************************
 * NEGATIVE tests of the assertions themselves.
 *
 * The five cases above exercise firstJsonDifference() directly. That is NOT
 * enough: what the five sub-tickets will actually write is EXPECT_JSON_EQ and
 * EXPECT_JSON_GOLDEN, and a misplaced AssertionSuccess() in either wrapper
 * would leave the whole series green forever - including a mutation run, which
 * would only be caught if it happened to go through the other wrapper.
 *
 * So every macro this harness exports is proven here to FAIL, on the right
 * input, with the right message. EXPECT_NONFATAL_FAILURE swallows the failure
 * and asserts that exactly one occurred and that its text contains the given
 * substring.
 *
 * gtest constraint: the statement inside EXPECT_NONFATAL_FAILURE must not
 * reference local non-static variables, hence the literals everywhere.
 ******************************************************************************/

TEST_F(JsonApiCharacterizationTestSuite, NegativeExpectJsonEqFailsOnADifferentValue)
{
    EXPECT_NONFATAL_FAILURE(
        EXPECT_JSON_EQ(std::string(R"({"a":"1"})"), std::string(R"({"a":"2"})")),
        "/a");
}

TEST_F(JsonApiCharacterizationTestSuite, NegativeExpectJsonEqFailsOnAStringVersusANumber)
{
    //The single most valuable negative: if this ever stops failing, the whole
    //"everything is stringified" contract stops being pinned.
    EXPECT_NONFATAL_FAILURE(
        EXPECT_JSON_EQ(std::string(R"({"type":"3"})"), std::string(R"({"type":3})")),
        "/type");
}

TEST_F(JsonApiCharacterizationTestSuite, NegativeExpectJsonEqFailsOnArrayOrder)
{
    EXPECT_NONFATAL_FAILURE(
        EXPECT_JSON_EQ(std::string(R"({"h":[{"n":"A"},{"n":"B"}]})"),
                       std::string(R"({"h":[{"n":"B"},{"n":"A"}]})")),
        "/h/0/n");
}

TEST_F(JsonApiCharacterizationTestSuite, NegativeExpectJsonEqFailsOnAMissingKey)
{
    EXPECT_NONFATAL_FAILURE(
        EXPECT_JSON_EQ(std::string(R"({"a":"1","b":"2"})"), std::string(R"({"a":"1"})")),
        "key missing from actual");
}

TEST_F(JsonApiCharacterizationTestSuite, NegativeExpectJsonEqFailsOnAnExtraKey)
{
    EXPECT_NONFATAL_FAILURE(
        EXPECT_JSON_EQ(std::string(R"({"a":"1"})"), std::string(R"({"a":"1","b":"2"})")),
        "unexpected key in actual");
}

TEST_F(JsonApiCharacterizationTestSuite, NegativeExpectJsonEqFailsOnUnparsableInput)
{
    //A payload that is not JSON at all must fail loudly, not compare equal to
    //something by accident.
    EXPECT_NONFATAL_FAILURE(
        EXPECT_JSON_EQ(std::string("{}"), std::string("this is not json")),
        "is not parsable JSON");
}

TEST_F(JsonApiCharacterizationTestSuite, NegativeExpectJsonGoldenFailsOnADivergentPayload)
{
    //In update mode the macro WRITES instead of comparing: it would overwrite
    //ws_get_home.json with this deliberately wrong payload.
    if (goldenUpdateModeEnabled())
        GTEST_SKIP() << "negative golden cases would corrupt the goldens in update mode";

    //Against a golden that really exists, so this proves the comparison branch
    //of goldenCompare() and not just its file handling.
    EXPECT_NONFATAL_FAILURE(
        EXPECT_JSON_GOLDEN("ws_get_home", std::string(R"({"msg":"get_home"})")),
        "diverges from golden");
}

TEST_F(JsonApiCharacterizationTestSuite, NegativeExpectJsonGoldenFailsOnAMissingGoldenFile)
{
    if (goldenUpdateModeEnabled())
        GTEST_SKIP() << "would create a stray golden file in update mode";

    //A sub-ticket that forgets to generate its golden must be told so, not
    //silently pass.
    EXPECT_NONFATAL_FAILURE(
        EXPECT_JSON_GOLDEN("e40_this_golden_does_not_exist", std::string("{}")),
        "not found");
}

TEST_F(JsonApiCharacterizationTestSuite, NegativeExpectJsonGoldenFailsOnUnparsablePayload)
{
    if (goldenUpdateModeEnabled())
        GTEST_SKIP() << "negative golden cases would corrupt the goldens in update mode";

    EXPECT_NONFATAL_FAILURE(
        EXPECT_JSON_GOLDEN("ws_get_home", std::string("this is not json")),
        "is not parsable JSON");
}

/*******************************************************************************
 * A plain command, full payload, against a versioned golden.
 ******************************************************************************/

TEST_F(JsonApiCharacterizationTestSuite, WsGetHomeMatchesGolden)
{
    loadReferenceHouse();

    WsTestSession ws;
    ws.send(Json{{ "msg", "get_home" }, { "msg_id", "42" }});

    ASSERT_EQ(1u, ws.count());
    EXPECT_JSON_GOLDEN("ws_get_home", ws.lastMessage());
}

TEST_F(JsonApiCharacterizationTestSuite, WsGetHomeEnvelopeCarriesTheMsgId)
{
    loadReferenceHouse();

    WsTestSession ws;
    ws.send(Json{{ "msg", "get_home" }, { "msg_id", "42" }});

    ASSERT_EQ(1u, ws.count());
    const Json env = ws.lastEnvelope();
    ASSERT_TRUE(env.is_object());
    EXPECT_EQ("get_home", env.value("msg", std::string()));
    EXPECT_EQ("42", env.value("msg_id", std::string()));
    ASSERT_TRUE(env.contains("data"));
    //get_home answers three top level members, always present, even empty.
    EXPECT_TRUE(env["data"].contains("home"));
    EXPECT_TRUE(env["data"].contains("cameras"));
    EXPECT_TRUE(env["data"].contains("audio"));
}

TEST_F(JsonApiCharacterizationTestSuite, WsGetHomeKeepsRoomAndIoOrder)
{
    loadReferenceHouse();

    WsTestSession ws;
    ws.send(Json{{ "msg", "get_home" }, { "msg_id", "1" }});

    ASSERT_EQ(1u, ws.count());
    const Json home = ws.lastEnvelope()["data"]["home"];
    ASSERT_TRUE(home.is_array());
    ASSERT_EQ(3u, home.size());
    EXPECT_EQ(HOUSE_ROOM1_NAME, home[0].value("name", std::string()));
    EXPECT_EQ(HOUSE_ROOM2_NAME, home[1].value("name", std::string()));
    EXPECT_EQ(HOUSE_ROOM3_NAME, home[2].value("name", std::string()));

    const Json items = home[0]["items"];
    ASSERT_EQ(4u, items.size());
    EXPECT_EQ(HOUSE_BOOL_IN, items[0].value("id", std::string()));
    EXPECT_EQ(HOUSE_BOOL_OUT, items[1].value("id", std::string()));
    EXPECT_EQ(HOUSE_INT, items[2].value("id", std::string()));
    EXPECT_EQ(HOUSE_STRING, items[3].value("id", std::string()));
}

TEST_F(JsonApiCharacterizationTestSuite, NonAsciiSurvivesTheEscapingDifference)
{
    //jansson dumps with JSON_ENSURE_ASCII, so the wire carries É escapes;
    //nlohmann writes raw UTF-8. Parsing dissolves the difference, which is why
    //the oracle can be semantic. This is the case that proves it, and it is
    //migration stable: it asserts the VALUE after parsing, nothing about bytes.
    loadReferenceHouse();

    WsTestSession ws;
    ws.send(Json{{ "msg", "get_home" }, { "msg_id", "1" }});

    ASSERT_EQ(1u, ws.count());

    const Json items = ws.lastEnvelope()["data"]["home"][1]["items"];
    ASSERT_EQ(1u, items.size());
    EXPECT_EQ("\xc3\x89" "clairage caf\xc3\xa9", items[0].value("name", std::string()));
}

TEST_F(JsonApiCharacterizationTestSuite, WsGetHomeCarriesTheCameraAndAudioArrays)
{
    //buildJsonCameras() and buildJsonAudio() filter ListeRoom's caches by
    //dynamic_cast. With an empty house both answer [] and neither the filter
    //nor the payload shape gets characterized - which is why the reference
    //house carries two real cameras and one real player.
    loadReferenceHouse();

    WsTestSession ws;
    ws.send(Json{{ "msg", "get_home" }, { "msg_id", "1" }});

    ASSERT_EQ(1u, ws.count());
    const Json data = ws.lastData();

    const Json cameras = data["cameras"];
    ASSERT_TRUE(cameras.is_array());
    ASSERT_EQ(2u, cameras.size());
    EXPECT_EQ(HOUSE_CAMERA_PTZ, cameras[0].value("id", std::string()));
    //both branches of the ptz capability, and it is a STRING, not a bool
    EXPECT_EQ("true", cameras[0].value("ptz", std::string()));
    EXPECT_EQ(HOUSE_CAMERA_PLAIN, cameras[1].value("id", std::string()));
    EXPECT_EQ("false", cameras[1].value("ptz", std::string()));

    const Json audio = data["audio"];
    ASSERT_TRUE(audio.is_array());
    ASSERT_EQ(1u, audio.size());
    EXPECT_EQ(HOUSE_PLAYER, audio[0].value("id", std::string()));
    EXPECT_EQ("false", audio[0].value("playlist", std::string()));
    EXPECT_EQ("false", audio[0].value("database", std::string()));
    //"avr" is emitted only when the player has an "amp" param
    EXPECT_EQ("e40_avr", audio[0].value("avr", std::string()));
}

TEST_F(JsonApiCharacterizationTestSuite, CamerasAndPlayersAreNotVisibleRoomItems)
{
    //IPCam and AudioPlayer force visible=false in their constructors, but they
    //still appear in their room's items array. Pinned because it is exactly the
    //kind of thing a migration could shift without anyone noticing.
    loadReferenceHouse();

    WsTestSession ws;
    ws.send(Json{{ "msg", "get_home" }, { "msg_id", "1" }});

    ASSERT_EQ(1u, ws.count());
    const Json items = ws.lastEnvelope()["data"]["home"][2]["items"];
    ASSERT_EQ(3u, items.size());
    EXPECT_EQ(HOUSE_CAMERA_PTZ, items[0].value("id", std::string()));
    EXPECT_EQ("false", items[0].value("visible", std::string()));
    EXPECT_EQ("camera", items[0].value("gui_type", std::string()));
    EXPECT_EQ(HOUSE_PLAYER, items[2].value("id", std::string()));
    EXPECT_EQ("audio_player", items[2].value("gui_type", std::string()));
}

/*******************************************************************************
 *  ###  EXPECTED TO GO RED DURING E4.1. DO NOT TREAT AS A REGRESSION.  ###
 *
 * This is the ONE case of the whole E4.0 series that looks at raw bytes on the
 * wire instead of at parsed values, and it is deliberate.
 *
 * It pins jansson's JSON_ENSURE_ASCII (Jansson_Addition.h:115): today every non
 * ASCII character leaves the server as a \uXXXX escape. nlohmann::dump() writes
 * raw UTF-8 instead. So the day E4.1 swaps the library, THIS CASE TURNS RED
 * WHILE NOTHING IS BROKEN - the user already accepted the change, and the
 * semantic test just above proves clients receive the same string either way.
 *
 * It exists because the swap must be NOTICED and acknowledged, not slipped in:
 * anything reading the socket byte-wise (a proxy, a log grepper, a non-UTF8
 * client) sees a different stream. It is the tripwire, not the contract.
 *
 * WHAT E4.1 MUST DO WITH IT: flip the expectation to raw UTF-8 in the same
 * commit that swaps the library, and say so in the commit message. What E4.1
 * must NOT do is chase it as a regression, and what E4.0e must NOT do is copy
 * this pattern - it is the single sanctioned exception.
 *
 * This is also the one place where E4.0.md:405-406 ("the E4.0 binaries pass,
 * assertions and goldens UNCHANGED") does not hold, and that is on purpose.
 ******************************************************************************/
TEST_F(JsonApiCharacterizationTestSuite,
       TRIPWIRE_ExpectedRedInE41_JanssonEnsureAsciiEscapesTheWire)
{
    loadReferenceHouse();

    WsTestSession ws;
    ws.send(Json{{ "msg", "get_home" }, { "msg_id", "1" }});

    ASSERT_EQ(1u, ws.count());

    //jansson writes the hex digits in upper case, hence the normalisation
    std::string wire = ws.lastMessage();
    for (char &c: wire)
        c = (char)::tolower((unsigned char)c);

    EXPECT_NE(std::string::npos, wire.find("\\u00c9"))
            << "If this failed right after the jansson -> nlohmann swap, it is "
               "the EXPECTED tripwire, not a regression. Read the comment above "
               "this test.";
    EXPECT_EQ(std::string::npos, ws.lastMessage().find("\xc3\x89"))
            << "If this failed right after the jansson -> nlohmann swap, it is "
               "the EXPECTED tripwire, not a regression. Read the comment above "
               "this test.";
}

/*******************************************************************************
 * The HTTP transport, driven through a real HttpClient on an unconnected
 * socket. This is the measurement that settles point (b) of E4.0.md.
 ******************************************************************************/

TEST_F(JsonApiCharacterizationTestSuite, HttpGetHomeMatchesGolden)
{
    loadReferenceHouse();

    HttpTestRequest req;
    req.send(authenticated(Json{{ "action", "get_home" }}));

    ASSERT_EQ(1u, req.count());
    EXPECT_JSON_GOLDEN("http_get_home", req.body());
}

TEST_F(JsonApiCharacterizationTestSuite, HttpSuccessResponseHeaders)
{
    loadReferenceHouse();

    HttpTestRequest req;
    req.send(authenticated(Json{{ "action", "get_home" }}));

    ASSERT_EQ(1u, req.count());
    EXPECT_EQ("HTTP/1.0 200 OK", req.statusLine());
    EXPECT_EQ("application/json", req.header("Content-Type"));
    EXPECT_EQ("Close", req.header("Connection"));
    EXPECT_EQ("no-cache, must-revalidate", req.header("Cache-Control"));
    EXPECT_EQ(req.body().size(), (size_t)std::stoul(req.header("Content-Length")));
}

TEST_F(JsonApiCharacterizationTestSuite, HttpAndWsAgreeOnTheGetHomePayload)
{
    //The HTTP body is, by construction, the dump of the same object the WS
    //envelope carries under "data". Pinning that equality is what lets the
    //other sub-tickets characterize a payload once instead of twice.
    loadReferenceHouse();

    WsTestSession ws;
    ws.send(Json{{ "msg", "get_home" }, { "msg_id", "1" }});
    ASSERT_EQ(1u, ws.count());

    HttpTestRequest req;
    req.send(authenticated(Json{{ "action", "get_home" }}));
    ASSERT_EQ(1u, req.count());

    EXPECT_JSON_EQ(ws.lastData(), req.bodyJson());
}

/*******************************************************************************
 * Second level of dispatch, and the error paths.
 ******************************************************************************/

TEST_F(JsonApiCharacterizationTestSuite, WsAudioReachesItsSubDispatch)
{
    //Frozen as is, typo included: production answers "unkown audio_action".
    loadReferenceHouse();

    WsTestSession ws;
    ws.send(Json{{ "msg", "audio" },
                 { "msg_id", "7" },
                 { "data", {{ "audio_action", "no_such_sub_action" }} }});

    ASSERT_EQ(1u, ws.count());
    EXPECT_JSON_EQ(std::string(R"({"msg":"audio","msg_id":"7",)"
                               R"("data":{"error":"unkown audio_action"}})"),
                   ws.lastMessage());
}

TEST_F(JsonApiCharacterizationTestSuite, WsAutoscenarioWithUnknownTypeIsAnError)
{
    //FLIPPED BY E4.6e (D8). This case pinned the silence: no else branch, no
    //answer, and a client waiting forever. The sub-dispatch now answers like
    //the audio one two cases above, and the connection is not closed - an
    //unknown sub-command is a bad request, not a broken session.
    loadReferenceHouse();

    WsTestSession ws;
    ws.send(Json{{ "msg", "autoscenario" },
                 { "msg_id", "8" },
                 { "data", {{ "type", "no_such_type" }} }});

    ASSERT_EQ(1u, ws.count());
    EXPECT_JSON_EQ(std::string(R"({"msg":"autoscenario","msg_id":"8",)"
                               R"("data":{"error":"unknown autoscenario type"}})"),
                   ws.lastMessage());
    EXPECT_TRUE(ws.closes().empty());

    //and nothing is queued behind it
    ws.clear();
    pumpEventLoop();
    EXPECT_EQ(0u, ws.count()) << "late answer: " << ws.lastMessage();
}

TEST_F(JsonApiCharacterizationTestSuite, WsIgnoresEverythingBeforeLogin)
{
    //Anything but login/login_service falls through the `else if (loggedin)`
    //and produces no answer at all.
    loadReferenceHouse();

    WsTestSession ws(false /*authenticated*/);
    ws.send(Json{{ "msg", "get_home" }, { "msg_id", "1" }});

    EXPECT_EQ(0u, ws.count()) << "expected silence, got: " << ws.lastMessage();
}

TEST_F(JsonApiCharacterizationTestSuite, WsIgnoresANonObjectPayload)
{
    loadReferenceHouse();

    WsTestSession ws;
    ws.send(std::string("this is not json at all"));
    ws.send(std::string("[1,2,3]"));

    EXPECT_EQ(0u, ws.count()) << "expected silence, got: " << ws.lastMessage();
}

TEST_F(JsonApiCharacterizationTestSuite, HttpUnknownActionIsAnError)
{
    loadReferenceHouse();

    HttpTestRequest req;
    req.send(authenticated(Json{{ "action", "no_such_action" }}));

    ASSERT_EQ(1u, req.count());
    EXPECT_EQ("HTTP/1.0 200 OK", req.statusLine());
    EXPECT_JSON_EQ(std::string(R"({"error":"unknown action"})"), req.body());
}

TEST_F(JsonApiCharacterizationTestSuite, HttpWrongCredentialsGetA400AndACloseRequest)
{
    //sendLoginFailed() dereferences httpClient without a guard: this case is
    //the proof that a real HttpClient on an unconnected socket is enough to
    //characterize the HTTP side, error paths included.
    loadReferenceHouse();

    HttpTestRequest req;
    req.send(Json{{ "action", "get_home" },
                  { "cn_user", "wrong" },
                  { "cn_pass", "wrong" }});

    ASSERT_EQ(1u, req.count());
    EXPECT_EQ("HTTP/1.0 400 Bad Request", req.statusLine());
    EXPECT_EQ("text/html", req.header("Content-Type"));
    ASSERT_EQ(1u, req.closes().size());
    EXPECT_EQ(0, req.closes().front().first);
}

TEST_F(JsonApiCharacterizationTestSuite, HttpNonJsonBodyWithoutGetParamsIsRejected)
{
    //No JSON and no usable GET parameters: credentials are empty, so the
    //request never even reaches the dispatch table.
    loadReferenceHouse();

    HttpTestRequest req;
    req.send(std::string("not json"));

    ASSERT_EQ(1u, req.count());
    EXPECT_EQ("HTTP/1.0 400 Bad Request", req.statusLine());
}

TEST_F(JsonApiCharacterizationTestSuite, HttpAcceptsCredentialsFromGetParameters)
{
    //The GET parameter fallback (JsonApiHandlerHttp.cpp:81-90) is a documented
    //entry point of the HTTP API, and the only way to reach the 400 of the
    //`else` branch with valid credentials.
    loadReferenceHouse();

    Params getParams;
    getParams.Add("cn_user", apiUser());
    getParams.Add("cn_pass", apiPassword());
    getParams.Add("action", "get_home");

    HttpTestRequest req;
    req.send(std::string("not json"), getParams);

    ASSERT_EQ(1u, req.count());
    EXPECT_EQ("HTTP/1.0 200 OK", req.statusLine());
    EXPECT_TRUE(req.bodyJson().contains("home"));
}

/*******************************************************************************
 * Events. E4.0d owns the campaign; what is proven here is the pump, which
 * settles point (c) of E4.0.md.
 ******************************************************************************/

TEST_F(JsonApiCharacterizationTestSuite, EventsAreOnlyDeliveredOnceTheLoopIsPumped)
{
    loadReferenceHouse();

    WsTestSession ws;

    Params p;
    p.Add("state", "true");
    EventManager::create(CalaosEvent::EventIOChanged, HOUSE_BOOL_IN, p,
                         false /*logHistory*/);

    //EventManager queues into a uvw Idler. Without a loop iteration the queue
    //simply grows and nothing is ever delivered - exactly what
    //CalaosCoreFixture.h warns about.
    ASSERT_EQ(0u, ws.count());

    pumpEventLoop();

    ASSERT_EQ(1u, ws.count());
    const Json env = ws.lastEnvelope();
    EXPECT_EQ("event", env.value("msg", std::string()));
    //push events are unsolicited: no msg_id
    EXPECT_FALSE(env.contains("msg_id"));
    ASSERT_TRUE(env.contains("data"));
    EXPECT_EQ("io_changed", env["data"].value("type_str", std::string()));
    //every value is a string, the enum is stringified
    EXPECT_TRUE(env["data"]["type"].is_string());
    EXPECT_EQ(HOUSE_BOOL_IN, env["data"]["data"].value("id", std::string()));
}

TEST_F(JsonApiCharacterizationTestSuite, EventsAreNotDeliveredToASessionThatIsNotLoggedIn)
{
    loadReferenceHouse();

    WsTestSession ws(false /*authenticated*/);

    Params p;
    p.Add("state", "true");
    EventManager::create(CalaosEvent::EventIOChanged, HOUSE_BOOL_IN, p, false);

    pumpEventLoop();

    EXPECT_EQ(0u, ws.count()) << "expected silence, got: " << ws.lastMessage();
}

/*******************************************************************************
 * E4.6e - the autoscenario dispatch itself: routing, service scope, unknown
 * sub-commands.
 *
 * The two handlers own this dispatch and nothing else does. Everything below
 * is asserted on BOTH transports where both have a path, because the two
 * dispatchers are separate code reading the sub-command from different places
 * (WS under "data", HTTP at the root) - an assertion on one proves nothing
 * about the other.
 *
 * ROUTING WITNESS. EachAutoscenarioSubCommandReachesItsOwnBuilder gives each
 * of the eight sub-commands an observable no other one produces, and drives
 * them in an order where every step depends on the previous. Two of the eight
 * answer the same bytes ({"success":"true"} for delete and del_schedule), so
 * the witness is the EFFECT, not the payload: swapping any two entries of the
 * routing table leaves the scenario in a state the sequence refuses.
 ******************************************************************************/

namespace
{

const char E46E_ROOM_NAME[] = "E4.6e room";
const char E46E_ROOM_TYPE[] = "salon";

//Prefixed and used nowhere else: Config's IO state cache is process wide and
//never cleared (CalaosCoreFixture.h).
const char E46E_BOOL[] = "e46e_bool";
const char E46E_INT[] = "e46e_int";
const char E46E_STRING[] = "e46e_string";

//The eight sub-commands, in dispatch order.
const char *const AUTOSCENARIO_SUBCOMMANDS[] =
{ "list", "get", "create", "delete", "modify", "add_schedule", "del_schedule",
  "reenable" };

} //namespace

class JsonApiAutoscenarioDispatchTest: public JsonApiCharacterizationTest
{
protected:
    /* A house of its own: the reference house carries no room the scenario
     * payload can name, and dragging its two cameras and its Roon player
     * through a create/delete sequence buys nothing.
     */
    void loadScenarioHouse()
    {
        std::string ios;
        ios += internalIoXml("InternalBool", E46E_BOOL, "Bool value");
        ios += internalIoXml("InternalInt", E46E_INT, "Int value");
        ios += internalIoXml("InternalString", E46E_STRING, "String value");

        loadConfig(ioXmlDocument(roomXml(E46E_ROOM_NAME, E46E_ROOM_TYPE, ios)),
                   rulesXmlDocument(std::string()));

        //The load queues one EventIOAdded per IO; drain them so the silence
        //cases below observe their own absence and not this backlog.
        pumpEventLoop();
    }

    static Json wsRequest(const std::string &type, Json data = Json::object(),
                          const std::string &msgId = "e46e")
    {
        if (!type.empty()) data["type"] = type;
        return Json{{ "msg", "autoscenario" }, { "msg_id", msgId }, { "data", data }};
    }

    static Json httpRequest(const std::string &type, Json body = Json::object())
    {
        body["action"] = "autoscenario";
        if (!type.empty()) body["type"] = type;
        return authenticated(body);
    }

    //Sends one sub-command over WS and answers the "data" member of the single
    //reply. Fails the calling case when the reply count is not exactly one.
    Json wsAutoscenario(WsTestSession &ws, const std::string &type,
                        Json data = Json::object())
    {
        ws.clear();
        ws.send(wsRequest(type, data));
        EXPECT_EQ(1u, ws.count()) << "autoscenario " << type << " answered "
                                  << ws.count() << " messages";
        if (ws.count() != 1) return Json::object();
        return ws.lastData();
    }

    /* The definition create and modify share. Two standard steps with
     * different pauses and different targets, plus a final step: a payload
     * where every sub-command that rewrites it has something to move.
     */
    static Json definitionPayload(const std::string &name)
    {
        return Json{
            { "name", name },
            { "room_name", E46E_ROOM_NAME },
            { "room_type", E46E_ROOM_TYPE },
            { "steps", Json::array({
                 Json{{ "pause", "1.5" },
                      { "actions", Json::array({
                            Json{{ "io", E46E_BOOL }, { "value", "true" }} }) }},
                 Json{{ "pause", "0.25" },
                      { "actions", Json::array({
                            Json{{ "io", E46E_INT }, { "value", "42" }} }) }} }) },
            { "final_step", Json{{ "actions", Json::array({
                            Json{{ "io", E46E_STRING }, { "value", "done" }} }) }} }};
    }

    std::string createScenario(WsTestSession &ws, const std::string &name)
    {
        return wsAutoscenario(ws, "create", definitionPayload(name))
                .value("id", std::string());
    }

    static bool ioExists(const std::string &id)
    {
        return ListeRoom::Instance().get_io(id) != nullptr;
    }

    static std::string scenarioName(const Json &getPayload)
    {
        return getPayload.value("name", std::string());
    }
};

/*******************************************************************************
 * The routing table. PROVE, DO NOT FLIP.
 ******************************************************************************/

TEST_F(JsonApiAutoscenarioDispatchTest, EachAutoscenarioSubCommandReachesItsOwnBuilder)
{
    loadScenarioHouse();

    WsTestSession ws;

    // create - the only sub-command that makes a scenario appear
    const std::string sid = createScenario(ws, "e46e first");
    ASSERT_FALSE(sid.empty());
    ASSERT_TRUE(ioExists(sid));

    // list - the only answer carrying a "scenarios" array
    Json data = wsAutoscenario(ws, "list");
    ASSERT_TRUE(data.contains("scenarios")) << data.dump();
    ASSERT_TRUE(data["scenarios"].is_array());
    ASSERT_EQ(1u, data["scenarios"].size());
    EXPECT_EQ(sid, data["scenarios"][0].value("id", std::string()));

    // get - the scenario document, named by its own id
    data = wsAutoscenario(ws, "get", Json{{ "id", sid }});
    EXPECT_EQ(sid, data.value("id", std::string()));
    EXPECT_EQ("e46e first", scenarioName(data));
    EXPECT_TRUE(data.contains("final_step")) << data.dump();

    // add_schedule - the only one answering the id of an IO it just built
    data = wsAutoscenario(ws, "add_schedule", Json{{ "id", sid }});
    const std::string scheduleId = data.value("id", std::string());
    ASSERT_FALSE(scheduleId.empty()) << data.dump();
    ASSERT_NE(sid, scheduleId);
    EXPECT_TRUE(ioExists(scheduleId));

    // del_schedule - the schedule IO goes, the scenario stays
    data = wsAutoscenario(ws, "del_schedule", Json{{ "id", sid }});
    EXPECT_JSON_EQ(std::string(R"({"success":"true"})"), data);
    EXPECT_FALSE(ioExists(scheduleId));
    EXPECT_TRUE(ioExists(sid));

    // modify - the only one that rewrites the definition in place
    data = wsAutoscenario(ws, "modify",
                          [&]{ Json p = definitionPayload("e46e renamed");
                               p["id"] = sid; return p; }());
    EXPECT_JSON_EQ(std::string(R"({"success":"true"})"), data);
    EXPECT_EQ("e46e renamed", scenarioName(wsAutoscenario(ws, "get", Json{{ "id", sid }})));

    // reenable - answers on a healthy scenario and changes nothing
    data = wsAutoscenario(ws, "reenable", Json{{ "id", sid }});
    EXPECT_JSON_EQ(std::string(R"({"success":"true"})"), data);
    EXPECT_EQ("e46e renamed", scenarioName(wsAutoscenario(ws, "get", Json{{ "id", sid }})));

    // create again - a SECOND scenario, so delete has a choice to make
    const std::string second = createScenario(ws, "e46e second");
    ASSERT_FALSE(second.empty());
    ASSERT_NE(sid, second);
    ASSERT_EQ(2u, wsAutoscenario(ws, "list")["scenarios"].size());

    // delete - the only sub-command that makes a scenario disappear
    data = wsAutoscenario(ws, "delete", Json{{ "id", second }});
    EXPECT_JSON_EQ(std::string(R"({"success":"true"})"), data);
    EXPECT_FALSE(ioExists(second));
    EXPECT_TRUE(ioExists(sid));
    EXPECT_EQ(1u, wsAutoscenario(ws, "list")["scenarios"].size());
}

TEST_F(JsonApiAutoscenarioDispatchTest, TheHttpDispatcherRoutesTheSameEightSubCommands)
{
    /* The HTTP dispatcher is code of its own and reads "type" from the ROOT
     * object. Deleting one of its branches has already been measured to leave
     * the whole WS side green (T3.18), so each branch is asserted here on this
     * transport, on the answer only: the effects are the WS case's job.
     */
    loadScenarioHouse();

    std::string sid;
    {
        WsTestSession ws;
        sid = createScenario(ws, "e46e http");
        ASSERT_FALSE(sid.empty());
    }

    {
        HttpTestRequest req;
        req.send(httpRequest("list"));
        ASSERT_EQ(1u, req.count());
        ASSERT_TRUE(req.bodyJson().contains("scenarios")) << req.body();
        EXPECT_EQ(1u, req.bodyJson()["scenarios"].size());
    }
    {
        HttpTestRequest req;
        req.send(httpRequest("get", Json{{ "id", sid }}));
        ASSERT_EQ(1u, req.count());
        EXPECT_EQ("e46e http", scenarioName(req.bodyJson()));
    }
    {
        HttpTestRequest req;
        req.send(httpRequest("add_schedule", Json{{ "id", sid }}));
        ASSERT_EQ(1u, req.count());
        EXPECT_FALSE(req.bodyJson().value("id", std::string()).empty()) << req.body();
    }
    {
        HttpTestRequest req;
        req.send(httpRequest("del_schedule", Json{{ "id", sid }}));
        ASSERT_EQ(1u, req.count());
        EXPECT_JSON_EQ(std::string(R"({"success":"true"})"), req.bodyJson());
    }
    {
        Json p = definitionPayload("e46e http renamed");
        p["id"] = sid;
        HttpTestRequest req;
        req.send(httpRequest("modify", p));
        ASSERT_EQ(1u, req.count());
        EXPECT_JSON_EQ(std::string(R"({"success":"true"})"), req.bodyJson());
    }
    {
        HttpTestRequest req;
        req.send(httpRequest("reenable", Json{{ "id", sid }}));
        ASSERT_EQ(1u, req.count());
        EXPECT_JSON_EQ(std::string(R"({"success":"true"})"), req.bodyJson());
    }
    {
        HttpTestRequest req;
        req.send(httpRequest("create", definitionPayload("e46e http second")));
        ASSERT_EQ(1u, req.count());
        EXPECT_FALSE(req.bodyJson().value("id", std::string()).empty()) << req.body();
    }
    {
        HttpTestRequest req;
        req.send(httpRequest("delete", Json{{ "id", sid }}));
        ASSERT_EQ(1u, req.count());
        EXPECT_JSON_EQ(std::string(R"({"success":"true"})"), req.bodyJson());
        EXPECT_FALSE(ioExists(sid));
    }
}

/*******************************************************************************
 * Service scope. >>> TO FLIP (E4.6e, D8) <<<
 ******************************************************************************/

TEST_F(JsonApiAutoscenarioDispatchTest,
       AServiceScopedSessionIsRefusedEveryAutoscenarioSubCommand)
{
    /* FLIPPED BY E4.6e (D8). The gate is on the message, not on the
     * sub-command, so the eight are refused identically - the READ ones
     * included, and that is the visible break: `list` and `get` answered a
     * scoped session until now.
     */
    loadScenarioHouse();

    for (const char *type: AUTOSCENARIO_SUBCOMMANDS)
    {
        WsTestSession ws(true /*authenticated*/, true /*serviceScope*/);
        ws.send(wsRequest(type, Json{{ "id", "e46e_no_such_scenario" }}, "sd"));

        ASSERT_EQ(1u, ws.count()) << type << " answered nothing";
        EXPECT_JSON_EQ(std::string(R"({"msg":"autoscenario","msg_id":"sd",)"
                                   R"("data":{"error":"scope denied"}})"),
                       ws.lastMessage()) << type;
        EXPECT_TRUE(ws.closes().empty()) << type;
    }

    //the contrast, and it is what makes the loop above mean anything: the same
    //requests on a session that is not service scoped still reach the builders
    WsTestSession plain;
    plain.send(wsRequest("list"));
    ASSERT_EQ(1u, plain.count());
    EXPECT_NE("scope denied", str(plain.lastData(), "error"));
}

TEST_F(JsonApiAutoscenarioDispatchTest,
       AServiceScopedSessionIsRefusedBothTheScheduleAndTheScenario)
{
    /* FLIPPED BY E4.6e (D8). The measurement that made D8 a decision rather
     * than a taste: the SAME session, in the SAME state, was refused the time
     * range of the scenario's schedule and allowed to delete the scenario that
     * owns it. Both halves are now refused, and the refusal is a real one -
     * the scenario and its schedule are still there afterwards.
     */
    loadScenarioHouse();

    std::string sid, scheduleId;
    {
        WsTestSession ws;
        sid = createScenario(ws, "e46e scoped");
        ASSERT_FALSE(sid.empty());
        scheduleId = wsAutoscenario(ws, "add_schedule", Json{{ "id", sid }})
                        .value("id", std::string());
        ASSERT_FALSE(scheduleId.empty());
    }

    WsTestSession scoped(true /*authenticated*/, true /*serviceScope*/);

    scoped.send(Json{{ "msg", "set_timerange" }, { "msg_id", "1" },
                     { "data", {{ "id", scheduleId }, { "months", "111111111111" }} }});
    ASSERT_EQ(1u, scoped.count());
    EXPECT_JSON_EQ(std::string(R"({"msg":"set_timerange","msg_id":"1",)"
                               R"("data":{"error":"scope denied"}})"),
                   scoped.lastMessage());

    scoped.clear();
    scoped.send(wsRequest("delete", Json{{ "id", sid }}, "2"));
    ASSERT_EQ(1u, scoped.count());
    EXPECT_JSON_EQ(std::string(R"({"msg":"autoscenario","msg_id":"2",)"
                               R"("data":{"error":"scope denied"}})"),
                   scoped.lastMessage());
    EXPECT_TRUE(ioExists(sid)) << "the refusal has to be a refusal, not a message";
    EXPECT_TRUE(ioExists(scheduleId));
}

/*******************************************************************************
 * Unknown and absent sub-commands. >>> TO FLIP (E4.6e, D8) <<<
 ******************************************************************************/

TEST_F(JsonApiAutoscenarioDispatchTest,
       WsAutoscenarioWithAnUnknownOrAbsentTypeIsAnError)
{
    /* FLIPPED BY E4.6e (D8). Four shapes of "no branch matches", all silent
     * before this ticket and all answered now: an unknown type, an empty one,
     * an absent one, and no "data" member at all. The last two matter as much
     * as the first: jsonStringGet() answers "" for both, so a client that
     * simply forgot the member used to get nothing back either.
     */
    loadScenarioHouse();

    const Json expected = Json{{ "error", "unknown autoscenario type" }};

    WsTestSession ws;

    for (const Json &request: { wsRequest("e46e_not_a_command"),
                                wsRequest("", Json{{ "type", "" }}),
                                wsRequest(""),
                                Json{{ "msg", "autoscenario" }, { "msg_id", "1" }} })
    {
        ws.clear();
        ws.send(request);
        ASSERT_EQ(1u, ws.count()) << request.dump();
        EXPECT_JSON_EQ(expected, ws.lastData()) << request.dump();
        EXPECT_TRUE(ws.closes().empty()) << request.dump();
    }

    //nothing is queued behind the answers
    ws.clear();
    pumpEventLoop();
    EXPECT_EQ(0u, ws.count()) << "late answer: " << ws.lastMessage();
}

TEST_F(JsonApiAutoscenarioDispatchTest,
       HttpAutoscenarioWithAnUnknownTypeAnswersAndReleasesTheSocket)
{
    /* FLIPPED BY E4.6e (D8), and this was the worse half: no response AND no
     * close, so the client held the connection until its own timeout fired.
     * The response itself is what releases it - "Connection: Close" plus a
     * body, exactly like every other error of this transport - so the header
     * is asserted here and not only the payload.
     */
    loadScenarioHouse();

    const Json expected = Json{{ "error", "unknown autoscenario type" }};

    {
        HttpTestRequest unknown;
        unknown.send(httpRequest("e46e_not_a_command"));
        ASSERT_EQ(1u, unknown.count());
        EXPECT_EQ("HTTP/1.0 200 OK", unknown.statusLine());
        EXPECT_EQ("Close", unknown.header("Connection"));
        EXPECT_JSON_EQ(expected, unknown.bodyJson());
    }
    {
        HttpTestRequest absent;
        absent.send(httpRequest(""));
        ASSERT_EQ(1u, absent.count());
        EXPECT_JSON_EQ(expected, absent.bodyJson());
    }
    {
        //A WS shaped request sent to HTTP still addresses nothing - "type"
        //lives under "data" and this dispatcher reads the root - but it is
        //answered instead of hanging.
        HttpTestRequest wsShaped;
        wsShaped.send(authenticated(Json{{ "action", "autoscenario" },
                                         { "data", {{ "type", "list" }} }}));
        ASSERT_EQ(1u, wsShaped.count());
        EXPECT_JSON_EQ(expected, wsShaped.bodyJson());
    }
}
