/******************************************************************************
 **  Copyright (c) 2006-2025, Calaos. All Rights Reserved.
 **
 **  This file is part of Calaos.
 **
 **  Calaos is free software; you can redistribute it and/or modify
 **  it under the terms of the GNU General Public License as published by
 **  the Free Software Foundation; either version 3 of the License, or
 **  (at your option) any later version.
 **
 **  Calaos is distributed in the hope that it will be useful,
 **  but WITHOUT ANY WARRANTY; without even the implied warranty of
 **  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 **  GNU General Public License for more details.
 **
 **  You should have received a copy of the GNU General Public License
 **  along with Foobar; if not, write to the Free Software
 **  Foundation, Inc., 51 Franklin St, Fifth Floor, Boston, MA  02110-1301  USA
 **
 ******************************************************************************/
/*******************************************************************************
 * E4.0c - time ranges and auto scenarios: the nine operations whose payload
 * contracts are the most fragile of the whole API.
 *
 *      get_timerange  set_timerange
 *      autoscenario x7 (list get create delete modify add_schedule del_schedule)
 *
 * Everything goes through the E4.0a harness (tests/core/JsonApiCharacterization.h,
 * read it first): semantic oracle, one golden per case, goldens GENERATED by
 * CALAOS_GOLDEN_UPDATE=1 and never hand written. No serialized JSON string is
 * ever compared here.
 *
 * This file freezes what the code does TODAY, bugs included. It fixes nothing.
 *
 * ---------------------------------------------------------------------------
 * >>> READ THIS FIRST: T3.18 WILL BREAK THIS FILE, ON PURPOSE <<<
 * ---------------------------------------------------------------------------
 * T3.18 (docs/refactoring/T3.18.md, decided, not implemented yet) adds THREE
 * keys to Scenario::toJson() - and to nothing else in the API:
 *
 *      "broken"              live, derived from Rule::isDisabled() over the
 *                            rules of the scenario. Not persisted, not
 *                            forgeable by a client.
 *      "disabled_missing_io" a NEW PERSISTED param of the Scenario IO. Sticky:
 *                            it is only ever set by the detection pass and only
 *                            ever cleared by an explicit user re-enable.
 *      "missing_ios"         the ids that no longer resolve, "id_a, id_b".
 *
 * The two first ones DIVERGE ON PURPOSE. The state broken=false /
 * disabled_missing_io=true - "repaired, waiting for a manual re-enable" - is
 * the whole reason the user asked for T3.18: today that state is
 * INDISTINGUISHABLE from a healthy scenario, so nobody can know there is a
 * button to press. This file pins that indistinguishability while it lasts.
 *
 * WHAT T3.18 HAS TO DO HERE, EXHAUSTIVELY:
 *
 *  1. REGENERATE SEVEN goldens - every one that carries a Scenario::toJson()
 *     payload, and that is ALL of them but the two time range ones:
 *         e40c_ws_autoscenario_get.json
 *         e40c_http_autoscenario_get.json
 *         e40c_ws_autoscenario_get_scheduled.json
 *         e40c_ws_autoscenario_get_hot_deleted.json
 *         e40c_ws_autoscenario_list.json              <- TWO payloads in it:
 *             buildAutoscenarioList() (JsonApi.cpp:1659) calls it->toJson() on
 *             every scenario, so the list moves exactly like a get. Missed by
 *             the first version of this list, caught in review.
 *         e40c_ws_autoscenario_get_broken.json        (broken=true,  flag=true)
 *         e40c_ws_autoscenario_get_repaired.json      (broken=false, flag=true)
 *     The two last are the "unhealthy" goldens T3.18.md asks for. They already
 *     exist here, built from real amputated configurations, so T3.18 has
 *     nothing to stage: it re-runs CALAOS_GOLDEN_UPDATE=1 once and reads the
 *     diff. e40c_ws_autoscenario_get_hot_deleted.json moves TWICE over: for the
 *     three keys, and because the hot delete path stops destroying the step
 *     rule (see the case pinning it).
 *     The repaired fixture goes through a REAL save/reload cycle after the IO
 *     is put back, which is what makes it land on broken=false: the detection
 *     of E4.2e is rebuilt from the file, finds nothing missing, and only the
 *     persisted flag is left. A third case,
 *     PuttingTheIoBackWithoutAReloadLeavesTheRuleDisabledAndThePayloadSilent,
 *     pins the intermediate state (broken stays true, the payload says
 *     nothing) and needs no edit at all: it reads scenarioPayloadKeys().
 *
 *  2. ADD THE THREE KEY NAMES TO scenarioPayloadKeys() BELOW - the single place
 *     in this file that enumerates them - and nowhere else. Every structural
 *     case reads that list, so three strings cover them all.
 *
 *  3. FLIP EXACTLY ONE ASSERTION, and it is named for that:
 *         RepairedScenarioIsIndistinguishableFromAHealthyOneUntilT3_18
 *     It asserts that the payload of a repaired scenario is SEMANTICALLY EQUAL
 *     to the payload of the same scenario before it was ever broken. T3.18
 *     makes them differ by disabled_missing_io (and by missing_ios if the
 *     detection kept the ids). Turn the EXPECT_JSON_EQ into the inequality that
 *     T3.18 is about - concretely: same payload except broken=="false" and
 *     disabled_missing_io=="true" - and say so in the commit message.
 *     It is the ONLY equality of two whole SCENARIO payloads that has to move.
 *     Three other cases compare whole payloads and none of them does:
 *         GetTimerangePayloadIsIdenticalOnBothTransports  - time range payload,
 *         SetTimerangeRoundTripsWhatGetTimerangeAnswered  - time range payload,
 *         AutoscenarioPayloadIsIdenticalOnBothTransports  - both sides gain the
 *             three keys together, so the equality still holds.
 *
 *  4. Two cases keep their MEANING but change their EXPECTED VALUE, and both
 *     say so in a comment at the point of assertion:
 *         DeletingAnIoUsedByAStepDestroysTheWholeStepRule  (step count 2 -> 3,
 *             the rule survives, disabled, instead of being destroyed)
 *         ModifyOfABrokenScenarioLosesTheDeadReferenceForever (the reference
 *             still dies on that round trip - T3.18 does not fix modify - but
 *             missing_ios now tells the user what they are about to lose)
 *
 * Nothing else in E4.0 moves: buildJsonIO() emits a fixed whitelist of 16 keys,
 * so a new param on the Scenario IO is invisible to get_home/get_io/get_state
 * (T3.18.md, constat (f)). The break is confined to this file.
 *
 * ---------------------------------------------------------------------------
 * WHY THE THREE KEYS ARE NOT FROZEN IN ADVANCE - settled, see T3.18.md
 * ---------------------------------------------------------------------------
 * T3.18.md used to instruct a not-yet-delivered E4.0c to "freeze the shape WITH
 * the three keys from the start". That instruction was RETRACTED (T3.18.md, the
 * "Correction (2026-08-16)" section) because it cannot be carried out:
 *  - goldens are GENERATED BY THE CODE (E4.0a), never typed. Production does
 *    not emit those keys, so no run can produce such a golden;
 *  - a hand written golden describing the desirable instead of the existing is
 *    exactly what E4.0's invariants forbid, and it would pass both before AND
 *    after the migration, proving nothing;
 *  - it would leave the CURRENT payload - the one E4.1 is judged against - with
 *    no reference at all, which is the one thing this whole series exists to
 *    prevent;
 *  - and T3.18 lands after T3.17, so this file would have been RED from its
 *    first day and E4.1 would have started without a green net.
 * The present shape is frozen instead, and the break is PREPARED: two unhealthy
 * goldens ready to be regenerated, one key list to extend, one named assertion
 * to flip.
 *
 * ---------------------------------------------------------------------------
 * WHAT THE TWO TRANSPORTS DO NOT AGREE ON - characterized, not fixed
 * ---------------------------------------------------------------------------
 *  - Every operation of this file reads its arguments from a DIFFERENT PLACE
 *    depending on the transport: WS reads the "data" member
 *    (JsonApiHandlerWS.cpp:199, :203, :206), HTTP reads the ROOT object
 *    (JsonApiHandlerHttp.cpp:167, :210, :212). The same document sent to both
 *    does not address the same thing - and for autoscenario it does not even
 *    select the same sub-command, since "type" itself lives there.
 *  - set_timerange is refused to a service-scoped WS session; autoscenario,
 *    which creates, modifies and DELETES scenarios, is not gated at all. HTTP
 *    has no scope notion whatsoever.
 *
 * ---------------------------------------------------------------------------
 * FROZEN BUGS - pinned on purpose, DO NOT FIX HERE
 * ---------------------------------------------------------------------------
 *  - autoscenario with an unknown (or missing) "type" answers NOTHING AT ALL,
 *    on both transports: there is no else branch (JsonApiHandlerWS.cpp:474-491,
 *    JsonApiHandlerHttp.cpp:880-896). Already listed as a known divergence in
 *    JsonApiCharacterization.h; pinned here as a message count of zero.
 *  - A step whose action IO no longer resolves is rendered as an EMPTY STEP,
 *    with no indication of any kind: countRealActions() skips the action
 *    because isScenarioInternalIO(nullptr) answers true (AutoScenario.cpp:706).
 *    This is T3.18.md's constat (d), measured again here.
 *  - The payload of autoscenario get CANNOT BE ECHOED BACK into
 *    autoscenario modify: get emits "enabled", modify reads "disabled", and
 *    get emits neither name, nor visible, nor room. A client replaying what it
 *    received renames the scenario to the localized "New unnamed scenario",
 *    hides it and disables its schedule - silently, with success:true.
 *  - A step list whose "end" step is not last silently drops the actions of
 *    every standard step after it: buildAutoscenarioCreate() uses the index in
 *    the JSON array as the step number (JsonApi.cpp:1743).
 *  - set_timerange drops a range whose "day" is not in 1..7 without a word,
 *    and an empty "ranges" wipes every range of the IO (o->clear() runs first).
 ******************************************************************************/

#include "JsonApiCharacterization.h"

#include "AutoScenario.h"
#include "EventManager.h"
#include "InPlageHoraire.h"
#include "ListeRoom.h"
#include "ListeRule.h"
#include "Rule.h"
#include "Scenario.h"

#include <algorithm>

using namespace Calaos;
using namespace CalaosTest;

namespace
{

/* Ids are e40c_ prefixed and used nowhere else in the tree: Config's IO state
 * cache is process wide and never cleared (CalaosCoreFixture.h), so sharing an
 * id with another test file leaks state between binaries.
 * The scenario IOs themselves are NOT prefixed: their ids are generated by
 * production (get_new_id("io_"), get_new_scenario_id()) and that generation is
 * part of what is characterized. Both scan the CURRENT ListeRoom only, which
 * the fixture empties between cases, so they are deterministic and immune to
 * --gtest_shuffle.
 */
const char E40C_ROOM_NAME[] = "E4.0c room";
const char E40C_ROOM_TYPE[] = "salon";

const char IO_BOOL[] = "e40c_bool";
const char IO_TARGET[] = "e40c_target";      //the one the T3.18 cases amputate
const char IO_INT[] = "e40c_int";
const char IO_STRING[] = "e40c_string";
const char IO_RANGE[] = "e40c_range";        //InPlageHoraire, standalone

//The scenario ids production hands out for the FIRST scenario of a fresh house
const char SCENARIO_IO_ID[] = "io_0";
const char SCENARIO_ID[] = "scenario_0";
const char SCENARIO_SCHEDULE_ID[] = "scenario_0_schedule";

/* A time range with content on three days, deliberately asymmetric on every
 * axis so that no mutation of buildJsonGetTimerange()/TimeRange::toParams() can
 * hide behind a symmetric fixture:
 *   - monday, wednesday and sunday, so the day+1 numbering is pinned at both
 *     ends of the week (1 and 7) and in the middle,
 *   - two ranges on the same day, so the array is not trivially of size one,
 *   - every hour/min/sec member set to a DIFFERENT value, so swapping two of
 *     them in production fails,
 *   - one sunset start with a negative offset and one sunrise end with a
 *     positive one, so start_type/end_type/start_offset/end_offset are all
 *     observed in presence with a non default value,
 *   - months = january, february and december only. All twelve months would
 *     make the std::reverse() of JsonApi.cpp:1580 invisible.
 */
const char MONTHS_JAN_FEB_DEC[] = "110000000001";

std::string timeRangeIoXml()
{
    return std::string()
        + "    <calaos:input type=\"InPlageHoraire\" id=\"" + IO_RANGE + "\""
          " name=\"Plage horaire\" enabled=\"true\" months=\"" + MONTHS_JAN_FEB_DEC + "\">\n"
          "      <calaos:lundi>\n"
          "        <calaos:plage start_type=\"0\" start_hour=\"8\" start_min=\"30\" start_sec=\"15\""
          " end_type=\"0\" end_hour=\"12\" end_min=\"45\" end_sec=\"5\" />\n"
          "        <calaos:plage start_type=\"2\" start_hour=\"1\" start_min=\"20\" start_sec=\"30\""
          " start_offset=\"-1\" end_type=\"0\" end_hour=\"23\" end_min=\"59\" end_sec=\"59\" />\n"
          "      </calaos:lundi>\n"
          "      <calaos:mercredi>\n"
          "        <calaos:plage start_type=\"0\" start_hour=\"6\" start_min=\"0\" start_sec=\"0\""
          " end_type=\"1\" end_hour=\"0\" end_min=\"10\" end_sec=\"20\" end_offset=\"1\" />\n"
          "      </calaos:mercredi>\n"
          "      <calaos:dimanche>\n"
          "        <calaos:plage start_type=\"3\" start_hour=\"2\" start_min=\"3\" start_sec=\"4\""
          " start_offset=\"1\" end_type=\"0\" end_hour=\"21\" end_min=\"22\" end_sec=\"23\" />\n"
          "      </calaos:dimanche>\n"
          "    </calaos:input>\n";
}

std::string houseIosXml()
{
    std::string ios;
    ios += internalIoXml("InternalBool", IO_BOOL, "Bool value");
    ios += internalIoXml("InternalBool", IO_TARGET, "Target of the second step");
    ios += internalIoXml("InternalInt", IO_INT, "Int value");
    ios += internalIoXml("InternalString", IO_STRING, "String value");
    ios += timeRangeIoXml();
    return ios;
}

} //namespace

class JsonApiScenarioTest: public JsonApiCharacterizationTest
{
protected:
    /* A small house of our own instead of loadReferenceHouse().
     * Two measured reasons, not taste:
     *  - the T3.18 cases save the WHOLE configuration to disk, amputate one IO
     *    from io.xml and load it back. Dragging two cameras and a Roon player
     *    through that cycle buys nothing and adds two failure modes;
     *  - the reference house carries no InPlageHoraire and no Scenario at all,
     *    which are the only two IO types this file is about.
     * The reference house is NOT modified: E4.0b's counter-mutation showed how
     * much its deliberate sparseness is worth, and this file has no need to
     * touch it.
     */
    void loadScenarioHouse()
    {
        loadConfig(ioXmlDocument(roomXml(E40C_ROOM_NAME, E40C_ROOM_TYPE, houseIosXml(), 0)),
                   rulesXmlDocument(std::string()));

        //Loading raises one EventIOAdded per IO. They sit in the EventManager
        //queue until something pumps the loop and are then delivered to every
        //live session, so a case pinning the ABSENCE of a message would trip
        //over them. Drain here, exactly like loadReferenceHouse() does.
        pumpEventLoop();
    }

    /* THE ONE PLACE that enumerates the keys of a Scenario::toJson() payload
     * (IO/Scenario.cpp:88-95, :146). T3.18 adds "broken",
     * "disabled_missing_io" and "missing_ios" HERE and nowhere else: every
     * structural assertion of this file reads this list.
     */
    static std::vector<std::string> scenarioPayloadKeys()
    {
        return { "id", "cycle", "enabled", "schedule", "category",
                 //T3.18, the three keys. "broken" is live (Rule::isDisabled()
                 //over the rules of the scenario), "disabled_missing_io" is the
                 //persisted sticky flag, and they DIVERGE on purpose.
                 "broken", "disabled_missing_io", "missing_ios",
                 "steps_count", "steps" };
    }

    /* The eleven keys of TimeRange::toParams() (src/lib/TimeRange.cpp:425-443),
     * same role for the time range payload.
     */
    static std::vector<std::string> timeRangePayloadKeys()
    {
        return { "day",
                 "start_hour", "start_min", "start_sec", "start_type", "start_offset",
                 "end_hour", "end_min", "end_sec", "end_type", "end_offset" };
    }

    //Every leaf of the document must be a JSON string: the whole API is
    //stringified today (32 json_string and zero json_integer in JsonApi.cpp).
    static ::testing::AssertionResult everyLeafIsAString(const Json &j,
                                                        const std::string &path = "")
    {
        if (j.is_object())
        {
            for (auto it = j.begin(); it != j.end(); ++it)
            {
                auto res = everyLeafIsAString(it.value(), path + "/" + it.key());
                if (!res) return res;
            }
            return ::testing::AssertionSuccess();
        }

        if (j.is_array())
        {
            for (size_t i = 0; i < j.size(); i++)
            {
                auto res = everyLeafIsAString(j[i], path + "/" + std::to_string(i));
                if (!res) return res;
            }
            return ::testing::AssertionSuccess();
        }

        if (j.is_string())
            return ::testing::AssertionSuccess();

        return ::testing::AssertionFailure()
                << "non string leaf at " << path << ": " << j.dump();
    }

    //Walks a document and answers true when `needle` appears as a whole string
    //value anywhere in it. Structural on purpose: searching a serialized dump
    //for a substring would be a comparison on serialized JSON, which this
    //series forbids, and it would also match a longer id containing this one.
    static bool mentionsValue(const Json &j, const std::string &needle)
    {
        if (j.is_string())
            return j.get<std::string>() == needle;

        if (j.is_object())
        {
            for (auto it = j.begin(); it != j.end(); ++it)
            {
                if (it.key() == needle) return true;
                if (mentionsValue(it.value(), needle)) return true;
            }
        }
        else if (j.is_array())
        {
            for (const Json &item: j)
                if (mentionsValue(item, needle)) return true;
        }

        return false;
    }

    //The type_str of every "event" message a session received, in order.
    static std::vector<std::string> eventTypes(const WsTestSession &ws)
    {
        std::vector<std::string> types;
        for (const std::string &m: ws.messages())
        {
            const Json env = Json::parse(m, nullptr, false);
            if (env.is_discarded() || env.value("msg", std::string()) != "event")
                continue;
            types.push_back(env["data"].value("type_str", std::string()));
        }
        return types;
    }

    static bool sawEvent(const std::vector<std::string> &types, const std::string &type)
    {
        return std::find(types.begin(), types.end(), type) != types.end();
    }

    /* ---------------------------------------------------------------------
     * Request shorthands. WS puts the sub-command under "data", HTTP puts it
     * at the root: keeping that asymmetry in one place is what makes the
     * divergence cases below readable.
     * ------------------------------------------------------------------ */

    static Json wsRequest(const std::string &msg, Json data,
                          const std::string &msgId = "e40c")
    {
        return Json{{ "msg", msg }, { "msg_id", msgId }, { "data", data }};
    }

    //Sends an autoscenario sub-command over WS and answers the "data" member
    //of the (single) reply. Fails the calling test when the reply count is not
    //exactly one.
    Json wsAutoscenario(WsTestSession &ws, Json data)
    {
        ws.clear();
        ws.send(wsRequest("autoscenario", data));
        EXPECT_EQ(1u, ws.count()) << "autoscenario " << data.value("type", std::string())
                                  << " answered " << ws.count() << " messages";
        if (ws.count() != 1) return Json::object();
        return ws.lastData();
    }

    /* The scenario every non-T3.18 case works on: two standard steps and a
     * synthetic end step, three different action targets, a non zero pause.
     * Answers the id of the Scenario IO, "io_0" on a fresh house.
     */
    std::string createReferenceScenario(WsTestSession &ws)
    {
        const Json ret = wsAutoscenario(ws, Json{
            { "type", "create" },
            { "name", "Soir\xc3\xa9""e" },   //accented on purpose, see E4.0a
            { "room_name", E40C_ROOM_NAME },
            { "room_type", E40C_ROOM_TYPE },
            { "steps", Json::array({
                Json{{ "step_type", "standard" }, { "step_pause", "1.5" },
                     { "actions", Json::array({ Json{{ "id", IO_BOOL }, { "action", "true" }} }) }},
                Json{{ "step_type", "standard" }, { "step_pause", "0" },
                     { "actions", Json::array({ Json{{ "id", IO_TARGET }, { "action", "true" }},
                                                Json{{ "id", IO_INT }, { "action", "42" }} }) }},
                Json{{ "step_type", "end" },
                     { "actions", Json::array({ Json{{ "id", IO_STRING }, { "action", "done" }} }) }}
            }) }});

        return ret.value("id", std::string());
    }

    static Scenario *scenarioIo(const std::string &id)
    {
        return dynamic_cast<Scenario *>(ListeRoom::Instance().get_io(id));
    }

    /* Amputate one IO element from an io.xml document, the way an installer
     * deleting a line from the file does. Self-closing elements only, which is
     * what every internal IO is written as.
     */
    static bool removeIoFromXml(std::string &xml, const std::string &id)
    {
        const size_t at = xml.find("id=\"" + id + "\"");
        if (at == std::string::npos) return false;
        const size_t start = xml.rfind('<', at);
        const size_t end = xml.find('>', at);
        if (start == std::string::npos || end == std::string::npos) return false;
        xml.erase(start, end - start + 1);
        return true;
    }

    /* Builds the reference scenario, then makes IO_TARGET vanish from io.xml
     * and reloads everything - the "someone deleted an IO from the config"
     * path. It is the ONLY path that leaves a step rule holding an id that
     * does not resolve: the hot path destroys the rule instead (see
     * DeletingAnIoUsedByAStepDestroysTheWholeStepRule).
     * On return the scenario is loaded, checkAutoScenario() has run, and the
     * step rule of step 2 is disabled with IO_TARGET as its missing id.
     */
    std::string loadScenarioWithAnAmputatedStep()
    {
        loadScenarioHouse();

        std::string scenarioId;
        {
            WsTestSession ws;
            scenarioId = createReferenceScenario(ws);
        }
        EXPECT_EQ(SCENARIO_IO_ID, scenarioId);

        saveConfig();

        std::string ioXml = ioXmlOnDisk();
        const std::string rulesXml = rulesXmlOnDisk();
        EXPECT_TRUE(removeIoFromXml(ioXml, IO_TARGET))
                << "the target IO was not found in the saved io.xml";
        EXPECT_EQ(std::string::npos, ioXml.find(IO_TARGET));
        //the rules keep the dead reference verbatim (ActionStd::SaveToXml(),
        //E4.2e): that is what makes this whole case possible
        EXPECT_NE(std::string::npos, rulesXml.find(IO_TARGET));

        clearCoreState();
        loadConfig(ioXml, rulesXml);
        ListeRoom::Instance().checkAutoScenario();
        pumpEventLoop();

        return scenarioId;
    }
};

/*******************************************************************************
 * get_timerange
 *
 * buildJsonGetTimerange() (JsonApi.cpp:1549-1584): a "ranges" array flattened
 * over the seven days, each entry produced by TimeRange::toParams(day) with
 * day = index + 1, plus "months" as a 12 bit set printed and then REVERSED so
 * that it reads january to december left to right.
 ******************************************************************************/

TEST_F(JsonApiScenarioTest, WsGetTimerange)
{
    loadScenarioHouse();

    WsTestSession ws;
    ws.send(wsRequest("get_timerange", Json{{ "id", IO_RANGE }}, "e40c-tr"));

    ASSERT_EQ(1u, ws.count());
    EXPECT_JSON_GOLDEN("e40c_ws_get_timerange", ws.lastMessage());
}

TEST_F(JsonApiScenarioTest, HttpGetTimerange)
{
    loadScenarioHouse();

    HttpTestRequest req;
    req.send(authenticated(Json{{ "action", "get_timerange" }, { "id", IO_RANGE }}));

    ASSERT_EQ(1u, req.count());
    EXPECT_EQ("HTTP/1.0 200 OK", req.statusLine());
    EXPECT_JSON_GOLDEN("e40c_http_get_timerange", req.body());
}

TEST_F(JsonApiScenarioTest, GetTimerangePayloadIsIdenticalOnBothTransports)
{
    //Pinned so every other case can characterize the payload once instead of
    //twice: only the ENVELOPE differs between the two transports.
    loadScenarioHouse();

    WsTestSession ws;
    ws.send(wsRequest("get_timerange", Json{{ "id", IO_RANGE }}));
    ASSERT_EQ(1u, ws.count());
    const Json wsData = ws.lastData();

    HttpTestRequest req;
    req.send(authenticated(Json{{ "action", "get_timerange" }, { "id", IO_RANGE }}));
    ASSERT_EQ(1u, req.count());

    EXPECT_JSON_EQ(wsData, req.bodyJson());
}

TEST_F(JsonApiScenarioTest, GetTimerangeReadsItsIdFromDataOverWsAndFromTheRootOverHttp)
{
    //DIVERGENCE, frozen. WS hands processGetTimerange() the Params decoded
    //from the "data" member (JsonApiHandlerWS.cpp:199), HTTP hands it the
    //Params decoded from the ROOT object (JsonApiHandlerHttp.cpp:167). Each
    //transport answers "wrong input" for the shape the other one requires.
    loadScenarioHouse();

    WsTestSession ws;
    ws.send(Json{{ "msg", "get_timerange" }, { "msg_id", "1" }, { "id", IO_RANGE }});
    ASSERT_EQ(1u, ws.count());
    EXPECT_JSON_EQ(std::string(R"({"error":"wrong input"})"), ws.lastData());

    HttpTestRequest req;
    req.send(authenticated(Json{{ "action", "get_timerange" },
                                { "data", {{ "id", IO_RANGE }} }}));
    ASSERT_EQ(1u, req.count());
    EXPECT_JSON_EQ(std::string(R"({"error":"wrong input"})"), req.body());
}

TEST_F(JsonApiScenarioTest, GetTimerangeOnAnUnknownIdAndOnAnIoOfAnotherTypeIsWrongInput)
{
    //Same answer for "no such IO" and for "an IO the dynamic_cast rejects":
    //buildJsonGetTimerange() cannot tell them apart, and the client cannot
    //either.
    loadScenarioHouse();

    WsTestSession ws;
    ws.send(wsRequest("get_timerange", Json{{ "id", "e40c_no_such_io" }}));
    ASSERT_EQ(1u, ws.count());
    EXPECT_JSON_EQ(std::string(R"({"error":"wrong input"})"), ws.lastData());

    ws.clear();
    ws.send(wsRequest("get_timerange", Json{{ "id", IO_INT }}));
    ASSERT_EQ(1u, ws.count());
    EXPECT_JSON_EQ(std::string(R"({"error":"wrong input"})"), ws.lastData());

    ws.clear();
    //no id at all: get_io("") answers null, same error
    ws.send(wsRequest("get_timerange", Json::object()));
    ASSERT_EQ(1u, ws.count());
    EXPECT_JSON_EQ(std::string(R"({"error":"wrong input"})"), ws.lastData());
}

TEST_F(JsonApiScenarioTest, GetTimerangeNumbersTheDaysFromOneAndFlattensTheWeek)
{
    //The ranges of the seven day vectors are concatenated in weekday order,
    //monday first, and "day" is the INDEX PLUS ONE (TimeRange::toParams(),
    //src/lib/TimeRange.cpp:429). The fixture puts two ranges on monday, one on
    //wednesday and one on sunday precisely so both ends of that numbering and
    //the flattening order are observed.
    loadScenarioHouse();

    WsTestSession ws;
    ws.send(wsRequest("get_timerange", Json{{ "id", IO_RANGE }}));
    ASSERT_EQ(1u, ws.count());

    const Json ranges = ws.lastData()["ranges"];
    ASSERT_TRUE(ranges.is_array());
    ASSERT_EQ(4u, ranges.size()) << ranges.dump();

    EXPECT_EQ("1", ranges[0].value("day", std::string()));
    EXPECT_EQ("1", ranges[1].value("day", std::string()));
    EXPECT_EQ("3", ranges[2].value("day", std::string()));
    EXPECT_EQ("7", ranges[3].value("day", std::string()));

    //and the two monday ranges keep their declaration order
    EXPECT_EQ("8", ranges[0].value("start_hour", std::string()));
    EXPECT_EQ("1", ranges[1].value("start_hour", std::string()));
}

TEST_F(JsonApiScenarioTest, GetTimerangeEmitsTheElevenKeysOfATimeRangeWithNonTrivialValues)
{
    /* COUNTER-MUTATION GUARD, the lesson of E4.0b: a payload whose keys are
     * all at their default value pins nothing, and a golden that only shows an
     * absence pins the fixture rather than the contract. Every one of the
     * eleven keys is checked here in PRESENCE, so a rename in
     * TimeRange::toParams() fails right here with the key name in the message.
     *
     * On the SWAP of two key names, precisely - the review corrected an earlier
     * claim here that "no other key of the same object carries the same value",
     * which is false for ranges[0], where start_type == end_type == "0" and
     * start_offset == end_offset == "1". What actually pins those two pairs is
     * that the OTHER ranges disagree: ranges[1] has start_offset "-1" against
     * end_offset "1", and start_type "2" against end_type "0"; ranges[2] has
     * end_type "1" against start_type "0". The four ranges are kept different
     * on purpose for that reason - a single range, whatever its values, cannot
     * pin a symmetric pair.
     */
    loadScenarioHouse();

    WsTestSession ws;
    ws.send(wsRequest("get_timerange", Json{{ "id", IO_RANGE }}));
    ASSERT_EQ(1u, ws.count());

    const Json ranges = ws.lastData()["ranges"];
    ASSERT_EQ(4u, ranges.size());

    for (const Json &r: ranges)
    {
        for (const std::string &k: timeRangePayloadKeys())
            EXPECT_TRUE(r.contains(k)) << "TimeRange::toParams() no longer emits " << k;
        EXPECT_EQ(timeRangePayloadKeys().size(), r.size()) << r.dump();
    }

    //first monday range: a plain range, every member different
    const Json &normal = ranges[0];
    EXPECT_EQ("8", normal.value("start_hour", std::string()));
    EXPECT_EQ("30", normal.value("start_min", std::string()));
    EXPECT_EQ("15", normal.value("start_sec", std::string()));
    EXPECT_EQ("0", normal.value("start_type", std::string()));
    EXPECT_EQ("1", normal.value("start_offset", std::string()));
    EXPECT_EQ("12", normal.value("end_hour", std::string()));
    EXPECT_EQ("45", normal.value("end_min", std::string()));
    EXPECT_EQ("5", normal.value("end_sec", std::string()));
    EXPECT_EQ("0", normal.value("end_type", std::string()));
    EXPECT_EQ("1", normal.value("end_offset", std::string()));

    //second monday range: sunset start (type 2) with a NEGATIVE offset
    EXPECT_EQ("2", ranges[1].value("start_type", std::string()));
    EXPECT_EQ("-1", ranges[1].value("start_offset", std::string()));

    //wednesday: sunrise end (type 1) with an explicit positive offset
    EXPECT_EQ("1", ranges[2].value("end_type", std::string()));
    EXPECT_EQ("1", ranges[2].value("end_offset", std::string()));

    //sunday: noon start (type 3)
    EXPECT_EQ("3", ranges[3].value("start_type", std::string()));

    EXPECT_TRUE(everyLeafIsAString(ws.lastData()));
}

TEST_F(JsonApiScenarioTest, GetTimerangeEmitsMonthsAsATwelveCharacterBitsetJanuaryFirst)
{
    //The bitset is printed most significant bit first and then REVERSED
    //(JsonApi.cpp:1577-1581), so the string reads january to december. The
    //fixture uses january+february+december exactly so that a lost
    //std::reverse() shows: the reversed string is a different one.
    loadScenarioHouse();

    WsTestSession ws;
    ws.send(wsRequest("get_timerange", Json{{ "id", IO_RANGE }}));
    ASSERT_EQ(1u, ws.count());

    const std::string months = ws.lastData().value("months", std::string());
    ASSERT_EQ(12u, months.size());
    EXPECT_EQ(MONTHS_JAN_FEB_DEC, months);
    //explicitly, so the intent survives a change of fixture
    EXPECT_EQ('1', months[0]);      //january
    EXPECT_EQ('1', months[1]);      //february
    EXPECT_EQ('0', months[2]);      //march
    EXPECT_EQ('1', months[11]);     //december
}

TEST_F(JsonApiScenarioTest, GetTimerangeOfAnEmptyTimeRangeStillCarriesBothMembers)
{
    //A range created by the scenario schedule has no plage and every month
    //set (InPlageHoraire.cpp:54). "ranges" is present as an EMPTY ARRAY, never
    //absent and never null - a client indexing it blindly must keep working.
    loadScenarioHouse();

    WsTestSession ws;
    const std::string scenarioId = createReferenceScenario(ws);
    ASSERT_FALSE(scenarioId.empty());

    const Json sched = wsAutoscenario(ws, Json{{ "type", "add_schedule" },
                                               { "id", scenarioId }});
    ASSERT_EQ(SCENARIO_SCHEDULE_ID, sched.value("id", std::string()));

    ws.clear();
    ws.send(wsRequest("get_timerange", Json{{ "id", SCENARIO_SCHEDULE_ID }}));
    ASSERT_EQ(1u, ws.count());
    EXPECT_JSON_EQ(std::string(R"({"ranges":[],"months":"111111111111"})"), ws.lastData());
}

/*******************************************************************************
 * set_timerange
 *
 * buildJsonSetTimerange() (JsonApi.cpp:1586-1652). Destructive by design: it
 * calls InPlageHoraire::clear() BEFORE reading anything, so whatever it fails
 * to parse is simply lost.
 ******************************************************************************/

TEST_F(JsonApiScenarioTest, SetTimerangeRoundTripsWhatGetTimerangeAnswered)
{
    //THE round trip of this file: the day+1 of toParams() and the "1".."7"
    //read back by buildJsonSetTimerange() (JsonApi.cpp:1610-1616) have to
    //agree, and the reversed months string has to survive its second reversal.
    //An off by one on either side moves a range to another day and shows here.
    loadScenarioHouse();

    WsTestSession ws;
    ws.send(wsRequest("get_timerange", Json{{ "id", IO_RANGE }}));
    ASSERT_EQ(1u, ws.count());
    const Json before = ws.lastData();

    Json data = before;
    data["id"] = IO_RANGE;
    ws.clear();
    ws.send(wsRequest("set_timerange", data));
    ASSERT_EQ(1u, ws.count());
    EXPECT_JSON_EQ(std::string(R"({"success":"true"})"), ws.lastData());

    ws.clear();
    ws.send(wsRequest("get_timerange", Json{{ "id", IO_RANGE }}));
    ASSERT_EQ(1u, ws.count());
    EXPECT_JSON_EQ(before, ws.lastData());
}

TEST_F(JsonApiScenarioTest, SetTimerangeMapsDayOneToMondayAndDaySevenToSunday)
{
    loadScenarioHouse();

    WsTestSession ws;
    ws.send(wsRequest("set_timerange", Json{
        { "id", IO_RANGE },
        { "months", "000000000001" },
        { "ranges", Json::array({
            Json{{ "day", "1" }, { "start_hour", "1" }, { "start_min", "0" }, { "start_sec", "0" },
                 { "start_type", "0" }, { "start_offset", "1" },
                 { "end_hour", "2" }, { "end_min", "0" }, { "end_sec", "0" },
                 { "end_type", "0" }, { "end_offset", "1" }},
            Json{{ "day", "7" }, { "start_hour", "7" }, { "start_min", "0" }, { "start_sec", "0" },
                 { "start_type", "0" }, { "start_offset", "1" },
                 { "end_hour", "8" }, { "end_min", "0" }, { "end_sec", "0" },
                 { "end_type", "0" }, { "end_offset", "1" }}
        }) }}));
    ASSERT_EQ(1u, ws.count());
    EXPECT_JSON_EQ(std::string(R"({"success":"true"})"), ws.lastData());

    //read back through the IO itself, so the assertion does not depend on the
    //very numbering it is checking
    InPlageHoraire *range = dynamic_cast<InPlageHoraire *>(io(IO_RANGE));
    ASSERT_TRUE(range != nullptr);
    ASSERT_EQ(1u, range->getMonday().size());
    EXPECT_EQ("1", range->getMonday()[0].shour);
    ASSERT_EQ(1u, range->getSunday().size());
    EXPECT_EQ("7", range->getSunday()[0].shour);
    EXPECT_EQ(0u, range->getWednesday().size());

    //and december only, which is what the reversed bitset means
    EXPECT_TRUE(range->months.test(InPlageHoraire::DECEMBER));
    EXPECT_FALSE(range->months.test(InPlageHoraire::JANUARY));
}

TEST_F(JsonApiScenarioTest, SetTimerangeSilentlyDropsARangeWhoseDayIsOutOfRange)
{
    //FROZEN: the seven `if (p["day"] == ...)` of JsonApi.cpp:1610-1616 have no
    //else. A range with day 0, day 8 or no day at all is parsed, logged on
    //stdout, and then dropped - and the answer is still success:true.
    loadScenarioHouse();

    WsTestSession ws;
    ws.send(wsRequest("set_timerange", Json{
        { "id", IO_RANGE },
        { "ranges", Json::array({
            Json{{ "day", "0" }, { "start_hour", "1" }},
            Json{{ "day", "8" }, { "start_hour", "2" }},
            Json{{ "start_hour", "3" }},
            Json{{ "day", "2" }, { "start_hour", "4" }, { "start_min", "0" }, { "start_sec", "0" },
                 { "start_type", "0" }, { "start_offset", "1" },
                 { "end_hour", "5" }, { "end_min", "0" }, { "end_sec", "0" },
                 { "end_type", "0" }, { "end_offset", "1" }}
        }) }}));

    ASSERT_EQ(1u, ws.count());
    EXPECT_JSON_EQ(std::string(R"({"success":"true"})"), ws.lastData());

    ws.clear();
    ws.send(wsRequest("get_timerange", Json{{ "id", IO_RANGE }}));
    ASSERT_EQ(1u, ws.count());
    const Json ranges = ws.lastData()["ranges"];
    ASSERT_EQ(1u, ranges.size()) << ranges.dump();
    EXPECT_EQ("2", ranges[0].value("day", std::string()));
    EXPECT_EQ("4", ranges[0].value("start_hour", std::string()));
}

TEST_F(JsonApiScenarioTest, SetTimerangeWithoutRangesWipesEveryRange)
{
    //o->clear() runs before anything is read (JsonApi.cpp:1596): a request
    //that carries no "ranges" member at all empties the IO. There is no
    //partial update in this API.
    loadScenarioHouse();

    WsTestSession ws;
    ws.send(wsRequest("get_timerange", Json{{ "id", IO_RANGE }}));
    ASSERT_EQ(1u, ws.count());
    ASSERT_EQ(4u, ws.lastData()["ranges"].size());

    ws.clear();
    ws.send(wsRequest("set_timerange", Json{{ "id", IO_RANGE }}));
    ASSERT_EQ(1u, ws.count());
    EXPECT_JSON_EQ(std::string(R"({"success":"true"})"), ws.lastData());

    ws.clear();
    ws.send(wsRequest("get_timerange", Json{{ "id", IO_RANGE }}));
    ASSERT_EQ(1u, ws.count());
    const Json after = ws.lastData();
    EXPECT_TRUE(after["ranges"].is_array());
    EXPECT_EQ(0u, after["ranges"].size());
    //months, on the other hand, is only touched when the member is present
    EXPECT_EQ(MONTHS_JAN_FEB_DEC, after.value("months", std::string()));
}

TEST_F(JsonApiScenarioTest, SetTimerangeKeepsTheOldMonthsWhenTheNewOneIsUnparsable)
{
    //bitset<12>(string) throws on any character other than 0/1, and the catch
    //logs and keeps the previous value (JsonApi.cpp:1626-1634). A shorter
    //string is NOT an error: bitset zero fills the high bits, so "1" means
    //january alone.
    loadScenarioHouse();

    WsTestSession ws;
    ws.send(wsRequest("set_timerange", Json{{ "id", IO_RANGE }, { "months", "12x" }}));
    ASSERT_EQ(1u, ws.count());
    EXPECT_JSON_EQ(std::string(R"({"success":"true"})"), ws.lastData());

    ws.clear();
    ws.send(wsRequest("get_timerange", Json{{ "id", IO_RANGE }}));
    ASSERT_EQ(1u, ws.count());
    EXPECT_EQ(MONTHS_JAN_FEB_DEC, ws.lastData().value("months", std::string()));

    ws.clear();
    ws.send(wsRequest("set_timerange", Json{{ "id", IO_RANGE }, { "months", "1" }}));
    ASSERT_EQ(1u, ws.count());

    ws.clear();
    ws.send(wsRequest("get_timerange", Json{{ "id", IO_RANGE }}));
    ASSERT_EQ(1u, ws.count());
    EXPECT_EQ("100000000000", ws.lastData().value("months", std::string()));
}

TEST_F(JsonApiScenarioTest, SetTimerangeOnAnUnknownIdIsWrongInputOnBothTransports)
{
    loadScenarioHouse();

    WsTestSession ws;
    ws.send(wsRequest("set_timerange", Json{{ "id", "e40c_no_such_io" }}));
    ASSERT_EQ(1u, ws.count());
    EXPECT_JSON_EQ(std::string(R"({"error":"wrong input"})"), ws.lastData());

    HttpTestRequest req;
    req.send(authenticated(Json{{ "action", "set_timerange" }, { "id", IO_INT }}));
    ASSERT_EQ(1u, req.count());
    EXPECT_JSON_EQ(std::string(R"({"error":"wrong input"})"), req.body());
}

TEST_F(JsonApiScenarioTest, HttpSetTimerangeReadsTheRootObjectAndWsReadsData)
{
    //DIVERGENCE, frozen, and this one is the dangerous half of the pair: the
    //WS shaped request sent to HTTP does not answer an error, it answers
    //"wrong input" because the root carries no id - while the HTTP shaped
    //request sent to WS ALSO answers "wrong input". Neither transport tells
    //the client it used the wrong shape.
    loadScenarioHouse();

    HttpTestRequest ok;
    ok.send(authenticated(Json{{ "action", "set_timerange" },
                               { "id", IO_RANGE },
                               { "months", "111111111111" }}));
    ASSERT_EQ(1u, ok.count());
    EXPECT_JSON_EQ(std::string(R"({"success":"true"})"), ok.body());

    HttpTestRequest wsShaped;
    wsShaped.send(authenticated(Json{{ "action", "set_timerange" },
                                     { "data", {{ "id", IO_RANGE }} }}));
    ASSERT_EQ(1u, wsShaped.count());
    EXPECT_JSON_EQ(std::string(R"({"error":"wrong input"})"), wsShaped.body());

    WsTestSession ws;
    ws.send(Json{{ "msg", "set_timerange" }, { "msg_id", "1" }, { "id", IO_RANGE }});
    ASSERT_EQ(1u, ws.count());
    EXPECT_JSON_EQ(std::string(R"({"error":"wrong input"})"), ws.lastData());
}

TEST_F(JsonApiScenarioTest, SetTimerangeRaisesTimeRangeChangedAndScenarioChanged)
{
    //JsonApi.cpp:1637-1644. The second event only fires when the IO is the
    //schedule of a scenario, which is exactly what add_schedule builds - so
    //the pair is characterized on a real scheduled scenario.
    loadScenarioHouse();

    WsTestSession ws;
    const std::string scenarioId = createReferenceScenario(ws);
    ASSERT_FALSE(scenarioId.empty());
    ASSERT_EQ(SCENARIO_SCHEDULE_ID,
              wsAutoscenario(ws, Json{{ "type", "add_schedule" }, { "id", scenarioId }})
                      .value("id", std::string()));

    pumpEventLoop();
    ws.clear();

    ws.send(wsRequest("set_timerange", Json{{ "id", SCENARIO_SCHEDULE_ID },
                                            { "months", "111111111111" }}));
    ASSERT_EQ(1u, ws.count());
    ws.clear();
    pumpEventLoop();

    const std::vector<std::string> types = eventTypes(ws);
    //"timerange_changed", not "time_range_changed": the wire spelling is what
    //clients match on, and it is not the one the enum suggests
    EXPECT_TRUE(sawEvent(types, "timerange_changed"));
    EXPECT_TRUE(sawEvent(types, "scenario_changed"));
}

TEST_F(JsonApiScenarioTest, SetTimerangeIsScopeDeniedButAutoscenarioIsNot)
{
    //WS only (JsonApiHandlerWS.cpp:200-204). Frozen as it is, and the contrast
    //is the point: set_timerange is gated for a service-scoped session while
    //autoscenario - which creates, modifies and DELETES scenarios - is not
    //gated at all. HTTP has no scope notion whatsoever.
    loadScenarioHouse();

    WsTestSession ws(true /*authenticated*/, true /*serviceScope*/);
    ws.send(wsRequest("set_timerange", Json{{ "id", IO_RANGE }}, "1"));
    ASSERT_EQ(1u, ws.count());
    EXPECT_JSON_EQ(std::string(R"({"msg":"set_timerange","msg_id":"1",)"
                               R"("data":{"error":"scope denied"}})"),
                   ws.lastMessage());

    ws.clear();
    ws.send(wsRequest("get_timerange", Json{{ "id", IO_RANGE }}, "2"));
    ASSERT_EQ(1u, ws.count());
    EXPECT_TRUE(ws.lastData().contains("ranges")) << ws.lastMessage();

    ws.clear();
    ws.send(wsRequest("autoscenario", Json{{ "type", "list" }}, "3"));
    ASSERT_EQ(1u, ws.count());
    EXPECT_JSON_EQ(std::string(R"({"scenarios":[]})"), ws.lastData());
}

/*******************************************************************************
 * autoscenario list / get
 ******************************************************************************/

TEST_F(JsonApiScenarioTest, AutoscenarioListOnAHouseWithoutScenarioIsAnEmptyArray)
{
    loadScenarioHouse();

    WsTestSession ws;
    EXPECT_JSON_EQ(std::string(R"({"scenarios":[]})"),
                   wsAutoscenario(ws, Json{{ "type", "list" }}));
}

TEST_F(JsonApiScenarioTest, WsAutoscenarioList)
{
    //Two scenarios, so the array order (creation order, i.e. the order of
    //ListeRoom's scenario cache) is pinned - arrays are ordered, always.
    loadScenarioHouse();

    WsTestSession ws;
    ASSERT_FALSE(createReferenceScenario(ws).empty());
    //the second one CYCLES while staying schedule-disabled, so this golden
    //carries cycle "true" against enabled "false" on the same object. Second
    //independent witness of that pair, after the scheduled golden: one case
    //pinning a key pair is a net one edit away from disappearing.
    ASSERT_FALSE(wsAutoscenario(ws, Json{{ "type", "create" },
                                         { "name", "Second" },
                                         { "cycle", "true" },
                                         { "room_name", E40C_ROOM_NAME },
                                         { "room_type", E40C_ROOM_TYPE }})
                         .value("id", std::string()).empty());

    ws.clear();
    ws.send(wsRequest("autoscenario", Json{{ "type", "list" }}, "e40c-list"));
    ASSERT_EQ(1u, ws.count());
    EXPECT_JSON_GOLDEN("e40c_ws_autoscenario_list", ws.lastMessage());

    const Json scenarios = ws.lastData()["scenarios"];
    ASSERT_EQ(2u, scenarios.size());
    EXPECT_EQ("false", scenarios[0].value("cycle", std::string()));
    EXPECT_EQ("true", scenarios[1].value("cycle", std::string()));
    EXPECT_EQ("false", scenarios[1].value("enabled", std::string()));
}

TEST_F(JsonApiScenarioTest, WsAutoscenarioGet)
{
    loadScenarioHouse();

    WsTestSession ws;
    const std::string scenarioId = createReferenceScenario(ws);
    ASSERT_EQ(SCENARIO_IO_ID, scenarioId);

    ws.clear();
    ws.send(wsRequest("autoscenario", Json{{ "type", "get" }, { "id", scenarioId }},
                      "e40c-get"));
    ASSERT_EQ(1u, ws.count());
    EXPECT_JSON_GOLDEN("e40c_ws_autoscenario_get", ws.lastMessage());
}

TEST_F(JsonApiScenarioTest, HttpAutoscenarioGet)
{
    //HTTP reads "type" and "id" from the ROOT object.
    loadScenarioHouse();

    std::string scenarioId;
    {
        WsTestSession ws;
        scenarioId = createReferenceScenario(ws);
    }
    ASSERT_EQ(SCENARIO_IO_ID, scenarioId);

    HttpTestRequest req;
    req.send(authenticated(Json{{ "action", "autoscenario" },
                                { "type", "get" },
                                { "id", scenarioId }}));
    ASSERT_EQ(1u, req.count());
    EXPECT_EQ("HTTP/1.0 200 OK", req.statusLine());
    EXPECT_JSON_GOLDEN("e40c_http_autoscenario_get", req.body());
}

TEST_F(JsonApiScenarioTest, AutoscenarioGetEmitsTheWholeKeySetAndTheSyntheticEndStep)
{
    //The structural contract of Scenario::toJson(), spelled out so a rename in
    //production fails HERE with the key name in the message. steps_count
    //counts the STANDARD steps only: the "end" step is appended outside the
    //loop (IO/Scenario.cpp) and is not counted.
    //T3.18: scenarioPayloadKeys() gained three entries and this case needed no
    //other change - only its NAME, which said "the seven keys".
    loadScenarioHouse();

    WsTestSession ws;
    const std::string scenarioId = createReferenceScenario(ws);
    const Json sc = wsAutoscenario(ws, Json{{ "type", "get" }, { "id", scenarioId }});

    ASSERT_TRUE(sc.is_object());
    for (const std::string &k: scenarioPayloadKeys())
        EXPECT_TRUE(sc.contains(k)) << "Scenario::toJson() no longer emits " << k;
    EXPECT_EQ(scenarioPayloadKeys().size(), sc.size()) << sc.dump();

    EXPECT_EQ(SCENARIO_IO_ID, sc.value("id", std::string()));
    EXPECT_EQ("false", sc.value("cycle", std::string()));
    //create defaults "disabled" to true, and toJson() emits its NEGATION
    EXPECT_EQ("false", sc.value("enabled", std::string()));
    //not scheduled: the literal string "false", not a boolean and not an id
    EXPECT_EQ("false", sc.value("schedule", std::string()));
    EXPECT_EQ("other", sc.value("category", std::string()));
    //T3.18, the healthy line of the four-state table: false / false / ""
    EXPECT_EQ("false", sc.value("broken", std::string()));
    EXPECT_EQ("false", sc.value("disabled_missing_io", std::string()));
    EXPECT_EQ("", sc.value("missing_ios", std::string()));
    EXPECT_EQ("2", sc.value("steps_count", std::string()));

    const Json steps = sc["steps"];
    ASSERT_TRUE(steps.is_array());
    ASSERT_EQ(3u, steps.size()) << "two standard steps plus the synthetic end step";

    //a standard step is exactly {step_pause, step_type, actions}
    EXPECT_EQ(3u, steps[0].size()) << steps[0].dump();
    EXPECT_EQ("standard", steps[0].value("step_type", std::string()));
    EXPECT_EQ("1.5", steps[0].value("step_pause", std::string()));
    EXPECT_EQ("0", steps[1].value("step_pause", std::string()));

    //the end step has NO step_pause at all - two keys, not three
    EXPECT_EQ("end", steps[2].value("step_type", std::string()));
    EXPECT_EQ(2u, steps[2].size()) << steps[2].dump();
    EXPECT_FALSE(steps[2].contains("step_pause"));

    //an action is exactly {id, action}
    ASSERT_EQ(1u, steps[0]["actions"].size());
    EXPECT_EQ(2u, steps[0]["actions"][0].size()) << steps[0]["actions"][0].dump();
    EXPECT_EQ(IO_BOOL, steps[0]["actions"][0].value("id", std::string()));
    EXPECT_EQ("true", steps[0]["actions"][0].value("action", std::string()));

    //array order is semantic: the two actions of step 2 keep their order
    ASSERT_EQ(2u, steps[1]["actions"].size());
    EXPECT_EQ(IO_TARGET, steps[1]["actions"][0].value("id", std::string()));
    EXPECT_EQ(IO_INT, steps[1]["actions"][1].value("id", std::string()));
    EXPECT_EQ("42", steps[1]["actions"][1].value("action", std::string()));

    //and the end step really carries its own action
    ASSERT_EQ(1u, steps[2]["actions"].size());
    EXPECT_EQ(IO_STRING, steps[2]["actions"][0].value("id", std::string()));
    EXPECT_EQ("done", steps[2]["actions"][0].value("action", std::string()));

    EXPECT_TRUE(everyLeafIsAString(sc));
}

TEST_F(JsonApiScenarioTest, AutoscenarioGetHidesTheInternalIosOfTheScenario)
{
    //Each step rule also acts on the internal IOs of the scenario (step,
    //timer). countRealActions() skips them (AutoScenario.cpp:703-713), so the
    //payload only shows what the user asked for. Pinned because that skip list
    //is the very function T3.18 changes.
    loadScenarioHouse();

    WsTestSession ws;
    const std::string scenarioId = createReferenceScenario(ws);
    const Json sc = wsAutoscenario(ws, Json{{ "type", "get" }, { "id", scenarioId }});

    for (const Json &step: sc["steps"])
    {
        for (const Json &act: step["actions"])
        {
            const std::string id = act.value("id", std::string());
            EXPECT_TRUE(id.compare(0, std::string(SCENARIO_ID).size(), SCENARIO_ID) != 0)
                    << "internal scenario IO " << id << " leaked into the payload";
        }
    }

    //the internal IOs do exist, they are simply not part of this payload
    EXPECT_TRUE(io(std::string(SCENARIO_ID) + "_step") != nullptr);
    EXPECT_TRUE(io(std::string(SCENARIO_ID) + "_timer") != nullptr);
    EXPECT_TRUE(io(std::string(SCENARIO_ID) + "_is_active") != nullptr);
}

TEST_F(JsonApiScenarioTest, AutoscenarioGetOnSomethingThatIsNotAnAutoScenarioIsWrongInput)
{
    //Three different misses, one single answer: unknown id, an IO that is not
    //a Scenario, and a Scenario IO WITHOUT the auto_scenario param (a plain
    //scenario variable, which is a legitimate IO of the tree).
    loadScenarioHouse();

    Params plain = {{ "type", "Scenario" }, { "id", "e40c_plain_scenario" },
                    { "name", "Plain scenario" }};
    ASSERT_TRUE(createIO(plain, firstRoom()) != nullptr);
    pumpEventLoop();

    WsTestSession ws;
    for (const char *id: { "e40c_no_such_io", IO_INT, "e40c_plain_scenario" })
    {
        const Json ret = wsAutoscenario(ws, Json{{ "type", "get" }, { "id", id }});
        EXPECT_JSON_EQ(std::string(R"({"error":"wrong input"})"), ret) << "for id " << id;
    }
}

TEST_F(JsonApiScenarioTest, AutoscenarioGetCategoryFollowsTheGuiTypeOfTheActionTargets)
{
    //getCategory() (AutoScenario.cpp:800-853) counts the action targets by
    //gui_type/type and concatenates the categories, most numerous first.
    //No concrete light IO is registered in this binary (OutputLight has no
    //REGISTER_IO, it is a driver base class), so the gui_type is set at
    //runtime - which is exactly what a real light IO does in its constructor
    //(IO/OutputLight.cpp:55).
    loadScenarioHouse();

    ASSERT_TRUE(io(IO_BOOL) != nullptr);
    io(IO_BOOL)->set_param("gui_type", "light");

    WsTestSession ws;
    const std::string scenarioId = createReferenceScenario(ws);
    const Json sc = wsAutoscenario(ws, Json{{ "type", "get" }, { "id", scenarioId }});

    //one light (step 1) against two others (step 2): "other" comes first
    EXPECT_EQ("other-light", sc.value("category", std::string()));
}

TEST_F(JsonApiScenarioTest, AutoscenarioPayloadIsIdenticalOnBothTransports)
{
    loadScenarioHouse();

    std::string scenarioId;
    Json wsPayload;
    {
        WsTestSession ws;
        scenarioId = createReferenceScenario(ws);
        wsPayload = wsAutoscenario(ws, Json{{ "type", "get" }, { "id", scenarioId }});
    }

    HttpTestRequest req;
    req.send(authenticated(Json{{ "action", "autoscenario" },
                                { "type", "get" },
                                { "id", scenarioId }}));
    ASSERT_EQ(1u, req.count());
    EXPECT_JSON_EQ(wsPayload, req.bodyJson());
}

/*******************************************************************************
 * autoscenario with an unknown type: SILENCE
 *
 * Known divergence, already listed in JsonApiCharacterization.h. Neither
 * transport has an else branch, so the client waits for an answer that will
 * never come. Same shape of silence as processCamera() (found by T3.17d).
 ******************************************************************************/

TEST_F(JsonApiScenarioTest, WsAutoscenarioWithAnUnknownOrMissingTypeAnswersNothingAtAll)
{
    loadScenarioHouse();

    WsTestSession ws;
    /* T3.18 - the probe was "reenable", which this ticket turned into a REAL
     * sub-command (it ships the dedicated re-enable rather than falling back on
     * set_param, which cannot refuse). The probe is now a string that cannot
     * become a command; the hole itself is unchanged and still frozen here.
     */
    ws.send(wsRequest("autoscenario", Json{{ "type", "e40c_not_a_command" }}));
    EXPECT_EQ(0u, ws.count()) << "expected silence, got: " << ws.lastMessage();

    //and the brand new sub-command DOES answer, on an unknown id like on any
    //other autoscenario command: it is not part of the silence
    ws.send(wsRequest("autoscenario", Json{{ "type", "reenable" }, { "id", "e40c_nope" }}));
    EXPECT_EQ(1u, ws.count());
    EXPECT_JSON_EQ(std::string(R"({"error":"wrong input"})"), ws.lastData());
    ws.clear();

    ws.send(wsRequest("autoscenario", Json{{ "type", "" }}));
    EXPECT_EQ(0u, ws.count()) << "expected silence, got: " << ws.lastMessage();

    ws.send(wsRequest("autoscenario", Json::object()));
    EXPECT_EQ(0u, ws.count()) << "expected silence, got: " << ws.lastMessage();

    //no data member at all: jansson_string_get(nullptr, "type") answers ""
    ws.send(Json{{ "msg", "autoscenario" }, { "msg_id", "1" }});
    EXPECT_EQ(0u, ws.count()) << "expected silence, got: " << ws.lastMessage();

    //and the silence survives a loop pump: nothing is queued, nothing is late
    pumpEventLoop();
    EXPECT_EQ(0u, ws.count()) << "expected silence, got: " << ws.lastMessage();
}

TEST_F(JsonApiScenarioTest, HttpAutoscenarioWithAnUnknownTypeAnswersNothingAtAll)
{
    //The HTTP side of the same hole, and it is worse there: the connection is
    //left open with no response and no close (JsonApiHandlerHttp.cpp:880-896).
    loadScenarioHouse();

    //T3.18: the probe was "reenable", now a real sub-command. See the WS case.
    HttpTestRequest unknown;
    unknown.send(authenticated(Json{{ "action", "autoscenario" },
                                    { "type", "e40c_not_a_command" }}));
    EXPECT_EQ(0u, unknown.count());
    EXPECT_TRUE(unknown.closes().empty());

    /* T3.18 - the positive half, and it MUST be asserted on this transport too.
     * Request dispatch is per-transport code (this handler reads the ROOT
     * object, the WS one reads "data"), so the WS assertion proves nothing
     * about HTTP: deleting the three lines of the HTTP dispatcher left the
     * whole suite green until this was added. Same lesson as T3.17c.
     */
    HttpTestRequest reenable;
    reenable.send(authenticated(Json{{ "action", "autoscenario" },
                                     { "type", "reenable" },
                                     { "id", "e40c_nope" }}));
    ASSERT_EQ(1u, reenable.count()) << "the HTTP dispatcher has no `reenable` branch";
    EXPECT_JSON_EQ(std::string(R"({"error":"wrong input"})"), reenable.bodyJson());

    //A WS shaped request sent to HTTP falls in the very same hole: "type" is
    //under "data", the root has none, and the server answers nothing.
    HttpTestRequest wsShaped;
    wsShaped.send(authenticated(Json{{ "action", "autoscenario" },
                                     { "data", {{ "type", "list" }} }}));
    EXPECT_EQ(0u, wsShaped.count());
}

TEST_F(JsonApiScenarioTest, HttpAutoscenarioReenableRefusesAStillBrokenScenarioWithItsIds)
{
    /* And the answer that carries the whole point of the command, on HTTP: it
     * REFUSES, naming what to repair. `set_param` cannot do that, which is why
     * T3.18 ships a command rather than reusing it.
     */
    const std::string scenarioId = loadScenarioWithAnAmputatedStep();
    ASSERT_FALSE(scenarioId.empty());

    HttpTestRequest req;
    req.send(authenticated(Json{{ "action", "autoscenario" },
                                { "type", "reenable" },
                                { "id", scenarioId }}));
    ASSERT_EQ(1u, req.count());
    EXPECT_EQ("HTTP/1.0 200 OK", req.statusLine());
    EXPECT_JSON_EQ(std::string(R"({"error":"scenario still references missing IOs: e40c_target"})"),
                   req.bodyJson());

    //refused means UNCHANGED: the payload still says the scenario is disabled
    HttpTestRequest get;
    get.send(authenticated(Json{{ "action", "autoscenario" },
                                { "type", "get" },
                                { "id", scenarioId }}));
    ASSERT_EQ(1u, get.count());
    const Json sc = get.bodyJson();
    EXPECT_EQ("true", sc.value("disabled_missing_io", std::string()));
    EXPECT_EQ("true", sc.value("broken", std::string()));
}

/*******************************************************************************
 * autoscenario create
 ******************************************************************************/

TEST_F(JsonApiScenarioTest, AutoscenarioCreateAnswersTheIdOfTheNewScenarioIo)
{
    loadScenarioHouse();

    WsTestSession ws;
    const Json ret = wsAutoscenario(ws, Json{{ "type", "create" },
                                             { "room_name", E40C_ROOM_NAME },
                                             { "room_type", E40C_ROOM_TYPE }});

    //exactly one key, the id of the created IO - not the auto_scenario id
    ASSERT_TRUE(ret.is_object());
    EXPECT_EQ(1u, ret.size()) << ret.dump();
    EXPECT_EQ(SCENARIO_IO_ID, ret.value("id", std::string()));

    Scenario *sc = scenarioIo(SCENARIO_IO_ID);
    ASSERT_TRUE(sc != nullptr);
    EXPECT_EQ(SCENARIO_ID, sc->get_param("auto_scenario"));
    //the defaults of buildAutoscenarioCreate() (JsonApi.cpp:1685-1689)
    EXPECT_EQ("false", sc->get_param("visible"));
    EXPECT_EQ("false", sc->get_param("cycle"));
    EXPECT_EQ("true", sc->get_param("disabled"));
    EXPECT_FALSE(sc->get_param("name").empty());

    //and its four internal IOs exist, invisible, in the same room
    EXPECT_TRUE(io(std::string(SCENARIO_ID) + "_is_active") != nullptr);
    EXPECT_TRUE(io(std::string(SCENARIO_ID) + "_step") != nullptr);
    EXPECT_TRUE(io(std::string(SCENARIO_ID) + "_timer") != nullptr);
    EXPECT_EQ("false", io(std::string(SCENARIO_ID) + "_step")->get_param("visible"));
}

TEST_F(JsonApiScenarioTest, AutoscenarioCreateSilentlyIgnoresAnActionOnAnUnknownIo)
{
    //JsonApi.cpp:1757-1760: `if (out)`. No error, no placeholder - the action
    //is simply not there, and the step is answered EMPTY. Exactly the same
    //silence T3.18 is about, reached from the create path instead of from a
    //deleted IO.
    loadScenarioHouse();

    WsTestSession ws;
    const std::string scenarioId = wsAutoscenario(ws, Json{
        { "type", "create" },
        { "room_name", E40C_ROOM_NAME },
        { "room_type", E40C_ROOM_TYPE },
        { "steps", Json::array({
            Json{{ "step_type", "standard" }, { "step_pause", "0" },
                 { "actions", Json::array({ Json{{ "id", "e40c_no_such_io" }, { "action", "true" }} }) }}
        }) }}).value("id", std::string());
    ASSERT_FALSE(scenarioId.empty());

    const Json sc = wsAutoscenario(ws, Json{{ "type", "get" }, { "id", scenarioId }});
    ASSERT_EQ(2u, sc["steps"].size());
    EXPECT_EQ("1", sc.value("steps_count", std::string()));
    EXPECT_TRUE(sc["steps"][0]["actions"].is_array());
    EXPECT_EQ(0u, sc["steps"][0]["actions"].size()) << sc["steps"][0].dump();
}

TEST_F(JsonApiScenarioTest, AutoscenarioCreateDropsTheActionsOfAStepPlacedAfterTheEndStep)
{
    //FROZEN BUG. buildAutoscenarioCreate() uses the index in the JSON ARRAY as
    //the step number (JsonApi.cpp:1743 `index_act = idx`), while addStep()
    //numbers the steps by how many standard steps already exist. Put the "end"
    //step first and the two numbering schemes drift by one: addStepAction() is
    //called with an out of range index, stepRule() answers null and the action
    //is dropped without a word (AutoScenario.cpp:687).
    loadScenarioHouse();

    WsTestSession ws;
    const std::string scenarioId = wsAutoscenario(ws, Json{
        { "type", "create" },
        { "room_name", E40C_ROOM_NAME },
        { "room_type", E40C_ROOM_TYPE },
        { "steps", Json::array({
            Json{{ "step_type", "end" },
                 { "actions", Json::array({ Json{{ "id", IO_STRING }, { "action", "done" }} }) }},
            Json{{ "step_type", "standard" }, { "step_pause", "0" },
                 { "actions", Json::array({ Json{{ "id", IO_BOOL }, { "action", "true" }} }) }}
        }) }}).value("id", std::string());
    ASSERT_FALSE(scenarioId.empty());

    const Json sc = wsAutoscenario(ws, Json{{ "type", "get" }, { "id", scenarioId }});
    ASSERT_EQ(2u, sc["steps"].size());
    //the end step kept its action...
    EXPECT_EQ(1u, sc["steps"][1]["actions"].size()) << sc["steps"][1].dump();
    //...and the standard step lost the one that was meant for it
    EXPECT_EQ(0u, sc["steps"][0]["actions"].size()) << sc["steps"][0].dump();
}

TEST_F(JsonApiScenarioTest, AutoscenarioCreateRaisesScenarioAddedAndIoAddedEvents)
{
    loadScenarioHouse();

    WsTestSession ws;
    ASSERT_FALSE(createReferenceScenario(ws).empty());

    ws.clear();
    pumpEventLoop();

    const std::vector<std::string> types = eventTypes(ws);
    EXPECT_TRUE(sawEvent(types, "scenario_added"));
    EXPECT_TRUE(sawEvent(types, "io_added"));
}

/*******************************************************************************
 * autoscenario modify
 *
 * buildAutoscenarioModify() (JsonApi.cpp:1801-1926) DELETES every step rule
 * first (deleteRules()) and rebuilds the scenario from the request. It is a
 * full replacement, never a patch, and it applies the same defaults as create
 * to every member the request omits.
 ******************************************************************************/

TEST_F(JsonApiScenarioTest, AutoscenarioModifyReplacesTheStepsWholesale)
{
    loadScenarioHouse();

    WsTestSession ws;
    const std::string scenarioId = createReferenceScenario(ws);
    ASSERT_FALSE(scenarioId.empty());

    const Json ret = wsAutoscenario(ws, Json{
        { "type", "modify" },
        { "id", scenarioId },
        { "name", "Soir\xc3\xa9""e" },
        { "room_name", E40C_ROOM_NAME },
        { "room_type", E40C_ROOM_TYPE },
        { "steps", Json::array({
            Json{{ "step_type", "standard" }, { "step_pause", "3" },
                 { "actions", Json::array({ Json{{ "id", IO_INT }, { "action", "7" }} }) }}
        }) }});
    EXPECT_JSON_EQ(std::string(R"({"success":"true"})"), ret);

    const Json sc = wsAutoscenario(ws, Json{{ "type", "get" }, { "id", scenarioId }});
    EXPECT_EQ("1", sc.value("steps_count", std::string()));
    ASSERT_EQ(2u, sc["steps"].size());
    EXPECT_EQ("3", sc["steps"][0].value("step_pause", std::string()));
    ASSERT_EQ(1u, sc["steps"][0]["actions"].size());
    EXPECT_EQ(IO_INT, sc["steps"][0]["actions"][0].value("id", std::string()));
    //the end step action of the previous version is gone too
    EXPECT_EQ(0u, sc["steps"][1]["actions"].size()) << sc["steps"][1].dump();
}

TEST_F(JsonApiScenarioTest, AutoscenarioModifyWithoutStepsWipesEveryStep)
{
    //Not a patch: a request that carries no "steps" member empties the
    //scenario and still answers success:true.
    loadScenarioHouse();

    WsTestSession ws;
    const std::string scenarioId = createReferenceScenario(ws);

    EXPECT_JSON_EQ(std::string(R"({"success":"true"})"),
                   wsAutoscenario(ws, Json{{ "type", "modify" }, { "id", scenarioId },
                                           { "name", "Soir\xc3\xa9""e" }}));

    const Json sc = wsAutoscenario(ws, Json{{ "type", "get" }, { "id", scenarioId }});
    EXPECT_EQ("0", sc.value("steps_count", std::string()));
    ASSERT_EQ(1u, sc["steps"].size()) << "only the synthetic end step is left";
    EXPECT_EQ("end", sc["steps"][0].value("step_type", std::string()));
}

TEST_F(JsonApiScenarioTest, TheGetPayloadCannotBeEchoedBackIntoModify)
{
    //FROZEN, and this is the most expensive one for a UI writer. What "get"
    //answers is NOT what "modify" reads:
    //  - get emits "enabled", modify reads "disabled" (the negation),
    //  - get emits neither "name", nor "visible", nor the room.
    //So a client replaying the payload it just received renames the scenario
    //to the localized default, hides it, and disables its schedule - with
    //success:true and no warning of any kind.
    loadScenarioHouse();

    WsTestSession ws;
    const std::string scenarioId = createReferenceScenario(ws);
    Scenario *sc = scenarioIo(scenarioId);
    ASSERT_TRUE(sc != nullptr);
    const std::string nameBefore = sc->get_param("name");

    //Make the scenario VISIBLE first. ADDED AFTER REVIEW: create() already
    //leaves visible="false", so asserting "false" after the echo proved
    //nothing at all - it would have passed even if modify never touched the
    //param. Starting from "true" is what turns the "and it hides it" half of
    //this divergence into a measurement instead of a reading of the code.
    sc->set_param("visible", "true");
    ASSERT_EQ("true", sc->get_param("visible"));

    Json echo = wsAutoscenario(ws, Json{{ "type", "get" }, { "id", scenarioId }});
    ASSERT_FALSE(echo.contains("name"));
    ASSERT_FALSE(echo.contains("visible"));
    ASSERT_FALSE(echo.contains("disabled"));
    ASSERT_FALSE(echo.contains("room_name"));

    echo["type"] = "modify";
    EXPECT_JSON_EQ(std::string(R"({"success":"true"})"), wsAutoscenario(ws, echo));

    sc = scenarioIo(scenarioId);
    ASSERT_TRUE(sc != nullptr);
    EXPECT_NE(nameBefore, sc->get_param("name")) << "the name survived, which it must not";
    //it really was hidden BY the echo: the param was "true" one line above
    EXPECT_EQ("false", sc->get_param("visible"));
    //"enabled":"false" was echoed back but modify never looked at it: it read
    //the absent "disabled", defaulted it to "true", and the two happen to agree
    EXPECT_EQ("true", sc->get_param("disabled"));
    //the steps, however, DID survive: they are the one thing both payloads
    //spell the same way
    const Json after = wsAutoscenario(ws, Json{{ "type", "get" }, { "id", scenarioId }});
    EXPECT_EQ("2", after.value("steps_count", std::string()));
}

TEST_F(JsonApiScenarioTest, AutoscenarioModifyOnAnUnknownIdIsWrongInput)
{
    loadScenarioHouse();

    WsTestSession ws;
    EXPECT_JSON_EQ(std::string(R"({"error":"wrong input"})"),
                   wsAutoscenario(ws, Json{{ "type", "modify" }, { "id", "e40c_no_such_io" }}));
    EXPECT_JSON_EQ(std::string(R"({"error":"wrong input"})"),
                   wsAutoscenario(ws, Json{{ "type", "modify" }, { "id", IO_INT }}));
}

TEST_F(JsonApiScenarioTest, AutoscenarioModifyRaisesIoChangedBeforeScenarioChanged)
{
    //JsonApi.cpp:1859-1875 and :1917. Only the members that CHANGED raise an
    //io_changed, and the scenario_changed always closes the sequence.
    loadScenarioHouse();

    WsTestSession ws;
    const std::string scenarioId = createReferenceScenario(ws);
    pumpEventLoop();
    ws.clear();

    ASSERT_JSON_EQ(std::string(R"({"success":"true"})"),
                   wsAutoscenario(ws, Json{{ "type", "modify" }, { "id", scenarioId },
                                           { "name", "Renamed" }, { "visible", "true" }}));
    ws.clear();
    pumpEventLoop();

    const std::vector<std::string> types = eventTypes(ws);
    ASSERT_TRUE(sawEvent(types, "io_changed"));
    ASSERT_TRUE(sawEvent(types, "scenario_changed"));
    //order is part of the contract: the per-member io_changed events come
    //first, the scenario_changed that tells the UI to refetch comes after
    EXPECT_LT(std::find(types.begin(), types.end(), "io_changed"),
              std::find(types.begin(), types.end(), "scenario_changed"));
}

/*******************************************************************************
 * autoscenario delete
 ******************************************************************************/

TEST_F(JsonApiScenarioTest, AutoscenarioDeleteRemovesTheScenarioItsInternalIosAndItsRules)
{
    loadScenarioHouse();

    WsTestSession ws;
    const std::string scenarioId = createReferenceScenario(ws);
    ASSERT_TRUE(io(std::string(SCENARIO_ID) + "_timer") != nullptr);
    const int rulesBefore = ListeRule::Instance().size();
    ASSERT_LT(0, rulesBefore);

    EXPECT_JSON_EQ(std::string(R"({"success":"true"})"),
                   wsAutoscenario(ws, Json{{ "type", "delete" }, { "id", scenarioId }}));

    EXPECT_TRUE(io(scenarioId) == nullptr);
    EXPECT_TRUE(io(std::string(SCENARIO_ID) + "_timer") == nullptr);
    EXPECT_TRUE(io(std::string(SCENARIO_ID) + "_step") == nullptr);
    EXPECT_TRUE(io(std::string(SCENARIO_ID) + "_is_active") == nullptr);
    EXPECT_EQ(0, ListeRule::Instance().size());

    //and it is gone from the list
    EXPECT_JSON_EQ(std::string(R"({"scenarios":[]})"),
                   wsAutoscenario(ws, Json{{ "type", "list" }}));

    //the house IOs are untouched
    EXPECT_TRUE(io(IO_BOOL) != nullptr);
    EXPECT_TRUE(io(IO_TARGET) != nullptr);
}

TEST_F(JsonApiScenarioTest, AutoscenarioDeleteOnAnUnknownIdIsWrongInput)
{
    loadScenarioHouse();

    WsTestSession ws;
    EXPECT_JSON_EQ(std::string(R"({"error":"wrong input"})"),
                   wsAutoscenario(ws, Json{{ "type", "delete" }, { "id", "e40c_no_such_io" }}));
    EXPECT_JSON_EQ(std::string(R"({"error":"wrong input"})"),
                   wsAutoscenario(ws, Json{{ "type", "delete" }, { "id", IO_RANGE }}));
}

/*******************************************************************************
 * autoscenario add_schedule / del_schedule
 ******************************************************************************/

TEST_F(JsonApiScenarioTest, AddScheduleAnswersTheIdOfTheTimeRangeItCreated)
{
    loadScenarioHouse();

    WsTestSession ws;
    const std::string scenarioId = createReferenceScenario(ws);

    const Json ret = wsAutoscenario(ws, Json{{ "type", "add_schedule" }, { "id", scenarioId }});
    ASSERT_TRUE(ret.is_object());
    EXPECT_EQ(1u, ret.size()) << ret.dump();
    EXPECT_EQ(SCENARIO_SCHEDULE_ID, ret.value("id", std::string()));

    //a real InPlageHoraire, addressable by get_timerange
    EXPECT_TRUE(dynamic_cast<InPlageHoraire *>(io(SCENARIO_SCHEDULE_ID)) != nullptr);

    //and the "schedule" key of the payload stops being the string "false" and
    //becomes that id
    const Json sc = wsAutoscenario(ws, Json{{ "type", "get" }, { "id", scenarioId }});
    EXPECT_EQ(SCENARIO_SCHEDULE_ID, sc.value("schedule", std::string()));
}

TEST_F(JsonApiScenarioTest, WsAutoscenarioGetOfAScheduledCyclingScenario)
{
    /* The second shape of the payload: scheduled and cycling, i.e. the two
     * members the default scenario of the other golden leaves at their default.
     *
     * THE THREE BOOLEAN-ISH KEYS ARE SET TO THREE DIFFERENT VALUES ON PURPOSE:
     * cycle "true", enabled "false" (disabled is left at true), schedule the id
     * of the time range. ADDED AFTER A REVIEW COUNTER-MUTATION: this case used
     * to send cycle:true AND disabled:false together, so cycle and enabled were
     * "false"/"false" in five goldens and "true"/"true" in this one - never in
     * disagreement. SWAPPING THE TWO KEY NAMES in IO/Scenario.cpp:89-90 left the
     * whole suite green. A payload key is only pinned when some case shows it
     * carrying a value one of its neighbours does not.
     *
     * Do not "tidy" this into cycle=enabled=true: it would silently un-pin the
     * pair again. The same reasoning applies to any key added here later,
     * including the three of T3.18 - broken and disabled_missing_io must
     * differ in at least one golden, and the repaired fixture is exactly the
     * one where they do.
     */
    loadScenarioHouse();

    WsTestSession ws;
    const std::string scenarioId = createReferenceScenario(ws);
    ASSERT_EQ(SCENARIO_SCHEDULE_ID,
              wsAutoscenario(ws, Json{{ "type", "add_schedule" }, { "id", scenarioId }})
                      .value("id", std::string()));
    ASSERT_JSON_EQ(std::string(R"({"success":"true"})"),
                   wsAutoscenario(ws, Json{{ "type", "modify" },
                                           { "id", scenarioId },
                                           { "name", "Soir\xc3\xa9""e" },
                                           { "cycle", "true" },
                                           { "disabled", "true" },
                                           { "room_name", E40C_ROOM_NAME },
                                           { "room_type", E40C_ROOM_TYPE },
                                           { "steps", Json::array({
                                               Json{{ "step_type", "standard" }, { "step_pause", "2.5" },
                                                    { "actions", Json::array({ Json{{ "id", IO_BOOL }, { "action", "true" }} }) }}
                                           }) }}));

    ws.clear();
    ws.send(wsRequest("autoscenario", Json{{ "type", "get" }, { "id", scenarioId }},
                      "e40c-sched"));
    ASSERT_EQ(1u, ws.count());
    EXPECT_JSON_GOLDEN("e40c_ws_autoscenario_get_scheduled", ws.lastMessage());

    //spelled out as well as pinned by the golden, so a swap of two key names
    //fails HERE with the key names in the message and not only in a diff
    const Json sc = ws.lastData();
    EXPECT_EQ("true", sc.value("cycle", std::string()));
    EXPECT_EQ("false", sc.value("enabled", std::string()));
    EXPECT_EQ(SCENARIO_SCHEDULE_ID, sc.value("schedule", std::string()));
}

TEST_F(JsonApiScenarioTest, AddScheduleTwiceAnswersTheSameIdAndCreatesNothingNew)
{
    //AutoScenario::addSchedule() returns immediately when ioTimeRange is
    //already there (AutoScenario.cpp:857), so the second call is a no-op that
    //still answers success. Pinned because "idempotent" is a property clients
    //rely on and nothing else states it.
    loadScenarioHouse();

    WsTestSession ws;
    const std::string scenarioId = createReferenceScenario(ws);

    ASSERT_EQ(SCENARIO_SCHEDULE_ID,
              wsAutoscenario(ws, Json{{ "type", "add_schedule" }, { "id", scenarioId }})
                      .value("id", std::string()));
    const int iosAfterFirst = ListeRoom::Instance().get_io_count();

    EXPECT_EQ(SCENARIO_SCHEDULE_ID,
              wsAutoscenario(ws, Json{{ "type", "add_schedule" }, { "id", scenarioId }})
                      .value("id", std::string()));
    EXPECT_EQ(iosAfterFirst, ListeRoom::Instance().get_io_count());
}

TEST_F(JsonApiScenarioTest, DelScheduleRemovesTheTimeRangeAndIsATolerantNoOpWithoutOne)
{
    loadScenarioHouse();

    WsTestSession ws;
    const std::string scenarioId = createReferenceScenario(ws);

    //no schedule yet: still success, nothing happens
    EXPECT_JSON_EQ(std::string(R"({"success":"true"})"),
                   wsAutoscenario(ws, Json{{ "type", "del_schedule" }, { "id", scenarioId }}));
    EXPECT_TRUE(io(SCENARIO_SCHEDULE_ID) == nullptr);

    ASSERT_EQ(SCENARIO_SCHEDULE_ID,
              wsAutoscenario(ws, Json{{ "type", "add_schedule" }, { "id", scenarioId }})
                      .value("id", std::string()));
    ASSERT_TRUE(io(SCENARIO_SCHEDULE_ID) != nullptr);

    EXPECT_JSON_EQ(std::string(R"({"success":"true"})"),
                   wsAutoscenario(ws, Json{{ "type", "del_schedule" }, { "id", scenarioId }}));
    EXPECT_TRUE(io(SCENARIO_SCHEDULE_ID) == nullptr);

    const Json sc = wsAutoscenario(ws, Json{{ "type", "get" }, { "id", scenarioId }});
    EXPECT_EQ("false", sc.value("schedule", std::string()));
}

TEST_F(JsonApiScenarioTest, ScheduleCommandsOnAnUnknownIdAreWrongInput)
{
    loadScenarioHouse();

    WsTestSession ws;
    EXPECT_JSON_EQ(std::string(R"({"error":"wrong input"})"),
                   wsAutoscenario(ws, Json{{ "type", "add_schedule" }, { "id", "e40c_nope" }}));
    EXPECT_JSON_EQ(std::string(R"({"error":"wrong input"})"),
                   wsAutoscenario(ws, Json{{ "type", "del_schedule" }, { "id", IO_RANGE }}));
}

/*******************************************************************************
 * >>> THE T3.18 BLOCK <<<
 *
 * Everything below characterizes what the API says about a scenario whose step
 * lost its IO. It says NOTHING today, which is the defect T3.18 corrects, and
 * that silence has never been recorded anywhere before this file.
 *
 * Two configurations are built, both from a REAL amputated configuration and
 * never by hand:
 *   - broken:  the IO is gone from io.xml, the step rule survives holding a
 *              dead reference (E4.2e keeps it verbatim), Rule::isDisabled() is
 *              true, and the payload shows an EMPTY STEP with no indication;
 *   - repaired: the same configuration with the IO put back. The reference
 *              resolves again, the payload is byte for byte the healthy one -
 *              while the rule is STILL disabled and the scenario still does
 *              nothing, because missingIoIds is only ever rebuilt at load.
 *
 * They are the two unhealthy goldens T3.18.md asks for. After T3.18 they carry
 * broken/disabled_missing_io as true/true and false/true respectively.
 ******************************************************************************/

TEST_F(JsonApiScenarioTest, ABrokenStepSilentlyLosesItsActionFromThePayload)
{
    //T3.18.md constat (d), measured here rather than argued: countRealActions()
    //skips the action because isScenarioInternalIO(nullptr) answers TRUE
    //(AutoScenario.cpp:706), so the step is answered with an empty "actions"
    //array - the exact shape of a step the user deliberately left empty.
    const std::string scenarioId = loadScenarioWithAnAmputatedStep();
    ASSERT_FALSE(scenarioId.empty());

    //the reference really is dead, and the rule really is disabled
    ASSERT_TRUE(io(IO_TARGET) == nullptr);
    Scenario *sc = scenarioIo(scenarioId);
    ASSERT_TRUE(sc != nullptr && sc->getAutoScenario() != nullptr);
    const std::vector<Rule *> steps = sc->getAutoScenario()->getRuleSteps();
    ASSERT_EQ(2u, steps.size()) << "the load path KEEPS the step rule";
    ASSERT_TRUE(steps[1] != nullptr);
    EXPECT_TRUE(steps[1]->isDisabled()) << "E4.2e should have disabled the step rule";

    WsTestSession ws;
    ws.send(wsRequest("autoscenario", Json{{ "type", "get" }, { "id", scenarioId }},
                      "e40c-broken"));
    ASSERT_EQ(1u, ws.count());
    EXPECT_JSON_GOLDEN("e40c_ws_autoscenario_get_broken", ws.lastMessage());

    const Json payload = ws.lastData();
    //the payload says the scenario has two steps and that one of them does
    //nothing. It does not say WHY, and it does not say the scenario is dead.
    EXPECT_EQ("2", payload.value("steps_count", std::string()));
    ASSERT_EQ(3u, payload["steps"].size());
    EXPECT_EQ(1u, payload["steps"][1]["actions"].size())
            << "only the surviving action of step 2 is left: " << payload["steps"][1].dump();
    EXPECT_EQ(IO_INT, payload["steps"][1]["actions"][0].value("id", std::string()));
    //not one key of the payload mentions the loss - THIS is what T3.18 changes
    for (const std::string &k: scenarioPayloadKeys())
        EXPECT_TRUE(payload.contains(k));
    EXPECT_EQ(scenarioPayloadKeys().size(), payload.size()) << payload.dump();
    /* T3.18 - EXPECTED VALUE FLIPPED. This used to be EXPECT_FALSE: the dead id
     * was nowhere in the payload, which is the silence the ticket removes. It
     * is now carried by "missing_ios", and the step is still rendered without
     * its action - the payload does not gain the action back, it gains the
     * DIAGNOSIS.
     */
    EXPECT_TRUE(mentionsValue(payload, IO_TARGET))
            << "missing_ios does not name the dead id: " << payload.dump();
    EXPECT_EQ(IO_TARGET, payload.value("missing_ios", std::string()));
    EXPECT_EQ("true", payload.value("broken", std::string()));
    EXPECT_EQ("true", payload.value("disabled_missing_io", std::string()));
}

TEST_F(JsonApiScenarioTest, ABrokenStepWhoseOnlyActionIsDeadIsAnsweredCompletelyEmpty)
{
    //The other half of the same defect: when the dead reference was the ONLY
    //user action of the step, the step is answered as
    //{"step_pause":..,"step_type":"standard","actions":[]} - indistinguishable
    //from a step the user created and left empty on purpose.
    loadScenarioHouse();

    std::string scenarioId;
    {
        WsTestSession ws;
        scenarioId = wsAutoscenario(ws, Json{
            { "type", "create" },
            { "room_name", E40C_ROOM_NAME },
            { "room_type", E40C_ROOM_TYPE },
            { "steps", Json::array({
                Json{{ "step_type", "standard" }, { "step_pause", "0" },
                     { "actions", Json::array({ Json{{ "id", IO_TARGET }, { "action", "true" }} }) }}
            }) }}).value("id", std::string());
    }
    ASSERT_FALSE(scenarioId.empty());

    saveConfig();
    std::string ioXml = ioXmlOnDisk();
    const std::string rulesXml = rulesXmlOnDisk();
    ASSERT_TRUE(removeIoFromXml(ioXml, IO_TARGET));

    clearCoreState();
    loadConfig(ioXml, rulesXml);
    ListeRoom::Instance().checkAutoScenario();
    pumpEventLoop();

    WsTestSession ws;
    const Json sc = wsAutoscenario(ws, Json{{ "type", "get" }, { "id", scenarioId }});
    ASSERT_EQ(2u, sc["steps"].size());
    EXPECT_EQ("standard", sc["steps"][0].value("step_type", std::string()));
    EXPECT_EQ(0u, sc["steps"][0]["actions"].size()) << sc["steps"][0].dump();
    EXPECT_EQ("1", sc.value("steps_count", std::string()));
}

TEST_F(JsonApiScenarioTest, PuttingTheIoBackWithoutAReloadLeavesTheRuleDisabledAndThePayloadSilent)
{
    //Halfway between broken and repaired, and the reason the two are kept
    //apart: recreating the IO makes ActionStd::get_output() resolve again
    //(it re-reads ListeRoom on every call, ActionStd.cpp:67-72) so the action
    //IS back in the payload - while Rule::isDisabled() stays TRUE, because
    //missingIoIds is only ever filled at load time (Rule.h:147, E4.2e). The
    //scenario therefore still does nothing, and the API shows a scenario in
    //perfect health.
    //T3.18 is what makes this state nameable: broken stays true here (the rule
    //is still disabled), disabled_missing_io is true, and the user is told to
    //restart or to re-enable.
    const std::string scenarioId = loadScenarioWithAnAmputatedStep();
    ASSERT_FALSE(scenarioId.empty());

    Json broken;
    {
        WsTestSession ws;
        broken = wsAutoscenario(ws, Json{{ "type", "get" }, { "id", scenarioId }});
    }

    //put the IO back, under the very same id, in the same room
    Params p = {{ "type", "InternalBool" }, { "id", IO_TARGET },
                { "name", "Target of the second step" }};
    ASSERT_TRUE(createIO(p, firstRoom()) != nullptr);
    pumpEventLoop();

    WsTestSession ws;
    const Json back = wsAutoscenario(ws, Json{{ "type", "get" }, { "id", scenarioId }});

    //the dead action is back in the payload, at its original place
    ASSERT_EQ(3u, back["steps"].size());
    ASSERT_EQ(2u, back["steps"][1]["actions"].size());
    EXPECT_EQ(IO_TARGET, back["steps"][1]["actions"][0].value("id", std::string()));
    EXPECT_NE(broken, back);

    //and the rule that drives that step is STILL disabled. No key of the
    //payload says so: the API never exposes Rule::isDisabled(), for a scenario
    //or for anything else.
    Scenario *sc = scenarioIo(scenarioId);
    ASSERT_TRUE(sc != nullptr && sc->getAutoScenario() != nullptr);
    const std::vector<Rule *> steps = sc->getAutoScenario()->getRuleSteps();
    ASSERT_EQ(2u, steps.size());
    ASSERT_TRUE(steps[1] != nullptr);
    EXPECT_TRUE(steps[1]->isDisabled())
            << "the rule is still disabled once the IO is back - that is the point";
    EXPECT_EQ(scenarioPayloadKeys().size(), back.size()) << back.dump();
}

TEST_F(JsonApiScenarioTest, RepairedScenarioIsIndistinguishableFromAHealthyOneUntilT3_18)
{
    /* >>> THE ASSERTION T3.18 HAS TO FLIP. <<<
     *
     * The full repair, as it happens in the field: the IO is put back in the
     * configuration and everything is loaded again. ActionStd::LoadFromXml()
     * resolves the id, nothing is recorded as missing, Rule::isDisabled() is
     * false - the scenario is, live, in perfect health.
     *
     * Today its payload is EQUAL, node for node, to the payload of the same
     * scenario that was never broken: nothing recalls that it was disabled,
     * and with T3.18 in place it will NOT be running (the sticky
     * disabled_missing_io survived in io.xml) while still looking healthy.
     * That is the "repaired, waiting for a manual re-enable" line of T3.18.md's
     * four state table, and the whole reason a sticky flag was asked for.
     *
     * T3.18, exactly one edit here: replace the final EXPECT_JSON_EQ by the
     * difference it introduces - repaired carries "broken":"false" AND
     * "disabled_missing_io":"true" where the healthy one carries "false" and
     * "false" - regenerate e40c_ws_autoscenario_get_repaired.json, and say in
     * the commit message that this file was written expecting it.
     */
    const std::string scenarioId = loadScenarioWithAnAmputatedStep();
    ASSERT_FALSE(scenarioId.empty());

    //put the IO back and take the configuration through a full save/reload
    //cycle, which is what a repair really is
    Params p = {{ "type", "InternalBool" }, { "id", IO_TARGET },
                { "name", "Target of the second step" }};
    ASSERT_TRUE(createIO(p, firstRoom()) != nullptr);
    saveConfig();
    reloadFromDisk();
    ListeRoom::Instance().checkAutoScenario();
    pumpEventLoop();

    WsTestSession ws;
    ws.send(wsRequest("autoscenario", Json{{ "type", "get" }, { "id", scenarioId }},
                      "e40c-repaired"));
    ASSERT_EQ(1u, ws.count());
    EXPECT_JSON_GOLDEN("e40c_ws_autoscenario_get_repaired", ws.lastMessage());

    const Json repaired = ws.lastData();

    //live state: nothing is missing any more, on any rule of the scenario
    Scenario *sc = scenarioIo(scenarioId);
    ASSERT_TRUE(sc != nullptr && sc->getAutoScenario() != nullptr);
    const std::vector<Rule *> steps = sc->getAutoScenario()->getRuleSteps();
    ASSERT_EQ(2u, steps.size());
    ASSERT_TRUE(steps[1] != nullptr);
    EXPECT_FALSE(steps[1]->isDisabled())
            << "the reload should have cleared the missing io of the step rule";

    //Rebuild the very same scenario from scratch, never broken, and compare.
    clearCoreState();
    loadScenarioHouse();
    WsTestSession fresh;
    const std::string healthyId = createReferenceScenario(fresh);
    ASSERT_EQ(scenarioId, healthyId);
    const Json healthy = wsAutoscenario(fresh, Json{{ "type", "get" }, { "id", healthyId }});

    /* >>> THE ASSERTION T3.18 FLIPPED. <<<
     * It used to be EXPECT_JSON_EQ(healthy, repaired): the two payloads were
     * equal node for node, which is precisely what made "was disabled, waiting
     * for a human" undetectable by a client. They now differ, and they differ
     * by EXACTLY ONE KEY - the sticky flag.
     */
    EXPECT_NE(healthy, repaired)
            << "the repaired scenario is still indistinguishable from a healthy one";

    //both live rules are healthy, so "broken" agrees on the two sides...
    EXPECT_EQ("false", healthy.value("broken", std::string()));
    EXPECT_EQ("false", repaired.value("broken", std::string()));
    EXPECT_EQ("", healthy.value("missing_ios", std::string()));
    EXPECT_EQ("", repaired.value("missing_ios", std::string()));

    //...and the ONLY thing that tells them apart is the persisted flag, which
    //survived the amputation, the repair and the reload. THE state of the
    //decision: "repaired, waiting for a manual re-enable".
    EXPECT_EQ("false", healthy.value("disabled_missing_io", std::string()));
    EXPECT_EQ("true", repaired.value("disabled_missing_io", std::string()));

    Json normalized = repaired;
    normalized["disabled_missing_io"] = "false";
    EXPECT_JSON_EQ(healthy, normalized)
            << "the two payloads differ by more than the sticky flag";
}

TEST_F(JsonApiScenarioTest, DeletingAnIoUsedByAStepKeepsTheStepRuleAndDisablesTheScenario)
{
    /* The HOT path, as opposed to the load path used by the cases above:
     * ListeRoom::deleteIO() -> detachIOFromRules() -> ListeRule::RemoveRule().
     *
     * T3.18 - EXPECTED VALUES FLIPPED, and the case RENAMED with them (it used
     * to be DeletingAnIoUsedByAStepDestroysTheWholeStepRule). RemoveRule() now
     * DISABLES instead of destroying: the step rule survives, so the step count
     * stays at 2, the surviving action of that step (IO_INT) is still rendered,
     * and the payload names the dead id in "missing_ios" instead of saying
     * nothing at all. Nothing is renumbered any more, because nothing
     * disappears.
     */
    loadScenarioHouse();

    WsTestSession ws;
    const std::string scenarioId = createReferenceScenario(ws);
    ASSERT_FALSE(scenarioId.empty());

    ASSERT_TRUE(io(IO_TARGET) != nullptr);
    ASSERT_TRUE(deleteIO(io(IO_TARGET)));
    pumpEventLoop();

    ws.clear();
    ws.send(wsRequest("autoscenario", Json{{ "type", "get" }, { "id", scenarioId }},
                      "e40c-hotdel"));
    ASSERT_EQ(1u, ws.count());
    EXPECT_JSON_GOLDEN("e40c_ws_autoscenario_get_hot_deleted", ws.lastMessage());

    const Json sc = ws.lastData();
    EXPECT_EQ("2", sc.value("steps_count", std::string()))
            << "the step rule was destroyed instead of being disabled";
    ASSERT_EQ(3u, sc["steps"].size());
    EXPECT_EQ("1.5", sc["steps"][0].value("step_pause", std::string()));
    //the action that SHARED the broken step is not collateral damage any more
    EXPECT_TRUE(mentionsValue(sc, IO_INT)) << sc.dump();
    //and the dead id is named, by "missing_ios" and only by it
    EXPECT_EQ(IO_TARGET, sc.value("missing_ios", std::string())) << sc.dump();
    EXPECT_EQ("true", sc.value("broken", std::string()));
    EXPECT_EQ("true", sc.value("disabled_missing_io", std::string()));
}

TEST_F(JsonApiScenarioTest, ModifyOfABrokenScenarioLosesTheDeadReferenceForever)
{
    //The round trip that makes the loss permanent. The client fetches the
    //scenario (the dead action is already invisible), sends it back with
    //modify, and buildAutoscenarioModify() rebuilds every step rule from what
    //it was given: the id that ActionStd::SaveToXml() had been preserving
    //verbatim since E4.2e is now really gone from rules.xml.
    //T3.18 does NOT fix this - modify is still a full replacement - but
    //"missing_ios" will at least tell the user what they are about to lose.
    const std::string scenarioId = loadScenarioWithAnAmputatedStep();
    ASSERT_FALSE(scenarioId.empty());

    saveConfig();
    ASSERT_NE(std::string::npos, rulesXmlOnDisk().find(IO_TARGET))
            << "the dead reference must still be on disk before the round trip";

    WsTestSession ws;
    Json echo = wsAutoscenario(ws, Json{{ "type", "get" }, { "id", scenarioId }});
    /* T3.18 - EXPECTED VALUE ADDED, the meaning of the case is unchanged. The
     * round trip still destroys the dead reference (modify is a full
     * replacement, T3.18 does not fix that), but the payload the client is
     * about to echo back now SAYS what is at stake instead of hiding it.
     */
    EXPECT_EQ(IO_TARGET, echo.value("missing_ios", std::string()));
    EXPECT_EQ("true", echo.value("broken", std::string()));
    EXPECT_EQ("true", echo.value("disabled_missing_io", std::string()));

    echo["type"] = "modify";
    echo["name"] = "Soir\xc3\xa9""e";
    echo["room_name"] = E40C_ROOM_NAME;
    echo["room_type"] = E40C_ROOM_TYPE;
    EXPECT_JSON_EQ(std::string(R"({"success":"true"})"), wsAutoscenario(ws, echo));

    saveConfig();
    EXPECT_EQ(std::string::npos, rulesXmlOnDisk().find(IO_TARGET))
            << "the dead reference survived the round trip, which it does not today";

    //and the payload is now the payload of a scenario that never had that
    //action: the step is still there, still empty of it, and nothing recalls it
    const Json after = wsAutoscenario(ws, Json{{ "type", "get" }, { "id", scenarioId }});
    EXPECT_EQ("2", after.value("steps_count", std::string()));
    ASSERT_EQ(3u, after["steps"].size());
    ASSERT_EQ(1u, after["steps"][1]["actions"].size());
    EXPECT_EQ(IO_INT, after["steps"][1]["actions"][0].value("id", std::string()));

    //the rule is not even disabled any more: it was rebuilt from a payload
    //that no longer mentions the missing IO
    Scenario *sc = scenarioIo(scenarioId);
    ASSERT_TRUE(sc != nullptr && sc->getAutoScenario() != nullptr);
    const std::vector<Rule *> steps = sc->getAutoScenario()->getRuleSteps();
    ASSERT_EQ(2u, steps.size());
    ASSERT_TRUE(steps[1] != nullptr);
    EXPECT_FALSE(steps[1]->isDisabled());

    /* T3.18: gate 1 is gone with the reference, but the STICKY flag is not -
     * modify does not touch it (ModifyDoesNotClearTheDisabledFlag pins that in
     * tests/core/ScenarioDisabledMissingIo_test.cpp). The scenario is left in
     * the "repaired, waiting for a manual re-enable" state, which is the one
     * this whole payload change exists to make visible.
     */
    EXPECT_EQ("false", after.value("broken", std::string()));
    EXPECT_EQ("true", after.value("disabled_missing_io", std::string()));
}

TEST_F(JsonApiScenarioTest, ABrokenScenarioIsStillListedAndStillModifiable)
{
    //No command of this API refuses to work on a broken scenario, and list
    //answers it like any other. Frozen so that T3.18 - which changes what the
    //payload SAYS, not which commands answer - cannot silently start refusing
    //one of them.
    const std::string scenarioId = loadScenarioWithAnAmputatedStep();

    WsTestSession ws;
    const Json list = wsAutoscenario(ws, Json{{ "type", "list" }});
    ASSERT_TRUE(list["scenarios"].is_array());
    ASSERT_EQ(1u, list["scenarios"].size());
    EXPECT_EQ(scenarioId, list["scenarios"][0].value("id", std::string()));

    EXPECT_JSON_EQ(std::string(R"({"id":"scenario_0_schedule"})"),
                   wsAutoscenario(ws, Json{{ "type", "add_schedule" }, { "id", scenarioId }}));
    EXPECT_JSON_EQ(std::string(R"({"success":"true"})"),
                   wsAutoscenario(ws, Json{{ "type", "del_schedule" }, { "id", scenarioId }}));
    EXPECT_JSON_EQ(std::string(R"({"success":"true"})"),
                   wsAutoscenario(ws, Json{{ "type", "delete" }, { "id", scenarioId }}));
}
