/******************************************************************************
 **  Copyright (c) 2006-2025, Calaos. All Rights Reserved.
 **
 **  This file is part of Calaos.
 **
 **  Calaos is free software; you can redistribute it and/or modify
 **  it under the terms of the GNU General Public License as published by
 **  the Free Software Foundation; either version 3 of the License, or
 **  (at your option) any later version.
 **
 **  Calaos is distributed in the hope that it will be useful,
 **  but WITHOUT ANY WARRANTY; without even the implied warranty of
 **  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 **  GNU General Public License for more details.
 **
 **  You should have received a copy of the GNU General Public License
 **  along with Foobar; if not, write to the Free Software
 **  Foundation, Inc., 51 Franklin St, Fifth Floor, Boston, MA  02110-1301  USA
 **
 ******************************************************************************/

/* T1.4 — hardening of the json api.
 *
 * Covers the parts that can be exercised without a running libuv loop and
 * without a real http client: the security helpers of JsonApi and the login
 * throttle state machine. The throttle takes the current time as a parameter
 * precisely so it can be driven here without any timer.
 */

#include "CalaosCoreFixture.h"

#include "JsonApi.h"
#include "FileUtils.h"
#include "LogSetup.h"

#include <fstream>
#include <sys/stat.h>

using namespace CalaosTest;

/******************************************************************************
 * Constant time comparison (F2)
 ******************************************************************************/

TEST(JsonApiSecureCompare, AcceptsIdenticalSecrets)
{
    EXPECT_TRUE(JsonApi::secureCompare("s3cr3t", "s3cr3t"));
    EXPECT_TRUE(JsonApi::secureCompare("", ""));

    //A real token: 64 hex chars, as generated by RAND_bytes
    const std::string token(64, 'a');
    EXPECT_TRUE(JsonApi::secureCompare(token, token));
}

TEST(JsonApiSecureCompare, RejectsDifferentSecrets)
{
    EXPECT_FALSE(JsonApi::secureCompare("s3cr3t", "S3cr3t"));
    EXPECT_FALSE(JsonApi::secureCompare("s3cr3t", "s3cr3T"));
    EXPECT_FALSE(JsonApi::secureCompare("s3cr3t", ""));
    EXPECT_FALSE(JsonApi::secureCompare("", "s3cr3t"));
}

TEST(JsonApiSecureCompare, RejectsPrefixOfTheSecret)
{
    //The old std::equal based check returned on the first differing byte and
    //compared sizes first, both leaking information through timing
    EXPECT_FALSE(JsonApi::secureCompare("s3cr3t", "s3cr"));
    EXPECT_FALSE(JsonApi::secureCompare("s3cr", "s3cr3t"));
}

TEST(JsonApiSecureCompare, HandlesEmbeddedNulBytes)
{
    std::string a("ab\0cd", 5);
    std::string b("ab\0ce", 5);

    EXPECT_TRUE(JsonApi::secureCompare(a, a));
    EXPECT_FALSE(JsonApi::secureCompare(a, b));
}

/******************************************************************************
 * Integer parameters given to calaos_picture (F7)
 ******************************************************************************/

TEST(JsonApiIntParam, AcceptsPlainIntegers)
{
    EXPECT_TRUE(JsonApi::isValidIntParam("100", 1, 10000));
    EXPECT_TRUE(JsonApi::isValidIntParam("1", 1, 10000));
    EXPECT_TRUE(JsonApi::isValidIntParam("10000", 1, 10000));
    EXPECT_TRUE(JsonApi::isValidIntParam("0", -360, 360));
    EXPECT_TRUE(JsonApi::isValidIntParam("-90", -360, 360));
}

TEST(JsonApiIntParam, RejectsArgumentInjection)
{
    //The command line used to be split on spaces: anything after a space was
    //an extra argv entry for calaos_picture
    EXPECT_FALSE(JsonApi::isValidIntParam("100 --flag", 1, 10000));
    EXPECT_FALSE(JsonApi::isValidIntParam("100 -r 90", 1, 10000));
    EXPECT_FALSE(JsonApi::isValidIntParam("100 /etc/passwd", 1, 10000));
    EXPECT_FALSE(JsonApi::isValidIntParam("--version", 1, 10000));
    EXPECT_FALSE(JsonApi::isValidIntParam("90 x", -360, 360));
}

TEST(JsonApiIntParam, RejectsNonIntegers)
{
    EXPECT_FALSE(JsonApi::isValidIntParam("", 1, 10000));
    EXPECT_FALSE(JsonApi::isValidIntParam("abc", 1, 10000));
    EXPECT_FALSE(JsonApi::isValidIntParam("1.5", 1, 10000));
    EXPECT_FALSE(JsonApi::isValidIntParam("0x10", 1, 10000));
    EXPECT_FALSE(JsonApi::isValidIntParam(" 100", 1, 10000));
    EXPECT_FALSE(JsonApi::isValidIntParam("100\n", 1, 10000));
    EXPECT_FALSE(JsonApi::isValidIntParam("+100", 1, 10000));
    EXPECT_FALSE(JsonApi::isValidIntParam("-", 1, 10000));
}

TEST(JsonApiIntParam, RejectsOutOfRangeValues)
{
    EXPECT_FALSE(JsonApi::isValidIntParam("0", 1, 10000));
    EXPECT_FALSE(JsonApi::isValidIntParam("10001", 1, 10000));
    EXPECT_FALSE(JsonApi::isValidIntParam("-1", 1, 10000));
    EXPECT_FALSE(JsonApi::isValidIntParam("361", -360, 360));
    //Does not overflow on huge values either
    EXPECT_FALSE(JsonApi::isValidIntParam("99999999999999999999", 1, 10000));
}

/******************************************************************************
 * Redaction of the credentials in the logs (F4)
 ******************************************************************************/

/* E4.1m ported these to nlohmann with the function. The ORACLE did not move:
 * a secret must not be readable and everything else must stay readable. Two
 * things were ADDED, both of them about what the port could have broken and
 * nothing else could see:
 *
 *  - RedactedDumpKeepsRawUtf8AndStaysIndented pins the FORM of this dump. It
 *    is the one dump() of the epic that deliberately does NOT set
 *    ensure_ascii, because it feeds a LOG and that log has never been ASCII:
 *    the previous call asked for INDENT(4) alone. Measured on a probe built
 *    against both libraries: with ensure_ascii = false the two forms agree byte
 *    for byte. This case is what makes that decision falsifiable - flip the
 *    flag and it reddens.
 *  - RedactedDumpDoesNotThrowOnInvalidUtf8 pins error_handler_t::replace. A
 *    bare dump() throws type_error.316 and nothing catches it above
 *    processApi(): that is std::terminate on a live connection, on a document
 *    the client wrote.
 */

TEST(JsonApiRedact, HidesCredentialFields)
{
    //Insertion order is NOT alphabetical, and the visible and the masked field
    //carry values from disjoint vocabularies: exchanging "cn_pass" and
    //"cn_user" in the sensitive list has to redden both halves of this case.
    Json j;
    j["cn_user"] = "admin";
    j["cn_pass"] = "sup3rs3cr3t";
    j["action"] = "get_home";

    const std::string dump = JsonApi::dumpJsonRedacted(j);

    EXPECT_EQ(dump.find("sup3rs3cr3t"), std::string::npos) << dump;
    EXPECT_NE(dump.find("***"), std::string::npos) << dump;
    //Everything that is not a secret is still readable
    EXPECT_NE(dump.find("get_home"), std::string::npos) << dump;
    EXPECT_NE(dump.find("admin"), std::string::npos) << dump;
}

TEST(JsonApiRedact, HidesCredentialFieldsWhateverTheKeyCase)
{
    //THE ONLY ORACLE OF THE TREE ON THE CASE FOLD. The whole sensitive list is
    //spelled in lower case, so the masking depends ENTIRELY on the
    //Utils::str_to_lower() applied to the key in dumpJsonRedacted(): drop that
    //one call and "CN_Pass" and "Authorization" stop being masked IN SILENCE,
    //with the whole rest of the suite still green. Both keys are realistic: a
    //client is free to spell its own field however it likes, and
    //"Authorization" is spelled with a capital A everywhere HTTP is written.
    //
    //⚠️ Each assertion comes in PAIRS - the secret is GONE and the pair is
    //STILL THERE, masked. A "find(secret) == npos" alone would also pass on a
    //dump that dropped the field altogether, which is a different bug and not
    //the one this case is about.
    Json j;
    j["CN_Pass"] = "M1XED_CASE_SECRET_THAT_MUST_NOT_REACH_THE_LOG";
    j["Authorization"] = "Bearer C4P1TAL_A_TOKEN_THAT_MUST_NOT_REACH_THE_LOG";
    j["Action"] = "get_home";

    const std::string dump = JsonApi::dumpJsonRedacted(j);

    EXPECT_EQ(dump.find("M1XED_CASE_SECRET_THAT_MUST_NOT_REACH_THE_LOG"),
              std::string::npos)
            << "the case fold is gone from dumpJsonRedacted(): " << dump;
    EXPECT_NE(dump.find("\"CN_Pass\": \"***\""), std::string::npos)
            << "masked, not dropped - the pair must survive: " << dump;

    EXPECT_EQ(dump.find("C4P1TAL_A_TOKEN_THAT_MUST_NOT_REACH_THE_LOG"),
              std::string::npos)
            << "the case fold is gone from dumpJsonRedacted(): " << dump;
    EXPECT_NE(dump.find("\"Authorization\": \"***\""), std::string::npos)
            << "masked, not dropped - the pair must survive: " << dump;

    //And a NON credential key in mixed case is still fully readable: the fold
    //must not be an excuse to mask everything.
    EXPECT_NE(dump.find("\"Action\": \"get_home\""), std::string::npos) << dump;
}

TEST(JsonApiRedact, HidesNestedAndServiceSecrets)
{
    Json data;
    data["cn_pass"] = "wspassword";
    data["token"] = "deadbeefservicetoken";
    data["old_pw"] = "oldpassword";
    data["new_pw"] = "newpassword";

    Json j;
    j["msg"] = "login";
    j["data"] = data;

    const std::string dump = JsonApi::dumpJsonRedacted(j);

    EXPECT_EQ(dump.find("wspassword"), std::string::npos) << dump;
    EXPECT_EQ(dump.find("deadbeefservicetoken"), std::string::npos) << dump;
    EXPECT_EQ(dump.find("oldpassword"), std::string::npos) << dump;
    EXPECT_EQ(dump.find("newpassword"), std::string::npos) << dump;
    EXPECT_NE(dump.find("login"), std::string::npos) << dump;
}

TEST(JsonApiRedact, HandlesNullAndArrays)
{
    //nullptr still answers the empty string: a null Json is the translation of
    //the null pointer the jansson version refused, and the two callers can
    //hand one over whenever a non throwing parse discards a bad message.
    EXPECT_EQ(JsonApi::dumpJsonRedacted(nullptr), std::string());
    EXPECT_EQ(JsonApi::dumpJsonRedacted(Json::parse("not json", nullptr, false)),
              std::string());

    Json item;
    item["password"] = "insidearray";
    Json j;
    j["items"] = Json::array({ item });

    const std::string dump = JsonApi::dumpJsonRedacted(j);

    EXPECT_EQ(dump.find("insidearray"), std::string::npos) << dump;
    EXPECT_NE(dump.find("***"), std::string::npos) << dump;
}

TEST(JsonApiRedact, RedactedDumpKeepsRawUtf8AndStaysIndented)
{
    //THE DELIBERATE EXCEPTION of E4.1m to invariant 3 of the epic, and the
    //only oracle that can see it. The value is a VALID code point, so no error
    //handler ever looks at it: this case is sensitive to ensure_ascii ONLY.
    Json j;
    j["name"] = "caf\xc3\xa9";

    const std::string dump = JsonApi::dumpJsonRedacted(j);

    EXPECT_NE(dump.find("caf\xc3\xa9"), std::string::npos)
            << "the log stopped carrying raw UTF-8: " << dump;
    EXPECT_EQ(dump.find("\\u00e9"), std::string::npos)
            << "ensure_ascii was turned on: the log bytes changed for nothing";
    EXPECT_EQ(dump.find("\\u00E9"), std::string::npos) << dump;
    //And it is still the INDENT(4) shape a human reads, not a compact line.
    EXPECT_NE(dump.find("\n    \"name\""), std::string::npos) << dump;
}

TEST(JsonApiRedact, RedactedDumpDoesNotThrowOnInvalidUtf8)
{
    //The probe is a byte pair that can never become valid UTF-8, so this case
    //is sensitive to the error handler ONLY. It asserts BOTH halves, so that
    //`strict` and `ignore` cannot redden the same assertion:
    //  - the call RETURNS (strict throws type_error.316 out of it),
    //  - and the bytes were REPLACED, not dropped (that is `ignore`).
    Json j;
    j["good"] = "readable";
    j["bad"] = std::string("head\xff\x80tail");

    std::string dump;
    ASSERT_NO_THROW(dump = JsonApi::dumpJsonRedacted(j))
            << "a bare dump() or a strict handler is back on the log path";

    //U+FFFD is EF BF BD in UTF-8, and there is one per bad byte.
    EXPECT_NE(dump.find("\xef\xbf\xbd\xef\xbf\xbd"), std::string::npos) << dump;
    EXPECT_EQ(dump.find("\xff\x80"), std::string::npos)
            << "the invalid bytes reached the log untouched";
    //Not a truncation: both ends of the value and the sibling pair survive.
    EXPECT_NE(dump.find("head"), std::string::npos) << dump;
    EXPECT_NE(dump.find("tail"), std::string::npos) << dump;
    EXPECT_NE(dump.find("readable"), std::string::npos) << dump;
}

/* T3.65 - THE WHOLE SENSITIVE LIST, ONE KEY AT A TIME.
 *
 * The four cases above name six of the eleven keys the list carries: dropping
 * "passwd", "pass", "old_password", "new_password" or "secret" from it used to
 * leave the whole suite green. Every key gets its own probe value here so that
 * removing any single one of them names itself in the failure.
 */
TEST(JsonApiRedact, MasksEveryKeyOfTheSensitiveList)
{
    const std::vector<std::string> sensitive =
    { "cn_pass", "password", "passwd", "pass", "token", "old_pw", "new_pw",
      "old_password", "new_password", "secret", "authorization" };

    Json j;
    for (const std::string &key: sensitive)
        j[key] = "LEAK_" + key + "_LEAK";

    //A key that CONTAINS a sensitive name without being one: the match is on
    //the whole key, and a substring match would mask this one too.
    j["passenger"] = "readable_passenger";
    j["action"] = "get_home";

    const std::string dump = JsonApi::dumpJsonRedacted(j);

    for (const std::string &key: sensitive)
    {
        //Both halves, always: "the secret is gone" alone would also pass on a
        //dump that dropped the pair, and "the pair is there" alone would pass
        //on a dump that never masked anything.
        EXPECT_EQ(dump.find("LEAK_" + key + "_LEAK"), std::string::npos)
                << key << " reached the log in clear: " << dump;
        EXPECT_NE(dump.find("\"" + key + "\": \"***\""), std::string::npos)
                << key << " is masked, or it is dropped: " << dump;
    }

    EXPECT_NE(dump.find("\"passenger\": \"readable_passenger\""), std::string::npos)
            << "the key match became a substring match: " << dump;
    EXPECT_NE(dump.find("\"action\": \"get_home\""), std::string::npos) << dump;
}

/******************************************************************************
 * What the log level does with the redacted request line (T3.65)
 ******************************************************************************/

/* THE PREMISE OF T3.65, AND THE ONLY PLACE IT IS FALSIFIABLE.
 *
 * LogStream appends whatever is streamed into it and looks at the level only
 * in its DESTRUCTOR: `cDebugDom(d) << expensive()` pays for expensive() at
 * every level, and prints it at one. dumpJsonRedacted() is that expensive
 * argument on the request path, and this case pins that at the level a stock
 * install runs (debug_level defaults to 4, INFO), nothing of it is ever
 * printed.
 *
 * std::cout is captured by its streambuf, not by the file descriptor: Logger
 * writes through the stream object and a redirected fd would also swallow what
 * the test framework prints.
 */
namespace
{

class CoutCapture
{
public:
    CoutCapture(): previous(std::cout.rdbuf(captured.rdbuf())) {}
    ~CoutCapture() { std::cout.rdbuf(previous); }

    CoutCapture(const CoutCapture &) = delete;
    CoutCapture &operator=(const CoutCapture &) = delete;

    std::string str() const { return captured.str(); }

private:
    std::ostringstream captured;
    std::streambuf *previous;
};

} //namespace

TEST(JsonApiRequestLog, TheNetworkDomainPrintsNothingAtDebugLevel)
{
    std::string debugOutput, infoOutput;

    {
        CoutCapture capture;
        cDebugDom("network") << "T365_DEBUG_MARKER";
        debugOutput = capture.str();
    }

    //The control: the very same domain, one level up, DOES print. Without it
    //this case would also pass on a capture that swallows everything.
    {
        CoutCapture capture;
        cInfoDom("network") << "T365_INFO_MARKER";
        infoOutput = capture.str();
    }

    EXPECT_EQ(debugOutput.find("T365_DEBUG_MARKER"), std::string::npos)
            << "the default log level is no longer INFO: " << debugOutput;
    EXPECT_NE(infoOutput.find("T365_INFO_MARKER"), std::string::npos)
            << infoOutput;
}

namespace
{

//One log line on the "network" domain, at a level chosen at run time.
void logNetworkAt(int level, const std::string &marker)
{
    switch (level)
    {
    case Logger::LOG_LEVEL_CRITICAL: cCriticalDom("network") << marker; break;
    case Logger::LOG_LEVEL_ERROR: cErrorDom("network") << marker; break;
    case Logger::LOG_LEVEL_WARNING: cWarningDom("network") << marker; break;
    case Logger::LOG_LEVEL_INFO: cInfoDom("network") << marker; break;
    case Logger::LOG_LEVEL_DEBUG: cDebugDom("network") << marker; break;
    default: FAIL() << "no macro for level " << level;
    }
}

} //namespace

/* THE GUARD OF T3.65 IS ONLY WORTH ANYTHING IF IT ANSWERS WHAT THE DESTRUCTOR
 * WOULD HAVE ANSWERED. It is asked one level too early, from the call site, so
 * this case asks BOTH and compares them, at every level the logger knows.
 *
 * The two counters at the end are what keeps it honest: a predicate stuck on
 * true and a predicate stuck on false both agree with the log at SOME level,
 * and only a case that sees printed and silent levels in the same run can tell
 * them apart.
 */
TEST(JsonApiRequestLog, TheDebugGuardAnswersWhatTheLogPrints)
{
    Logger *logger = Utils::calaosLogger("network");
    ASSERT_TRUE(logger != nullptr);

    int printedLevels = 0, silentLevels = 0;

    for (int level = Logger::LOG_LEVEL_CRITICAL; level <= Logger::LOG_LEVEL_DEBUG; level++)
    {
        const std::string marker = "T365_LEVEL_" + std::to_string(level);
        std::string output;

        {
            CoutCapture capture;
            logNetworkAt(level, marker);
            output = capture.str();
        }

        const bool printed = output.find(marker) != std::string::npos;
        EXPECT_EQ(logger->isLevelEnabled(level), printed)
                << "level " << level << ": the guard and the log disagree";

        printed? printedLevels++: silentLevels++;
    }

    EXPECT_GT(printedLevels, 0) << "no level printed: the comparison is vacuous";
    EXPECT_GT(silentLevels, 0) << "every level printed: the comparison is vacuous";
}

/******************************************************************************
 * Login throttle (F3)
 ******************************************************************************/

class JsonApiThrottleTest: public ::testing::Test
{
protected:
    void SetUp() override { LoginThrottle::clear(); }
    void TearDown() override { LoginThrottle::clear(); }
};

TEST_F(JsonApiThrottleTest, UnknownAddressIsNeverBlocked)
{
    EXPECT_FALSE(LoginThrottle::isBlocked("10.0.0.1", 1000.0));
    EXPECT_EQ(LoginThrottle::trackedCount(), 0);
}

TEST_F(JsonApiThrottleTest, FirstFailureOpensAOneSecondWindow)
{
    LoginThrottle::registerFailure("10.0.0.1", 1000.0);

    EXPECT_TRUE(LoginThrottle::isBlocked("10.0.0.1", 1000.0));
    EXPECT_TRUE(LoginThrottle::isBlocked("10.0.0.1", 1000.5));
    EXPECT_FALSE(LoginThrottle::isBlocked("10.0.0.1", 1001.0));
}

TEST_F(JsonApiThrottleTest, WindowGrowsExponentiallyAndIsCapped)
{
    double now = 1000.0;

    //1s, then 2s, then 4s, 8s...
    LoginThrottle::registerFailure("10.0.0.1", now);
    EXPECT_FALSE(LoginThrottle::isBlocked("10.0.0.1", now + 1.0));

    now += 1.0;
    LoginThrottle::registerFailure("10.0.0.1", now);
    EXPECT_TRUE(LoginThrottle::isBlocked("10.0.0.1", now + 1.5));
    EXPECT_FALSE(LoginThrottle::isBlocked("10.0.0.1", now + 2.0));

    now += 2.0;
    LoginThrottle::registerFailure("10.0.0.1", now);
    EXPECT_TRUE(LoginThrottle::isBlocked("10.0.0.1", now + 3.5));
    EXPECT_FALSE(LoginThrottle::isBlocked("10.0.0.1", now + 4.0));

    //Many more failures never lock the address out for more than MaxDelay
    for (int i = 0;i < 40;i++)
        LoginThrottle::registerFailure("10.0.0.1", now);

    EXPECT_TRUE(LoginThrottle::isBlocked("10.0.0.1", now + LoginThrottle::MaxDelay - 0.1));
    EXPECT_FALSE(LoginThrottle::isBlocked("10.0.0.1", now + LoginThrottle::MaxDelay));
}

TEST_F(JsonApiThrottleTest, ThrottleIsPerSourceAddress)
{
    LoginThrottle::registerFailure("10.0.0.1", 1000.0);

    EXPECT_TRUE(LoginThrottle::isBlocked("10.0.0.1", 1000.0));
    EXPECT_FALSE(LoginThrottle::isBlocked("10.0.0.2", 1000.0));
}

TEST_F(JsonApiThrottleTest, SuccessClearsTheBackoff)
{
    LoginThrottle::registerFailure("10.0.0.1", 1000.0);
    LoginThrottle::registerFailure("10.0.0.1", 1001.0);
    EXPECT_TRUE(LoginThrottle::isBlocked("10.0.0.1", 1001.5));

    LoginThrottle::registerSuccess("10.0.0.1");

    EXPECT_FALSE(LoginThrottle::isBlocked("10.0.0.1", 1001.5));
    EXPECT_EQ(LoginThrottle::trackedCount(), 0);

    //And the backoff starts again from the shortest window
    LoginThrottle::registerFailure("10.0.0.1", 1002.0);
    EXPECT_FALSE(LoginThrottle::isBlocked("10.0.0.1", 1003.0));
}

TEST_F(JsonApiThrottleTest, QuietEntriesExpire)
{
    LoginThrottle::registerFailure("10.0.0.1", 1000.0);
    EXPECT_EQ(LoginThrottle::trackedCount(), 1);

    //Nothing from that address for a long time: it is forgotten
    double later = 1000.0 + LoginThrottle::EntryTimeout + 1.0;
    EXPECT_FALSE(LoginThrottle::isBlocked("10.0.0.1", later));
    EXPECT_EQ(LoginThrottle::trackedCount(), 0);

    //A new failure from another address purges the stale ones as well
    LoginThrottle::registerFailure("10.0.0.5", 2000.0);
    LoginThrottle::registerFailure("10.0.0.6", 2000.0 + LoginThrottle::EntryTimeout + 1.0);
    EXPECT_EQ(LoginThrottle::trackedCount(), 1);
}

TEST_F(JsonApiThrottleTest, TableSizeIsBounded)
{
    //Spoofed source addresses must not be usable to eat memory
    for (int i = 0;i < LoginThrottle::MaxEntries + 500;i++)
    {
        std::string ip = "10.1." + std::to_string(i / 256) + "." + std::to_string(i % 256);
        LoginThrottle::registerFailure(ip, 1000.0 + i * 0.001);
    }

    EXPECT_LE(LoginThrottle::trackedCount(), LoginThrottle::MaxEntries);

    //The most recent addresses are the ones still tracked
    std::string last = "10.1." + std::to_string((LoginThrottle::MaxEntries + 499) / 256) + "." +
                       std::to_string((LoginThrottle::MaxEntries + 499) % 256);
    EXPECT_TRUE(LoginThrottle::isBlocked(last, 1000.0 + (LoginThrottle::MaxEntries + 499) * 0.001));
}

/******************************************************************************
 * Credentials and event pictures, both need the config/cache tree
 ******************************************************************************/

class JsonApiConfigTest: public CoreFixture
{
protected:
    void SetUp() override
    {
        CoreFixture::SetUp();
        LoginThrottle::clear();
    }

    std::string pushPicturesDir() const { return cacheDir() + "/push_pictures"; }

    void writePicture(const std::string &name)
    {
        ::mkdir(pushPicturesDir().c_str(), 0755);
        std::ofstream f((pushPicturesDir() + "/" + name).c_str());
        f << "jpegdata";
    }
};

TEST_F(JsonApiConfigTest, CheckCredentialsUsesTheConfiguredUser)
{
    //local_config.xml is seeded with a cn_user/cn_pass pair, which takes
    //precedence over calaos_user/calaos_password
    Utils::del_config_option("cn_user");
    Utils::del_config_option("cn_pass");

    Utils::set_config_option("calaos_user", "admin");
    Utils::set_config_option("calaos_password", "s3cr3t");

    EXPECT_TRUE(JsonApi::checkCredentials("admin", "s3cr3t"));
    EXPECT_FALSE(JsonApi::checkCredentials("admin", "s3cr3T"));
    EXPECT_FALSE(JsonApi::checkCredentials("admi", "s3cr3t"));
    EXPECT_FALSE(JsonApi::checkCredentials("admin", "s3cr3"));
    EXPECT_FALSE(JsonApi::checkCredentials("", ""));
}

TEST_F(JsonApiConfigTest, CheckCredentialsPrefersTheCalaosNetworkAccount)
{
    Utils::set_config_option("calaos_user", "admin");
    Utils::set_config_option("calaos_password", "s3cr3t");
    Utils::set_config_option("cn_user", "cnuser");
    Utils::set_config_option("cn_pass", "cnpass");

    EXPECT_TRUE(JsonApi::checkCredentials("cnuser", "cnpass"));
    EXPECT_FALSE(JsonApi::checkCredentials("admin", "s3cr3t"));

    Utils::del_config_option("cn_user");
    Utils::del_config_option("cn_pass");
}

TEST_F(JsonApiConfigTest, EventPictureResolvesAnExistingUid)
{
    writePicture("abcd1234.jpg");

    std::string out;
    ASSERT_TRUE(JsonApi::resolveEventPicture("abcd1234", out));
    EXPECT_NE(out.find("/push_pictures/abcd1234.jpg"), std::string::npos) << out;
    EXPECT_TRUE(FileUtils::exists(out));
}

TEST_F(JsonApiConfigTest, EventPictureRejectsPathTraversal)
{
    writePicture("abcd1234.jpg");

    //A file the api must never serve, one level above the cache directory
    std::ofstream secret((cacheDir() + "/secret.jpg").c_str());
    secret << "secret";
    secret.close();

    std::string out;

    EXPECT_FALSE(JsonApi::resolveEventPicture("../secret", out));
    EXPECT_TRUE(out.empty());

    EXPECT_FALSE(JsonApi::resolveEventPicture("../../../../../../etc/passwd", out));
    EXPECT_FALSE(JsonApi::resolveEventPicture("sub/../../secret", out));
    EXPECT_FALSE(JsonApi::resolveEventPicture("/etc/passwd", out));
    EXPECT_FALSE(JsonApi::resolveEventPicture(std::string("abcd1234\0/../secret", 19), out));
    EXPECT_FALSE(JsonApi::resolveEventPicture("", out));
    //Unknown uid, no information about the filesystem is given back
    EXPECT_FALSE(JsonApi::resolveEventPicture("doesnotexist", out));
}
