/******************************************************************************
 **  Copyright (c) 2006-2025, Calaos. All Rights Reserved.
 **
 **  This file is part of Calaos.
 **
 **  Calaos is free software; you can redistribute it and/or modify
 **  it under the terms of the GNU General Public License as published by
 **  the Free Software Foundation; either version 3 of the License, or
 **  (at your option) any later version.
 **
 **  Calaos is distributed in the hope that it will be useful,
 **  but WITHOUT ANY WARRANTY; without even the implied warranty of
 **  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 **  GNU General Public License for more details.
 **
 **  You should have received a copy of the GNU General Public License
 **  along with Foobar; if not, write to the Free Software
 **  Foundation, Inc., 51 Franklin St, Fifth Floor, Boston, MA  02110-1301  USA
 **
 ******************************************************************************/
/*******************************************************************************
 * E4.0a - the foundation of the JSON API characterization net, proven end to
 * end.
 *
 * This file is NOT the characterization campaign. E4.0b..E4.0f are. What it
 * has to demonstrate is that every mechanism of the harness works against the
 * real production code, so the five sub-tickets can start on it without
 * re-litigating anything:
 *
 *   - the semantic oracle behaves as specified (key order blind, array order
 *     significant, strict on types),
 *   - a golden file round trips: generated by the code, compared semantically,
 *   - a plain WS command answers a full payload (get_home),
 *   - a WS command with a second level of dispatch reaches its sub-handler
 *     (audio / audio_action),
 *   - the error and silence paths are observable (unknown action, unknown
 *     autoscenario type, command before login),
 *   - the HTTP transport is drivable with a real HttpClient built on an
 *     unconnected socket, headers included,
 *   - events are delivered once, and only once, the uvw loop is pumped.
 *
 * Everything here records the behaviour that exists today. Two cases pin what
 * are, unambiguously, production bugs (the autoscenario silence, the "unkown
 * audio_action" typo). They are frozen on purpose: fixing a behaviour while
 * characterizing it destroys the reference.
 ******************************************************************************/

#include "JsonApiCharacterization.h"

#include "EventManager.h"

using namespace Calaos;
using namespace CalaosTest;

class JsonApiCharacterizationTestSuite: public JsonApiCharacterizationTest
{
};

/*******************************************************************************
 * The oracle itself. Executable specification of the comparison contract: if
 * one of these ever fails, every golden in the series became meaningless.
 ******************************************************************************/

TEST_F(JsonApiCharacterizationTestSuite, OracleIsBlindToKeyOrder)
{
    //jansson emits insertion order, nlohmann emits sorted keys, and the user
    //has already accepted the change. The tree even emits the WS envelope in
    //two different orders today depending on the sendJson() overload.
    EXPECT_JSON_EQ(std::string(R"({"msg":"get_home","msg_id":"1","data":{"a":"b"}})"),
                   std::string(R"({"data":{"a":"b"},"msg_id":"1","msg":"get_home"})"));
}

TEST_F(JsonApiCharacterizationTestSuite, OracleIsStrictOnTypes)
{
    //"3" is not 3. The whole API is stringified today; a migration that
    //"improves" a stringified number into a JSON number must break the net.
    const Json stringy = Json::parse(R"({"type":"3"})");
    const Json numeric = Json::parse(R"({"type":3})");

    EXPECT_NE(stringy, numeric);
    EXPECT_FALSE(firstJsonDifference(stringy, numeric).empty());
    EXPECT_NE(std::string::npos, firstJsonDifference(stringy, numeric).find("/type"));
}

TEST_F(JsonApiCharacterizationTestSuite, OracleKeepsArrayOrderSignificant)
{
    //Room, IO and rule order drives evaluation order (invariant of the E4.2
    //series). Never sort an array before comparing.
    const Json a = Json::parse(R"({"home":[{"name":"A"},{"name":"B"}]})");
    const Json b = Json::parse(R"({"home":[{"name":"B"},{"name":"A"}]})");

    EXPECT_FALSE(firstJsonDifference(a, b).empty());
    EXPECT_NE(std::string::npos, firstJsonDifference(a, b).find("/home/0/name"));
}

TEST_F(JsonApiCharacterizationTestSuite, OracleReportsThePathOfTheFirstDivergence)
{
    //A raw EXPECT_EQ on a 200 key object is unusable during a migration. The
    //assertion has to say WHERE.
    const Json expected = Json::parse(
        R"({"home":[{"items":[{"id":"a","state":"true"},{"id":"b","state":"false"}]}]})");
    const Json actual = Json::parse(
        R"({"home":[{"items":[{"id":"a","state":"true"},{"id":"b","state":"true"}]}]})");

    const std::string diff = firstJsonDifference(expected, actual);
    EXPECT_NE(std::string::npos, diff.find("/home/0/items/1/state")) << diff;
}

TEST_F(JsonApiCharacterizationTestSuite, OracleReportsAMissingAndAnExtraKey)
{
    const Json expected = Json::parse(R"({"a":"1","b":"2"})");
    const Json missing = Json::parse(R"({"a":"1"})");
    const Json extra = Json::parse(R"({"a":"1","b":"2","c":"3"})");

    EXPECT_NE(std::string::npos, firstJsonDifference(expected, missing).find("/b"));
    EXPECT_NE(std::string::npos, firstJsonDifference(expected, extra).find("/c"));
}

/*******************************************************************************
 * A plain command, full payload, against a versioned golden.
 ******************************************************************************/

TEST_F(JsonApiCharacterizationTestSuite, WsGetHomeMatchesGolden)
{
    loadReferenceHouse();

    WsTestSession ws;
    ws.send(Json{{ "msg", "get_home" }, { "msg_id", "42" }});

    ASSERT_EQ(1u, ws.count());
    EXPECT_JSON_GOLDEN("ws_get_home", ws.lastMessage());
}

TEST_F(JsonApiCharacterizationTestSuite, WsGetHomeEnvelopeCarriesTheMsgId)
{
    loadReferenceHouse();

    WsTestSession ws;
    ws.send(Json{{ "msg", "get_home" }, { "msg_id", "42" }});

    ASSERT_EQ(1u, ws.count());
    const Json env = ws.lastEnvelope();
    ASSERT_TRUE(env.is_object());
    EXPECT_EQ("get_home", env.value("msg", std::string()));
    EXPECT_EQ("42", env.value("msg_id", std::string()));
    ASSERT_TRUE(env.contains("data"));
    //get_home answers three top level members, always present, even empty.
    EXPECT_TRUE(env["data"].contains("home"));
    EXPECT_TRUE(env["data"].contains("cameras"));
    EXPECT_TRUE(env["data"].contains("audio"));
}

TEST_F(JsonApiCharacterizationTestSuite, WsGetHomeKeepsRoomAndIoOrder)
{
    loadReferenceHouse();

    WsTestSession ws;
    ws.send(Json{{ "msg", "get_home" }, { "msg_id", "1" }});

    ASSERT_EQ(1u, ws.count());
    const Json home = ws.lastEnvelope()["data"]["home"];
    ASSERT_TRUE(home.is_array());
    ASSERT_EQ(2u, home.size());
    EXPECT_EQ(HOUSE_ROOM1_NAME, home[0].value("name", std::string()));
    EXPECT_EQ(HOUSE_ROOM2_NAME, home[1].value("name", std::string()));

    const Json items = home[0]["items"];
    ASSERT_EQ(4u, items.size());
    EXPECT_EQ(HOUSE_BOOL_IN, items[0].value("id", std::string()));
    EXPECT_EQ(HOUSE_BOOL_OUT, items[1].value("id", std::string()));
    EXPECT_EQ(HOUSE_INT, items[2].value("id", std::string()));
    EXPECT_EQ(HOUSE_STRING, items[3].value("id", std::string()));
}

TEST_F(JsonApiCharacterizationTestSuite, NonAsciiSurvivesTheEscapingDifference)
{
    //jansson dumps with JSON_ENSURE_ASCII, so the wire carries É escapes;
    //nlohmann writes raw UTF-8. Parsing dissolves the difference, which is why
    //the oracle can be semantic. This is the case that proves it.
    loadReferenceHouse();

    WsTestSession ws;
    ws.send(Json{{ "msg", "get_home" }, { "msg_id", "1" }});

    ASSERT_EQ(1u, ws.count());

    //the raw wire really does carry the escape, not the UTF-8 bytes (jansson
    //writes the hex digits in upper case, hence the normalisation)
    std::string wire = ws.lastMessage();
    for (char &c: wire)
        c = (char)::tolower((unsigned char)c);
    EXPECT_NE(std::string::npos, wire.find("\\u00c9"));
    EXPECT_EQ(std::string::npos, ws.lastMessage().find("\xc3\x89"));

    const Json items = ws.lastEnvelope()["data"]["home"][1]["items"];
    ASSERT_EQ(1u, items.size());
    EXPECT_EQ("\xc3\x89" "clairage caf\xc3\xa9", items[0].value("name", std::string()));
}

/*******************************************************************************
 * The HTTP transport, driven through a real HttpClient on an unconnected
 * socket. This is the measurement that settles point (b) of E4.0.md.
 ******************************************************************************/

TEST_F(JsonApiCharacterizationTestSuite, HttpGetHomeMatchesGolden)
{
    loadReferenceHouse();

    HttpTestRequest req;
    req.send(authenticated(Json{{ "action", "get_home" }}));

    ASSERT_EQ(1u, req.count());
    EXPECT_JSON_GOLDEN("http_get_home", req.body());
}

TEST_F(JsonApiCharacterizationTestSuite, HttpSuccessResponseHeaders)
{
    loadReferenceHouse();

    HttpTestRequest req;
    req.send(authenticated(Json{{ "action", "get_home" }}));

    ASSERT_EQ(1u, req.count());
    EXPECT_EQ("HTTP/1.0 200 OK", req.statusLine());
    EXPECT_EQ("application/json", req.header("Content-Type"));
    EXPECT_EQ("Close", req.header("Connection"));
    EXPECT_EQ("no-cache, must-revalidate", req.header("Cache-Control"));
    EXPECT_EQ(req.body().size(), (size_t)std::stoul(req.header("Content-Length")));
}

TEST_F(JsonApiCharacterizationTestSuite, HttpAndWsAgreeOnTheGetHomePayload)
{
    //The HTTP body is, by construction, the dump of the same object the WS
    //envelope carries under "data". Pinning that equality is what lets the
    //other sub-tickets characterize a payload once instead of twice.
    loadReferenceHouse();

    WsTestSession ws;
    ws.send(Json{{ "msg", "get_home" }, { "msg_id", "1" }});
    ASSERT_EQ(1u, ws.count());

    HttpTestRequest req;
    req.send(authenticated(Json{{ "action", "get_home" }}));
    ASSERT_EQ(1u, req.count());

    EXPECT_JSON_EQ(ws.lastData(), req.bodyJson());
}

/*******************************************************************************
 * Second level of dispatch, and the error paths.
 ******************************************************************************/

TEST_F(JsonApiCharacterizationTestSuite, WsAudioReachesItsSubDispatch)
{
    //Frozen as is, typo included: production answers "unkown audio_action".
    loadReferenceHouse();

    WsTestSession ws;
    ws.send(Json{{ "msg", "audio" },
                 { "msg_id", "7" },
                 { "data", {{ "audio_action", "no_such_sub_action" }} }});

    ASSERT_EQ(1u, ws.count());
    EXPECT_JSON_EQ(std::string(R"({"msg":"audio","msg_id":"7",)"
                               R"("data":{"error":"unkown audio_action"}})"),
                   ws.lastMessage());
}

TEST_F(JsonApiCharacterizationTestSuite, WsAutoscenarioWithUnknownTypeAnswersNothing)
{
    //KNOWN BUG, FROZEN. processAutoscenario() has no else branch
    //(JsonApiHandlerWS.cpp:474-491), so an unknown type gets no answer at all,
    //not even an error. Silence is observable behaviour: the client waits
    //forever. Pinned here so the migration cannot change it by accident; a fix
    //belongs to a ticket of its own, after E4.1.
    loadReferenceHouse();

    WsTestSession ws;
    ws.send(Json{{ "msg", "autoscenario" },
                 { "msg_id", "8" },
                 { "data", {{ "type", "no_such_type" }} }});

    pumpEventLoop();

    EXPECT_EQ(0u, ws.count()) << "expected silence, got: " << ws.lastMessage();
    EXPECT_TRUE(ws.closes().empty());
}

TEST_F(JsonApiCharacterizationTestSuite, WsIgnoresEverythingBeforeLogin)
{
    //Anything but login/login_service falls through the `else if (loggedin)`
    //and produces no answer at all.
    loadReferenceHouse();

    WsTestSession ws(false /*authenticated*/);
    ws.send(Json{{ "msg", "get_home" }, { "msg_id", "1" }});

    EXPECT_EQ(0u, ws.count()) << "expected silence, got: " << ws.lastMessage();
}

TEST_F(JsonApiCharacterizationTestSuite, WsIgnoresANonObjectPayload)
{
    loadReferenceHouse();

    WsTestSession ws;
    ws.send(std::string("this is not json at all"));
    ws.send(std::string("[1,2,3]"));

    EXPECT_EQ(0u, ws.count()) << "expected silence, got: " << ws.lastMessage();
}

TEST_F(JsonApiCharacterizationTestSuite, HttpUnknownActionIsAnError)
{
    loadReferenceHouse();

    HttpTestRequest req;
    req.send(authenticated(Json{{ "action", "no_such_action" }}));

    ASSERT_EQ(1u, req.count());
    EXPECT_EQ("HTTP/1.0 200 OK", req.statusLine());
    EXPECT_JSON_EQ(std::string(R"({"error":"unknown action"})"), req.body());
}

TEST_F(JsonApiCharacterizationTestSuite, HttpWrongCredentialsGetA400AndACloseRequest)
{
    //sendLoginFailed() dereferences httpClient without a guard: this case is
    //the proof that a real HttpClient on an unconnected socket is enough to
    //characterize the HTTP side, error paths included.
    loadReferenceHouse();

    HttpTestRequest req;
    req.send(Json{{ "action", "get_home" },
                  { "cn_user", "wrong" },
                  { "cn_pass", "wrong" }});

    ASSERT_EQ(1u, req.count());
    EXPECT_EQ("HTTP/1.0 400 Bad Request", req.statusLine());
    EXPECT_EQ("text/html", req.header("Content-Type"));
    ASSERT_EQ(1u, req.closes().size());
    EXPECT_EQ(0, req.closes().front().first);
}

TEST_F(JsonApiCharacterizationTestSuite, HttpNonJsonBodyWithoutGetParamsIsRejected)
{
    //No JSON and no usable GET parameters: credentials are empty, so the
    //request never even reaches the dispatch table.
    loadReferenceHouse();

    HttpTestRequest req;
    req.send(std::string("not json"));

    ASSERT_EQ(1u, req.count());
    EXPECT_EQ("HTTP/1.0 400 Bad Request", req.statusLine());
}

TEST_F(JsonApiCharacterizationTestSuite, HttpAcceptsCredentialsFromGetParameters)
{
    //The GET parameter fallback (JsonApiHandlerHttp.cpp:81-90) is a documented
    //entry point of the HTTP API, and the only way to reach the 400 of the
    //`else` branch with valid credentials.
    loadReferenceHouse();

    Params getParams;
    getParams.Add("cn_user", apiUser());
    getParams.Add("cn_pass", apiPassword());
    getParams.Add("action", "get_home");

    HttpTestRequest req;
    req.send(std::string("not json"), getParams);

    ASSERT_EQ(1u, req.count());
    EXPECT_EQ("HTTP/1.0 200 OK", req.statusLine());
    EXPECT_TRUE(req.bodyJson().contains("home"));
}

/*******************************************************************************
 * Events. E4.0d owns the campaign; what is proven here is the pump, which
 * settles point (c) of E4.0.md.
 ******************************************************************************/

TEST_F(JsonApiCharacterizationTestSuite, EventsAreOnlyDeliveredOnceTheLoopIsPumped)
{
    loadReferenceHouse();

    WsTestSession ws;

    Params p;
    p.Add("state", "true");
    EventManager::create(CalaosEvent::EventIOChanged, HOUSE_BOOL_IN, p,
                         false /*logHistory*/);

    //EventManager queues into a uvw Idler. Without a loop iteration the queue
    //simply grows and nothing is ever delivered - exactly what
    //CalaosCoreFixture.h warns about.
    ASSERT_EQ(0u, ws.count());

    pumpEventLoop();

    ASSERT_EQ(1u, ws.count());
    const Json env = ws.lastEnvelope();
    EXPECT_EQ("event", env.value("msg", std::string()));
    //push events are unsolicited: no msg_id
    EXPECT_FALSE(env.contains("msg_id"));
    ASSERT_TRUE(env.contains("data"));
    EXPECT_EQ("io_changed", env["data"].value("type_str", std::string()));
    //every value is a string, the enum is stringified
    EXPECT_TRUE(env["data"]["type"].is_string());
    EXPECT_EQ(HOUSE_BOOL_IN, env["data"]["data"].value("id", std::string()));
}

TEST_F(JsonApiCharacterizationTestSuite, EventsAreNotDeliveredToASessionThatIsNotLoggedIn)
{
    loadReferenceHouse();

    WsTestSession ws(false /*authenticated*/);

    Params p;
    p.Add("state", "true");
    EventManager::create(CalaosEvent::EventIOChanged, HOUSE_BOOL_IN, p, false);

    pumpEventLoop();

    EXPECT_EQ(0u, ws.count()) << "expected silence, got: " << ws.lastMessage();
}
