name: Build and Publish dev docker image

on:
    push:
      branches: [ master ]

env:
  REGISTRY_IMAGE: ghcr.io/calaos/calaos_base
  NAME: calaos_base
  IMG_TAG: dev

jobs:
  # define job to build and publish docker image
  build-and-push-docker-image:
    name: Build Docker image and push to repositories
    # run only when code is compiling and tests are passing
    runs-on: ubuntu-latest

    # steps to perform in job
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Calaos Action Bump Version
        id: calaos_version
        uses: calaos/action-bump-version@1.0.0
        with:
          version-fragment: 'prerelease'

      - name: Docker meta
        id: meta
        uses: docker/metadata-action@v4
        with:
          images: ${{ env.REGISTRY_IMAGE }}

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to Github Packages
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      
      - name: Build and push by digest
        id: build
        uses: docker/build-push-action@v4
        with:
          context: .
          push: true
          build-args: APP_VERSION=${{ steps.calaos_version.outputs.version-bumped }}
          tags: |
            ${{ env.REGISTRY_IMAGE }}:${{ env.IMG_TAG }}
            ${{ env.REGISTRY_IMAGE }}:${{ steps.calaos_version.outputs.version-bumped }}

      - name: Create Tag
        uses: negz/create-tag@v1
        with:
          version: ${{ steps.calaos_version.outputs.version-bumped }}
          token: ${{ secrets.ACTION_DISPATCH }}

      - name: Build deb
        uses: peter-evans/repository-dispatch@v1
        with:
          token: ${{ secrets.ACTION_DISPATCH }}
          repository: calaos/pkgdebs
          event-type: build_deb
          client-payload: '{ "pkgname": "calaos-server", "version": "${{ steps.calaos_version.outputs.version-bumped }}", "image_src": "${{ env.REGISTRY_IMAGE }}:${{ steps.calaos_version.outputs.version-bumped }}", "prerelease": true }'

