name: Build and Publish docker image

on:
  workflow_dispatch:
    inputs:
      vincrement:
        description: 'Package version increment (major.feature.bug)'
        required: true
        default: 'bug'
        type: choice
        options:
          - major
          - feature
          - bug

env:
  REGISTRY_IMAGE: ghcr.io/calaos/calaos_base

jobs:
  # define job to build and publish docker image
  build-and-push-docker-image:
    name: Build Docker image and push to repositories
    # run only when code is compiling and tests are passing
    runs-on: ubuntu-latest

    # steps to perform in job
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Fetch latest release version
        id: fetch-latest-release
        uses: reloc8/action-latest-release-version@1.0.0

      - name: Increment dev release version
        id: bump_version
        uses: christian-draeger/increment-semantic-version@1.1.0
        with:
          current-version: ${{ steps.fetch-latest-release.outputs.latest-release }}
          version-fragment: ${{ github.event.inputs.vincrement }}

      - name: Docker meta
        id: meta
        uses: docker/metadata-action@v4
        with:
          images: ${{ env.REGISTRY_IMAGE }}

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to Github Packages
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      
      - name: Build and push by digest
        id: build
        uses: docker/build-push-action@v4
        with:
          context: .
          push: true
          build-args: APP_VERSION=${{ steps.bump_version.outputs.next-version }}
          tags: |
            ghcr.io/calaos/calaos_base:latest
            ghcr.io/calaos/calaos_base:${{ steps.bump_version.outputs.next-version }}

      - name: Create Tag
        uses: negz/create-tag@v1
        with:
          version: ${{ steps.bump_version.outputs.next-version }}
          token: ${{ secrets.ACTION_DISPATCH }}

      - name: update calaos release
        uses: fjogeleit/http-request-action@v1
        with:
          url: 'https://releases.calaos.fr/v4/image/calaos_base'
          method: 'POST'
          customHeaders: '{"Content-Type": "application/json"}'
          bearerToken: ${{ secrets.CALAOS_REL_TOKEN }}
          data: '{"name": "calaos_base", "source": "ghcr.io/calaos/calaos_base:${{ steps.bump_version.outputs.next-version }}", "version": "${{ steps.bump_version.outputs.next-version }}"}'
