name: Build

on:
  workflow_dispatch:

  push:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Repository Dispatch
        uses: peter-evans/repository-dispatch@v1
        with:
          token: ${{ secrets.ACTION_DISPATCH }}
          repository: calaos/calaos-build
          event-type: build_pkg
          client-payload: '{ "pkgname": "calaos-server", "repo": "calaos-dev", "arch": "x86_64" }'
